### PR TITLE
[SDL3] SDL_SetWindowIcon now reports errors.

### LINKED ISSUE #1473: SDL_SetWindowIcon fails silently
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Windows 7, x86_64

# Comments on the original bug report:

On 2014-05-10 03:04:29 +0000, Adam M. wrote:

> SDL_SetWindowIcon can fail (e.g. try setting a 64x64 icon), but there is no way to detect the failure. SDL_SetWindowIcon should return a result code like the other methods that can fail.

On 2014-05-10 03:11:47 +0000, Adam M. wrote:

> A 64x64 icon in Windows 7, that is. (See # 2533.) I imagine there are other reasons it can fail as well.

On 2015-02-19 06:32:14 +0000, Ryan C. Gordon wrote:

> Marking a large number of bugs with the "triage-2.0.4" keyword at once. Sorry
> if you got a lot of email from this. This is to help me sort through some bugs
> in regards to a 2.0.4 release. We may or may not fix this bug for 2.0.4,
> though!

On 2015-02-25 01:30:04 +0000, Gerry JJ wrote:

> I don't know if this is expected, but SDL 2 is pickier than SDL 1 about what it'll accept as an icon. A game i've been porting to SDL 2 sets a 512x512 icon, and that used to work fine with SDL_WM_SetIcon in SDL 1, but fails with SDL_SetWindowIcon in SDL 2. 256x256 works. (Ubuntu 14.10 64-bit, Unity desktop)
> 
> By the way, Ubuntu's Unity dash will cache icons, so setting an icon may appear to work even if it doesn't. Renaming the executable to something new works around that.

On 2015-04-07 04:57:56 +0000, Ryan C. Gordon wrote:

> 
> (sorry if you get a lot of copies of this email, I'm marking several bugs at once)
> 
> Marking bugs for the (mostly) final 2.0.4 TODO list. This means we're hoping to resolve this bug before 2.0.4 ships if possible. In a perfect world, the open bug count with the target-2.0.4 keyword is zero when we ship.
> 
> (Note that closing a bug report as WONTFIX, INVALID or WORKSFORME might still happen.)
> 
> --ryan.

On 2015-04-08 06:35:19 +0000, Ryan C. Gordon wrote:

> 
> This is an API change, so we'll hold off on this until 2.1. As such, I've removed the target-2.0.4 keyword and will leave this bug open.
> 
> Related Bug # 2533 is still being looked at for 2.0.4, however!
> 
> --ryan.

On 2017-08-14 13:48:58 +0000, Sam Lantinga wrote:

> Marking this for review for SDL 2.1

### PR DESCRIPTION
**Pull request by MisterIcy**
## Description
As described in the issue, when `SDL_SetWindowIcon` fails, it does so silently. This PR changes:
1. The signature of the function so that it return `0` on success or an integer on error
2. Calls `SDL_GetError` in order to report what when wrong while trying to set the Window's Icon.

Calling this function on a system which does not support setting a window's icon (or it is meaningless to do so), will always return `SDL_UNSUPPORTED`.

## Existing Issue(s)
Closes #1473

### CODE REVIEW

File: src/video/windows/SDL_windowswindow.c [hunk 1]
```diff
@@ -669,12 +670,21 @@ void WIN_SetWindowIcon(_THIS, SDL_Window *window, SDL_Surface *icon)
 
     SDL_small_free(icon_bmp, isstack);
 
+    if (hicon == NULL) {
+        SDL_SetError("SDL_SetWindowIcon(): Unable to create a resource from the icon");
+        retVal = (int)GetLastError();
```
Comment (MisterIcy) [inline src/video/windows/SDL_windowswindow.c:675]: I am not sure that:

1. We should return at this point or let `SendMessage` be executed
2. We should actually poll windows to return a proper error message.

File: src/video/x11/SDL_x11window.c [hunk 2]
```diff
@@ -738,52 +738,83 @@ void X11_SetWindowTitle(_THIS, SDL_Window *window)
...
+        }
+
+        X11_XChangeProperty(display, data->xwindow, _NET_WM_ICON, XA_CARDINAL,
                                 32, PropModeReplace, (unsigned char *)propdata,
                                 propsize);
-        }
         SDL_free(propdata);
+
+        if (caught_x11_error) {
+            SDL_SetError("SDL_SetWindowIcon(): An error occurred while trying to set the window's icon");
```
Comment (MisterIcy) [inline src/video/x11/SDL_x11window.c:795]: Also, not sure if we have to actually get the error X reported and properly report it to the caller.

**Comment by sezero** [comment]
A lot of void functions have been changed into returning int,
that includes SDL_SetWindowIcon as of following commit:
https://github.com/libsdl-org/SDL/commit/375bde8a4fc6a5ca413dea13c3e47de1bae974a8

The question is, do we want the backend changes in this pull
request: @slouken?

**Comment by 1bsyl** [comment]
I've proposed some diff to resolve the merge. hope this is ok!

File: src/video/haiku/SDL_bwindow.cc [hunk 3]
```diff
@@ -127,8 +127,10 @@ void HAIKU_SetWindowTitle(_THIS, SDL_Window * window) {
     _ToBeWin(window)->PostMessage(&msg);
 }
 
-void HAIKU_SetWindowIcon(_THIS, SDL_Window * window, SDL_Surface * icon) {
-    /* FIXME: Icons not supported by Haiku */
+int HAIKU_SetWindowIcon(_THIS, SDL_Window * window, SDL_Surface * icon) {
+    /* Icons not supported by Haiku */
+    SDL_Unsupported();
+    return SDL_UNSUPPORTED;
```
Comment (sezero) [inline src/video/haiku/SDL_bwindow.cc:133]: `return SDL_Unsupported();` instead

File: src/video/kmsdrm/SDL_kmsdrmvideo.c [hunk 4]
```diff
@@ -1560,8 +1560,10 @@ int KMSDRM_CreateWindowFrom(_THIS, SDL_Window *window, const void *data)
 void KMSDRM_SetWindowTitle(_THIS, SDL_Window *window)
 {
 }
-void KMSDRM_SetWindowIcon(_THIS, SDL_Window *window, SDL_Surface *icon)
+int KMSDRM_SetWindowIcon(_THIS, SDL_Window *window, SDL_Surface *icon)
 {
+    SDL_Unsupported();
+    return SDL_UNSUPPORTED;
```
Comment (sezero) [inline src/video/kmsdrm/SDL_kmsdrmvideo.c:1566]: `return SDL_Unsupported();` instead

File: src/video/psp/SDL_pspvideo.c [hunk 5]
```diff
@@ -216,8 +216,10 @@ int PSP_CreateWindowFrom(_THIS, SDL_Window *window, const void *data)
 void PSP_SetWindowTitle(_THIS, SDL_Window *window)
 {
 }
-void PSP_SetWindowIcon(_THIS, SDL_Window *window, SDL_Surface *icon)
+int PSP_SetWindowIcon(_THIS, SDL_Window *window, SDL_Surface *icon)
 {
+    SDL_Unsupported();
+    return SDL_UNSUPPORTED;
```
Comment (sezero) [inline src/video/psp/SDL_pspvideo.c:222]: `return SDL_Unsupported();` instead

File: src/video/raspberry/SDL_rpivideo.c [hunk 6]
```diff
@@ -352,6 +352,8 @@ void RPI_SetWindowTitle(_THIS, SDL_Window *window)
 }
 void RPI_SetWindowIcon(_THIS, SDL_Window *window, SDL_Surface *icon)
 {
+    SDL_Unsupported();
+    return SDL_UNSUPPORTED;
```
Comment (sezero) [inline src/video/raspberry/SDL_rpivideo.c:356]: `return SDL_Unsupported();` instead

File: src/video/vita/SDL_vitavideo.c [hunk 7]
```diff
@@ -304,8 +304,10 @@ int VITA_CreateWindowFrom(_THIS, SDL_Window *window, const void *data)
 void VITA_SetWindowTitle(_THIS, SDL_Window *window)
 {
 }
-void VITA_SetWindowIcon(_THIS, SDL_Window *window, SDL_Surface *icon)
+int VITA_SetWindowIcon(_THIS, SDL_Window *window, SDL_Surface *icon)
 {
+    SDL_Unsupported();
+    return SDL_UNSUPPORTED;
```
Comment (sezero) [inline src/video/vita/SDL_vitavideo.c:310]: `return SDL_Unsupported();` instead

File: src/video/windows/SDL_windowswindow.c [hunk 8]
```diff
@@ -677,12 +678,21 @@ void WIN_SetWindowIcon(_THIS, SDL_Window *window, SDL_Surface *icon)
...
+    }
+
     /* Set the icon for the window */
     SendMessage(hwnd, WM_SETICON, ICON_SMALL, (LPARAM)hicon);
 
     /* Set the icon in the task manager (should we do this?) */
     SendMessage(hwnd, WM_SETICON, ICON_BIG, (LPARAM)hicon);
+#else
+    SDL_Unsupported();
+    retVal = SDL_UNSUPPORTED;
```
Comment (sezero) [inline src/video/windows/SDL_windowswindow.c:693]: `return SDL_Unsupported();` instead

File: include/SDL3/SDL_video.h [hunk 9]
```diff
@@ -743,6 +743,9 @@ extern DECLSPEC const char *SDLCALL SDL_GetWindowTitle(SDL_Window *window);
 /**
  * Set the icon for a window.
  *
+ * Systems that do not support setting an icon to the window, will always fail,
+ * reporting `SDL_UNSUPPORTED`.
```
Comment (sezero) [inline include/SDL3/SDL_video.h:747]: I don't think that extra complexity of returning `SDL_UNSUPPORTED` is necessary.

File: src/video/cocoa/SDL_cocoawindow.m [hunk 10]
```diff
@@ -1874,14 +1874,18 @@ void Cocoa_SetWindowTitle(_THIS, SDL_Window *window)
...
     @autoreleasepool {
         NSImage *nsimage = Cocoa_CreateImage(icon);
 
         if (nsimage) {
             [NSApp setApplicationIconImage:nsimage];
+
+            return 0;
         }
+
+        return -1;
```
Comment (sezero) [inline src/video/cocoa/SDL_cocoawindow.m:1888]: Set some error message here?

File: src/video/x11/SDL_x11window.c [hunk 11]
```diff
@@ -739,52 +739,83 @@ void X11_SetWindowTitle(_THIS, SDL_Window *window)
...
-            dst = &propdata[2];
-            for (y = 0; y < icon->h; ++y) {
-                src = (Uint32 *)((Uint8 *)icon->pixels + y * icon->pitch);
-                for (x = 0; x < icon->w; ++x) {
-                    *dst++ = *src++;
-                }
+
+        if (!propdata) {
+            SDL_OutOfMemory();
+            return SDL_ENOMEM;
```
Comment (sezero) [inline src/video/x11/SDL_x11window.c:774]: `return SDL_OutOfMemory();` instead

File: src/video/x11/SDL_x11window.c [hunk 12]
```diff
@@ -739,52 +739,83 @@ void X11_SetWindowTitle(_THIS, SDL_Window *window)
...
+            SDL_SetError("SDL_SetWindowIcon(): An error occurred while trying to set the window's icon");
+            retVal = -1;
+        }
+
     } else {
+        prevHandler = X11_XSetErrorHandler(X11_CatchAnyError);
         X11_XDeleteProperty(display, data->xwindow, _NET_WM_ICON);
+
+        if (caught_x11_error) {
+            SDL_SetError("SDL_SetWindowIcon(): An error occurred while trying to unset the window's icon");
```
Comment (sezero) [inline src/video/x11/SDL_x11window.c:805]: `retVal = SDL_SetError("SDL_SetWindowIcon(): An error occurred while trying to unset the window's icon");` instead,
(and similar above.)

**Comment by sezero** [comment]
> A lot of void functions have been changed into returning int, that includes SDL_SetWindowIcon as of following commit: [375bde8](https://github.com/libsdl-org/SDL/commit/375bde8a4fc6a5ca413dea13c3e47de1bae974a8)
> 
> The question is, do we want the backend changes in this pull request: @slouken?

PING @slouken: do we want these changes (also review my reviews if you can),
or should we close this one?

**Comment by slouken** [comment]
I think generally we want the backend to propagate errors, but I don't know if we need this specific implementation. Does anyone want to clean this PR up, or submit a new one?

**Comment by MisterIcy** [comment]
@sezero thank you very much for the suggestions. Most of them were addressed in https://github.com/libsdl-org/SDL/pull/7081/commits/29b19f3d3dc2a3e456e089babaab8afbe00d31f5

File: src/video/SDL_video.c [hunk 13]
```diff
@@ -2060,21 +2060,22 @@ int SDL_SetWindowIcon(SDL_Window *window, SDL_Surface *icon)
...
+        return SDL_InvalidParamError("icon");
     }
 
     SDL_DestroySurface(window->icon);
 
     /* Convert the icon into ARGB8888 */
     window->icon = SDL_ConvertSurfaceFormat(icon, SDL_PIXELFORMAT_ARGB8888);
     if (!window->icon) {
-        return -1;
+        return SDL_SetError("SDL_SetWindowIcon(): Unable to convert the icon's format");
```
Comment (sezero) [inline src/video/SDL_video.c:2071]: Nitpicking: `SDL_SetWindowIcon(): ` part can be dropped from the message

File: src/video/cocoa/SDL_cocoawindow.m [hunk 14]
```diff
@@ -1874,14 +1874,18 @@ void Cocoa_SetWindowTitle(_THIS, SDL_Window *window)
...
     @autoreleasepool {
         NSImage *nsimage = Cocoa_CreateImage(icon);
 
         if (nsimage) {
             [NSApp setApplicationIconImage:nsimage];
+
+            return 0;
         }
+
+        return SDL_SetError("SDL_SetWindowIcon(): Unable to set the window's icon");
```
Comment (sezero) [inline src/video/cocoa/SDL_cocoawindow.m:1888]: Similar as above

File: src/video/windows/SDL_windowswindow.c [hunk 15]
```diff
@@ -677,12 +678,20 @@ void WIN_SetWindowIcon(_THIS, SDL_Window *window, SDL_Surface *icon)
 
     SDL_small_free(icon_bmp, isstack);
 
+    if (hicon == NULL) {
+        SDL_SetError("SDL_SetWindowIcon(): Unable to create a resource from the icon");
```
Comment (sezero) [inline src/video/windows/SDL_windowswindow.c:682]: Similar to above

File: src/video/x11/SDL_x11window.c [hunk 16]
```diff
@@ -739,52 +739,80 @@ void X11_SetWindowTitle(_THIS, SDL_Window *window)
...
+        }
+
+        X11_XChangeProperty(display, data->xwindow, _NET_WM_ICON, XA_CARDINAL,
                                 32, PropModeReplace, (unsigned char *)propdata,
                                 propsize);
-        }
         SDL_free(propdata);
+
+        if (caught_x11_error) {
+            retVal = SDL_SetError("SDL_SetWindowIcon(): An error occurred while trying to set the window's icon");
```
Comment (sezero) [inline src/video/x11/SDL_x11window.c:795]: Similar to above

File: src/video/x11/SDL_x11window.c [hunk 17]
```diff
@@ -739,52 +739,80 @@ void X11_SetWindowTitle(_THIS, SDL_Window *window)
...
+        }
+
     } else {
+        prevHandler = X11_XSetErrorHandler(X11_CatchAnyError);
         X11_XDeleteProperty(display, data->xwindow, _NET_WM_ICON);
+
+        if (caught_x11_error) {
+            retVal = SDL_SetError("SDL_SetWindowIcon(): An error occurred while trying to unset the window's icon");
```
Comment (sezero) [inline src/video/x11/SDL_x11window.c:803]: Similar to above

File: include/SDL3/SDL_video.h (hunk 9 above)
Comment (sezero) [reply include/SDL3/SDL_video.h:747]: I guess this doc addition can be dropped now?

**Comment by sezero** [comment]
Also: Can you rebase to current main, squash into a single patch, and force-push after you finalize ?

File: src/video/windows/SDL_windowswindow.c (hunk 1 above)
Comment (sezero) [reply src/video/windows/SDL_windowswindow.c:683]: @slouken can help with those concerns better

File: src/video/x11/SDL_x11window.c (hunk 2 above)
Comment (sezero) [reply src/video/x11/SDL_x11window.c]: @slouken can help with those concerns better

**Comment by sezero** [comment]
@slouken: The patch is now updated and squashed. Awaits your review.

File: src/video/SDL_video.c [hunk 18]
```diff
@@ -2060,21 +2060,22 @@ int SDL_SetWindowIcon(SDL_Window *window, SDL_Surface *icon)
...
+        return SDL_SetError("SDL_SetWindowIcon(): Invalid surface");
     }
 
     SDL_DestroySurface(window->icon);
 
     /* Convert the icon into ARGB8888 */
     window->icon = SDL_ConvertSurfaceFormat(icon, SDL_PIXELFORMAT_ARGB8888);
     if (!window->icon) {
-        return -1;
+        return SDL_SetError("Unable to convert the icon's format");
```
Comment (slouken) [inline src/video/SDL_video.c:2071]: SDL_ConvertSurfaceFormat() will provide an error message, this additional error isn't needed.

File: src/video/cocoa/SDL_cocoawindow.m [hunk 19]
```diff
@@ -1874,14 +1874,18 @@ void Cocoa_SetWindowTitle(_THIS, SDL_Window *window)
...
     @autoreleasepool {
         NSImage *nsimage = Cocoa_CreateImage(icon);
 
         if (nsimage) {
             [NSApp setApplicationIconImage:nsimage];
+
+            return 0;
         }
+
+        return SDL_SetError("Unable to set the window's icon");
```
Comment (slouken) [inline src/video/cocoa/SDL_cocoawindow.m:1888]: Does Cocoa_CreateImage() set a more detailed error?

File: src/video/haiku/SDL_bwindow.cc [hunk 20]
```diff
@@ -127,8 +127,9 @@ void HAIKU_SetWindowTitle(_THIS, SDL_Window * window) {
     _ToBeWin(window)->PostMessage(&msg);
 }
 
-void HAIKU_SetWindowIcon(_THIS, SDL_Window * window, SDL_Surface * icon) {
-    /* FIXME: Icons not supported by Haiku */
+int HAIKU_SetWindowIcon(_THIS, SDL_Window * window, SDL_Surface * icon) {
+    /* Icons not supported by Haiku */
```
Comment (slouken) [inline src/video/haiku/SDL_bwindow.cc:131]: This whole function can be removed. We now return SDL_Unsupported() if there is no driver implementation.

File: src/video/kmsdrm/SDL_kmsdrmvideo.c [hunk 21]
```diff
@@ -1560,8 +1560,9 @@ int KMSDRM_CreateWindowFrom(_THIS, SDL_Window *window, const void *data)
 void KMSDRM_SetWindowTitle(_THIS, SDL_Window *window)
 {
 }
-void KMSDRM_SetWindowIcon(_THIS, SDL_Window *window, SDL_Surface *icon)
+int KMSDRM_SetWindowIcon(_THIS, SDL_Window *window, SDL_Surface *icon)
 {
+    return SDL_Unsupported();
```
Comment (slouken) [inline src/video/kmsdrm/SDL_kmsdrmvideo.c:1565]: Same here

File: src/video/psp/SDL_pspvideo.c [hunk 22]
```diff
@@ -216,8 +216,9 @@ int PSP_CreateWindowFrom(_THIS, SDL_Window *window, const void *data)
 void PSP_SetWindowTitle(_THIS, SDL_Window *window)
 {
 }
-void PSP_SetWindowIcon(_THIS, SDL_Window *window, SDL_Surface *icon)
+int PSP_SetWindowIcon(_THIS, SDL_Window *window, SDL_Surface *icon)
 {
+    return SDL_Unsupported();
```
Comment (slouken) [inline src/video/psp/SDL_pspvideo.c:221]: and here, etc.

File: src/video/windows/SDL_windowswindow.c (hunk 1 above)
Comment (slouken) [reply src/video/windows/SDL_windowswindow.c:683]: We definitely shouldn't return this error, we should return -1, but you can show the error number in the error message, like we do here:
```c
return SDL_SetError("GetClientRect() failed, error %08X", (unsigned int)GetLastError());
```

File: src/video/x11/SDL_x11window.c [hunk 23]
```diff
@@ -739,52 +739,80 @@ void X11_SetWindowTitle(_THIS, SDL_Window *window)
...
-                src = (Uint32 *)((Uint8 *)icon->pixels + y * icon->pitch);
-                for (x = 0; x < icon->w; ++x) {
-                    *dst++ = *src++;
-                }
+
+        if (!propdata) {
+            return SDL_OutOfMemory();
+        }
+
+        prevHandler = X11_XSetErrorHandler(X11_CatchAnyError);
```
Comment (slouken) [inline src/video/x11/SDL_x11window.c:776]: You might need to do an XFlush() or XSync() here to make sure we don't get an X11 error from a previous operation.

File: src/video/cocoa/SDL_cocoawindow.m (hunk 19 above)
Comment (MisterIcy) [reply src/video/cocoa/SDL_cocoawindow.m:1888]: Unfortunately, it does not.

File: src/video/haiku/SDL_bwindow.cc (hunk 20 above)
Comment (MisterIcy) [reply src/video/haiku/SDL_bwindow.cc:131]: So both the definition and the declaration can be removed for drivers that do not support setting a window's icon? @slouken

Comment (slouken) [reply src/video/haiku/SDL_bwindow.cc:131]: Yes

File: src/video/x11/SDL_x11window.c [hunk 24]
```diff
@@ -739,52 +739,72 @@ void X11_SetWindowTitle(_THIS, SDL_Window *window)
...
-            X11_XChangeProperty(display, data->xwindow, _NET_WM_ICON, XA_CARDINAL,
+        }
+
+        X11_XChangeProperty(display, data->xwindow, _NET_WM_ICON, XA_CARDINAL,
                                 32, PropModeReplace, (unsigned char *)propdata,
                                 propsize);
-        }
         SDL_free(propdata);
-    } else {
-        X11_XDeleteProperty(display, data->xwindow, _NET_WM_ICON);
```
Comment (MisterIcy) [inline src/video/x11/SDL_x11window.c:776]: Also removed this branch, since `icon` cannot be null anymore

**Comment by slouken** [comment]
Looks good, thanks!

File: src/video/x11/SDL_x11window.c (hunk 24 above)
Comment (sezero) [reply src/video/x11/SDL_x11window.c:776]: @slouken, @MisterIcy: Do we not need to `X11_XDeleteProperty(display, data->xwindow, _NET_WM_ICON);` if we hit `caught_x11_error`?

Also, since icon can't be NULL anymore, we can remove  `if (icon) {` ?
