### PR TITLE
`wayland`: Remove freed display from `SDL_WaylandOutputData->output_list`

### LINKED ISSUE #6035: Crash on display disconnect/connect on Wayland
Since f39500297c17e65b4886df0a17e6e8e692f4a3a9, when disconnecting and reconnecting monitors a few times, the following backtrace is generated:
```
#0  0x00007f2fc5483403 in Wayland_add_display (d=0x5585b2a50e10, id=91) at .../SDL/src/video/wayland/SDL_waylandvideo.c:723
#1  0x00007f2fc548370f in display_handle_global (data=0x5585b2a50e10, registry=0x5585b2a50cb0, id=91, interface=0x5585b354a6e0 "wl_output", version=2) at .../SDL/src/video/wayland/SDL_waylandvideo.c:836
#2  0x00007f2fc45ee536 in ffi_call_unix64 () at ../src/x86/unix64.S:105
#3  0x00007f2fc45eb037 in ffi_call_int (cif=<optimized out>, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>, closure=<optimized out>) at ../src/x86/ffi64.c:672
#4  0x00007f2fc45fa645 in wl_closure_invoke (closure=closure@entry=0x5585b354a600, target=<optimized out>, target@entry=0x5585b2a50cb0, opcode=opcode@entry=0, data=<optimized out>, flags=1) at ../wayland-1.21.0/src/connection.c:1025
#5  0x00007f2fc45fae03 in dispatch_event (display=display@entry=0x5585b2a50f60, queue=0x5585b2a51030) at ../wayland-1.21.0/src/wayland-client.c:1595
#6  0x00007f2fc45faffc in dispatch_queue (queue=0x5585b2a51030, display=0x5585b2a50f60) at ../wayland-1.21.0/src/wayland-client.c:1741
#7  wl_display_dispatch_queue_pending (display=0x5585b2a50f60, queue=0x5585b2a51030) at ../wayland-1.21.0/src/wayland-client.c:1983
#8  0x00007f2fc547a81f in Wayland_WaitEventTimeout (_this=0x5585b2a50550, timeout=382) at .../SDL/src/video/wayland/SDL_waylandevents.c:312
#9  0x00007f2fc52582a8 in SDL_WaitEventTimeout_Device (_this=0x5585b2a50550, wakeup_window=0x5585b2a9d220, event=0x0, start=21212, timeout=382) at .../SDL/src/events/SDL_events.c:972
#10 0x00007f2fc52585de in SDL_WaitEventTimeout_REAL (event=0x0, timeout=382) at .../SDL/src/events/SDL_events.c:1087
#11 0x00007f2fc524a2ab in SDL_WaitEventTimeout (a=0x0, b=382) at .../SDL/src/dynapi/SDL_dynapi_procs.h:158
```

This seems to be caused by not removing the disconnected display from `SDL_WaylandOutputData->output_list`.

### PR DESCRIPTION
**Pull request by Guldoman**
## Description

Since f39500297c17e65b4886df0a17e6e8e692f4a3a9 when a display is freed it isn't removed from `SDL_WaylandOutputData->output_list`.
When a new display is added, the `output_list->next` chain is explored, which can cause a segmentation fault.

With this PR the chain is modified accordingly when `Wayland_free_display` is called.

## Existing Issue(s)

Fixes #6035.

### CODE REVIEW

File: src/video/wayland/SDL_waylandvideo.c [hunk 1]
```diff
@@ -747,6 +747,17 @@ Wayland_free_display(uint32_t id)
         display = SDL_GetDisplay(i);
         data = (SDL_WaylandOutputData *) display->driverdata;
         if (data->registry_id == id) {
+            if (d->output_list != NULL) {
+                SDL_WaylandOutputData *node = d->output_list;
+                if (node == data) {
+                    d->output_list = node->next;
+                } else {
+                    while (node->next != data) {
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandvideo.c:755]: Not that I expect it to happen, but might be good to have an escape path:
```suggestion
                    while (node->next != data && node->next != NULL) {
```
Aside from that lgtm.

Comment (Guldoman) [reply src/video/wayland/SDL_waylandvideo.c:755]: Yeah that might be a useful safeguard.
I'd also have to add a check for `node->next = node->next->next;` tho.

Comment (flibitijibibo) [reply src/video/wayland/SDL_waylandvideo.c:755]: Yeah, probably going to have all the usual fun linked list boilerplate... wonder if that common linked list logic would be helpful at some point.
