### PR TITLE
Fix SDL_MAIN_USE_CALLBACKS with Android, introduce SDL_MAIN_EXPORTED

### LINKED ISSUE #11162: SDL_main not found on Android
I sync'd up recently to commit e31c68427a3aa29db6a8ab8ceb1cdd52d3d7edf5 and after rebuilding for Android hit a failure at startup of the apk that SDL_main was not found in libtestsprite.so.  The following patch fixed it for me:

```
diff --git a/include/SDL3/SDL_main.h b/include/SDL3/SDL_main.h
index 6160e5e36..de9c84739 100644
--- a/include/SDL3/SDL_main.h
+++ b/include/SDL3/SDL_main.h
@@ -567,8 +567,7 @@ extern SDL_DECLSPEC void SDLCALL SDL_GDKSuspendComplete(void);
      *  do *not* use SDL_main_impl.h (because SDL_main() is called from external Java code).
      *  If other platforms like that turn up, add them next to "defined(SDL_PLATFORM_ANDROID)"
      */
-    #if (defined(SDL_MAIN_USE_CALLBACKS) || defined(SDL_MAIN_NEEDED) || defined(SDL_MAIN_AVAILABLE)) && \
-        !defined(SDL_PLATFORM_ANDROID)
+       #if (defined(SDL_MAIN_USE_CALLBACKS) || defined(SDL_MAIN_NEEDED) || defined(SDL_MAIN_AVAILABLE))
 
         /* platforms which main (-equivalent) can be implemented in plain C */
         #include <SDL3/SDL_main_impl.h>
```

### PR DESCRIPTION
**Pull request by DanielGibson**
Fixing an oversight in #11126, and introducing a #define in SDL_main.h that communicates that
`main()` *should* be renamed to `SDL_main()` (and `SDL_main()` should be implemented by SDL in case of `SDL_MAIN_USE_CALLBACKS`), but no **native** main function must be implemented by SDL_main_impl.h because it's implemented somewhere outside the C/C++ codebase, for example in Java code. Currently that's only defined for Android.

## Description

SDL_MAIN_EXPORTED is defined for platforms where the real main() function is outside of the code that uses SDL, like Android where Java code is used that calls SDL_main().

My last simplification of the conditions for including SDL_main_impl.h had one problem: I forgot that SDL_main_impl.h must be included even on Android when SDL_MAIN_USE_CALLBACKS is used, because then a SDL_main() function that makes sure the callbacks get called is needed. 

Should be better now, and I think the whole handling of this weird case of not implementing
native main is a bit cleaner and easier to understand now.

## Existing Issue(s)

fixes #11162

### CODE REVIEW

File: include/SDL3/SDL_main.h [hunk 1]
```diff
@@ -89,6 +89,14 @@
         /* We need to export SDL_main so it can be launched from Java */
         #define SDLMAIN_DECLSPEC    SDL_DECLSPEC
 
+        /* As this is launched from Java, the "real" main it outside of the
+           the binary built from this code. This define makes sure that SDL_main.h
+           and SDL_main_impl.h don't try to provide a native main() function,
+           but if SDL_MAIN_USE_CALLBACKS is used, SDL_main_impl.h is still included
+           for the SDL_main() implementation that handles the callbacks.
+         */
+        #define SDL_MAIN_OUTSIDE_MAIN
```
Comment (slouken) [inline include/SDL3/SDL_main.h:98]: This is very confusing. Let's nuke it and re-add Android below. There will be few enough additional platforms that need this kind of thing that I think we can special case them.

Comment (DanielGibson) [reply include/SDL3/SDL_main.h:98]: on the contrary, we should keep it (though I'm open for a better name) and move the checks for what to do in that case into SDL_main_impl.h

because I just realized that in the SDL_MAIN_USE_CALLBACKS + Android case, currently a standard `int main(int argc, char* argv[])` **will** be generated in SDL_main_impl.h, because
https://github.com/libsdl-org/SDL/blob/b676413657875e1ba3af4eb038611db5deb13d9e/include/SDL3/SDL_main_impl.h#L55
defines `SDL_MAIN_CALLBACK_STANDARD` so after 
https://github.com/libsdl-org/SDL/blob/b676413657875e1ba3af4eb038611db5deb13d9e/include/SDL3/SDL_main_impl.h#L68
we'll run into
https://github.com/libsdl-org/SDL/blob/b676413657875e1ba3af4eb038611db5deb13d9e/include/SDL3/SDL_main_impl.h#L141-L149

So IMO it's best to explicitly define that behavior with its own name in SDL_main.h, and to implement it in SDL_main_impl.h, without having to hardcode the affected platforms in multiple places

(of course either way this needs more changes that I'm currently working on)

**Comment by DanielGibson** [comment]
Just pushed a commit that fixes an additional issue: with SDL_MAIN_USE_CALLBACKS enabled, SDL_main_impl.h would create a standard `int main(int argc, char* argv[])` function even on Android. Apparently that hasn't caused issues so far, but should probably be avoided

File: include/SDL3/SDL_main.h (hunk 1 above)
Comment (DanielGibson) [reply include/SDL3/SDL_main.h:98]: turned out it's still just one check for android-like platforms, but I still think that having a #define for that behavior in SDL_main.h is both cleaner and potentially useful for users to check than hardcoding SDL_PLATFORM_ANDROID

Comment (DanielGibson) [reply include/SDL3/SDL_main.h:98]: I improved the description to hopefully make it less confusing

File: include/SDL3/SDL_main.h [hunk 2]
```diff
@@ -89,6 +89,14 @@
         /* We need to export SDL_main so it can be launched from Java */
         #define SDLMAIN_DECLSPEC    SDL_DECLSPEC
 
+        /* As this is launched from Java, the real entry point (main() function)
+           is outside of the the binary built from this code.
+           This define makes sure that, unlike on other platforms, SDL_main.h
+           and SDL_main_impl.h only provide an `SDL_main()` function (to be called
+           from Java), but no native `int main(int argc, char* argv[])` or similar.
+         */
+        #define SDL_MAIN_OUTSIDE_MAIN
```
Comment (slouken) [inline include/SDL3/SDL_main.h:98]:
```suggestion
        #define SDL_MAIN_EXPORTED
```
What about this?

Comment (DanielGibson) [reply include/SDL3/SDL_main.h:98]: not sure..
or maybe something like SDL_MAIN_EXTERNAL or SDL_MAIN_IS_EXTERNAL?

Comment (DanielGibson) [reply include/SDL3/SDL_main.h:98]: OTOH, maybe I like EXPORTED better after all, EXTERNAL sounds too much like something that abstracts `extern "C"` or similar

Comment (DanielGibson) [reply include/SDL3/SDL_main.h:98]: what do you think about moving `#define SDLMAIN_DECLSPEC    SDL_DECLSPEC`
to the place where currently `#ifndef SDL_DECLSPEC #define SDL_DECLSPEC #endif` is, as
```c
#ifdef SDL_MAIN_EXPORTED
#define SDLMAIN_DECLSPEC  SDL_DECLSPEC
#else
#define SDLMAIN_DECLSPEC
#endif
```

**Comment by DanielGibson** [comment]
Tell me when this is ready to be merged, then I'll squash all the commits into one and combine the commit messages into a shorter coherent one

File: include/SDL3/SDL_main.h (hunk 2 above)
Comment (slouken) [reply include/SDL3/SDL_main.h]: I like it!

**Review by slouken — APPROVED** [review]
This looks really good now. Thanks for pushing through the awkward phase. :)

**Comment by DanielGibson** [comment]
Naming things remains one of the hardest problems in computer science =)

I'll do the squashing once I'm done playing with my cat

**Comment by DanielGibson** [comment]
Alright, it's all squashed into one commit now.

Thanks for reviewing this and suggesting a better name :)

**Comment by slouken** [comment]
You're welcome! Merged! :)
