### PR TITLE
x11: Ensure that parent windows for a dialog are from the X11 driver

### LINKED ISSUE #14273: SDL_ShowMessageBox fails with non-null parent in Wayland
The following example tries to create a window and then a child message box (i.e. a message box with that window as the `window` attribute in the `SDL_MessageBoxData` structure).
```cpp
#include <SDL3/SDL.h>

int main() {
	SDL_Init(SDL_INIT_VIDEO);

	SDL_Window* window;
	SDL_Renderer* renderer;

	SDL_CreateWindowAndRenderer("A window", 400, 400, 0, &window, &renderer);
	SDL_RenderClear(renderer);
	SDL_RenderPresent(renderer);

	SDL_Delay(1000);

	SDL_MessageBoxButtonData buttons[] = {
		{.flags = 0, .buttonID = 0, .text = "Close"},
	};

	SDL_MessageBoxData data = {
		.flags = 0,
		.window = window,
		.title = "A message box",
		.message = "This only works if window is nullptr.",
		.numbuttons = 1,
		.buttons = buttons,
		.colorScheme = nullptr,
	};

	int result = -1;
	SDL_ShowMessageBox(&data, &result);

	SDL_DestroyWindow(window);
	SDL_Quit();

	return 0;
}
```
However, this does not work on Wayland. I have built the program above with `g++ $(pkg-config --libs sdl3) main.cpp -fsanitize=address -o example`. Its behavior depends on the `SDL_VIDEODRIVER` environment variable:
* With `./example` (no environment variable), no message box appears and the address sanitizer complains about a SEGV somewhere inside `libSDL3.so`. The result of `SDL_GetCurrentVideoDriver` is `wayland`.
   * If the `window` field of `data` is replaced by `nullptr`, the message box appears (far from the window) and there is no SEGV.
   * If `-fsanitize=address` is not used, there is no visible complain for the SEGV, but the message box still does not appear.
* With `SDL_VIDEODRIVER=wayland ./example`, no message box appears, but there is apparently no SEGV. This is quite surprising, because `wayland` seems to be the default driver.
* With `SDL_VIDEODRIVER=x11 ./example`, the message box is shown and everything works as expected.

I am using SDL 3.2.24 on ArchLinux.

### PR DESCRIPTION
**Pull request by Kontrabant**
If the system doesn't have Zenity installed, message boxes can fall back to the X11 toolkit while the Wayland driver is in use, in which case, a Wayland window may be set as a parent to an X11 dialog. Ensure that the parent window for an X11 dialog is actually an X11 window.

Fixes #14273

### CODE REVIEW

File: src/video/x11/SDL_x11messagebox.c [hunk 1]
```diff
@@ -288,6 +288,8 @@ static void X11_OnMessageBoxScaleChange(SDL_ToolkitWindowX11 *window, void *data
 
 static bool X11_ShowMessageBoxImpl(const SDL_MessageBoxData *messageboxdata, int *buttonID)
 {
+    SDL_VideoDevice *viddev = SDL_GetVideoDevice();
```
Comment (slouken) [inline src/video/x11/SDL_x11messagebox.c]:
```suggestion
    SDL_VideoDevice *video = SDL_GetVideoDevice();
```

File: src/video/x11/SDL_x11messagebox.c [hunk 2]
```diff
@@ -305,10 +307,14 @@ static bool X11_ShowMessageBoxImpl(const SDL_MessageBoxData *messageboxdata, int
     }
 
     /* Create window */
+    if (messageboxdata->window && SDL_strcmp(viddev->name, "x11") == 0) {
```
Comment (slouken) [inline src/video/x11/SDL_x11messagebox.c]:
```suggestion
    if (messageboxdata->window && video && SDL_strcmp(video->name, "x11") == 0) {
```

File: src/video/x11/SDL_x11messagebox.c (hunk 1 above)
Comment (Kontrabant) [reply src/video/x11/SDL_x11messagebox.c]: Done…

File: src/video/x11/SDL_x11messagebox.c (hunk 2 above)
Comment (Kontrabant) [reply src/video/x11/SDL_x11messagebox.c]: and done.

**Comment by Kontrabant** [comment]
I'm hoping that @eafton finishes up #14023 as well. It would be a nice addition to the native Wayland driver, and would allow for similar functionality as the X11 toolkit with properly parented Wayland windows.

File: src/video/x11/SDL_x11messagebox.c (hunk 2 above)
Comment (sezero) [reply src/video/x11/SDL_x11messagebox.c]: Not done: video != NULL still not checked.

Comment (Kontrabant) [reply src/video/x11/SDL_x11messagebox.c]: If an SDL window is being passed as a parent, then a video driver had to have been initialized to create the window in the first place. Passing a non-null parent window without a video driver running is passing a garbage pointer, which is already broken. I added the check in a separate commit, but things are probably still going to eventually explode if an app is passing around random garbage window pointers with no video system initialized.
