### PR TITLE
Don't define SDL_ELF_NOTE_DLOPEN when compiler does not support variadic macro's

### LINKED ISSUE #14214: `SDL_ELF_NOTE_DLOPEN` cannot be used with a toolchain not supporting variadic macros
`SDL_ELF_NOTE_DLOPEN` of `SDL_dlopennote.h` is currently designed to be used unconditionally.

https://github.com/libsdl-org/SDL/blob/45d65f6e1f51422c414e85f133849648918a8c09/include/SDL3/SDL_dlopennote.h#L102-L109

However, it cannot be used with an (older) toolchain not supporting variadic macros.

Compiling `testdlopennote.c` of [this PR](https://github.com/libsdl-org/SDL/pull/14212) fails with the error below (when using MSVC 6):
```
testdlopennote.c(13) : error C2059: syntax error : 'string'
```
Defining `SDL_DISABLE_DLOPEN_NOTES` does not help since it is already defined (Windows is not a unix platform).

### PR DESCRIPTION
**Pull request by madebr**
I removed the cmake comment in the documentation since I feel CMake does not belong in the public headers.

Projects can make sure their toolchain supports `SDL_ELF_NOTE_DLOPEN` through this fragment:
```cmake
find_package(SDL3 REQUIRED COMPONENTS Headers)
set(CMAKE_REQUIRED_LIBRARIES SDL3::Headers)
check_c_source_compiles([==[
    #include <SDL3/SDL_dlopennote.h>
    SDL_ELF_NOTE_DLOPEN("sdl-video",
        "Support for video through SDL",
        SDL_ELF_NOTE_DLOPEN_PRIORITY_SUGGESTED,
        "libSDL-1.2.so.0", "libSDL-2.0.so.0", "libSDL3.so.0"
    );
    int main(int argc, char *argv[]) {
      return argc + argv[0][1];
    }
  ]==] COMPILER_SUPPORTS_SDL_ELF_NOTE_DLOPEN)
```

We document how to disable the macro. CMake/meson developers should know what do do with that.

Here's how to test without using the SDL3 headers:
```cmake

include(CheckCSourceCompiles)
check_c_source_compiles([==[
    #ifndef __ELF__
      ELF DL notes are only supported on ELF platforms
    #endif
    #define ARR1(N1) "[\"" N1 "\"]"
    #define ARR2(N1, N2) "[\"" N1 "\",\"" N2 "\"]"
    #define ARR_GET(N1,N2,NAME,...) NAME
    #define ARR(...) ARR_GET(__VA_ARGS__, ARR2, ARR1)(__VA_ARGS__)
    #define JOIN2(A,B) A##B
    #define JOIN(A,B) JOIN2(A,B)
    #define UNIQ JOIN(s_global, __LINE__)
    #define DLNOTE_INT2(JSON,VARNAME) \\
      __attribute__ ((used,aligned(4),section(".note.dlopen"))) static const struct { \\
        struct { int a; int b; } v; __attribute__((aligned(4))) char dlopen_json[sizeof(JSON)]; \\
      } VARNAME = { { 4, 0x407c0c0aU }, JSON }
    #define DLNOTE_INT(JSON,VARNAME) DLNOTE_INT2(JSON,VARNAME)
    #define DLNOTE(P,...) DLNOTE_INT("[" P "," ARR(__VA_ARGS__) "]", UNIQ)
    DLNOTE("required", "liba.so.0");
    DLNOTE("recommended", "libb.so.0", "libb.so.1");
    int main(int argc, char *argv[]) {
      return argc + argv[0][1];
    }
  ]==] COMPILER_SUPPORTS_ELFNOTES)
```

## Existing Issue(s)
Closes #14214

### CODE REVIEW

File: include/SDL3/SDL_dlopennote.h [hunk 1]
```diff
@@ -206,7 +188,7 @@
         "[{\"feature\":\"" feature                               \
         "\",\"description\":\"" description                      \
         "\",\"priority\":\"" priority                            \
-        "\",\"soname\":" SDL_SONAME_ARRAY(__VA_ARGS__) "}]",     \
+        "\",\"soname\":" SDL_ELF_JSON_ARRAY(__VA_ARGS__) "}]",   \
```
Comment (slouken) [inline include/SDL3/SDL_dlopennote.h]:
```suggestion
        "\",\"soname\":" SDL_DLNOTE_JSON_ARRAY(__VA_ARGS__) "}]",   \
```

**Comment by slouken** [comment]
> Projects can make sure their toolchain supports `SDL_ELF_NOTE_DLOPEN` through this fragment:

This needs to be documented somewhere...

**Comment by madebr** [comment]
> This needs to be documented somewhere...

I reinstated it, but the test is simply trying to use the SDL macro and sets the macro if the test failed.

**Comment by slouken** [comment]
> > This needs to be documented somewhere...
> 
> I reinstated it, but the test is simply trying to use the SDL macro and sets the macro if the test failed.

It doesn't have to be in the header, it can be in a README, it just needs to be referenced here. Feel free to put the real test in the README. Maybe we need README-dlnotes.md? :)

**Comment by sezero** [comment]
What is this waiting for?

**Comment by madebr** [comment]
> What is this waiting for?

A documentation change, but looking back at my changes in SDL_image/SDL_mixer, a small rewording of the doc string might be sufficient.

File: include/SDL3/SDL_dlopennote.h [hunk 2]
```diff
@@ -141,36 +143,37 @@
...
-#define SDL_ELF_NOTE_JOIN2(A,B) A##B
-#define SDL_ELF_NOTE_JOIN(A,B) SDL_ELF_NOTE_JOIN2(A,B)
-#define SDL_ELF_NOTE_UNIQUE_NAME SDL_ELF_NOTE_JOIN(s_SDL_dlopen_note_, __LINE__)
+#define SDL_DLNOTE_JOIN2(A,B) A##B
+#define SDL_DLNOTE_JOIN(A,B) SDL_DLNOTE_JOIN2(A,B)
+#define SDL_DLNOTE_UNIQUE_NAME SDL_DLNOTE_JOIN(s_SDL_dlopen_note_, __LINE__)
 
 /**
- * Note that your application has dynamic shared library dependencies.
+ * Add a not that your application has dynamic shared library dependencies.
```
Comment (sezero) [inline include/SDL3/SDL_dlopennote.h]: `a not` -> `a note`

Comment (madebr) [reply include/SDL3/SDL_dlopennote.h]: Oops! Thanks for the correction!

**Review by sezero — APPROVED** [review]
