### PR TITLE
io: rework how we set SDL_IOStream status.

### LINKED ISSUE #13720: Asyncio generc fails when the buffer is larger than file contents
When we perform reads with asyncio generic and provide a buffer larger than the file contents an assert and a failure occur.

Works fine with the liburing backend but I did not test it on windows.

I provided a pull request to fix the issue: https://github.com/libsdl-org/SDL/pull/13719

### PR DESCRIPTION
**Pull request by icculus**
This now relies on the implementation to set these flags on short reads/writes instead of the higher level checking if SDL_SetError() was called.

Additionally (and crucially), this now sets ERROR or EOF on all short reads, across all backends, not just when we get a zero-byte return value.

Fixes #13720.

### CODE REVIEW

File: include/SDL3/SDL_iostream.h [hunk 1]
```diff
@@ -111,7 +111,7 @@ typedef struct SDL_IOStreamInterface
 
     /**
      *  Read up to `size` bytes from the data stream to the area pointed
-     *  at by `ptr`.
+     *  at by `ptr`. `size` will always be > 0.
```
Comment (slouken) [inline include/SDL3/SDL_iostream.h:114]: will -> must?
