### PR TITLE
[Process API] Quoting enhancements

### LINKED ISSUE #12945: SDL_CreateProcess Windows argument escaping is imperfect
# The Problem

> Windows. Windows is the problem.
> -- [Issue 8129](https://github.com/libsdl-org/SDL/issues/8129)

The argument escaping is correct. Howevever, `cmd.exe` isn't (well, it's not broken, but it's complicated).
Windows does not have argc and argv. It has a lpCmdline where everything is passed as a string.
When you specify `/c` or `/k`, `cmd.exe` will use two modes to interpret the rest of lpCmdline:

1. if `/s` is specified, `cmd.exe` will find the first and last quote in lpCmdline and remove that. Your command is _everything_ in between.
2. If `/s` is not specified, `cmd.exe` will use the following rules (expand the following section):

<details>

Image

</details>

Note that this just generates the actual _batch command_ to run. The command still goes through the batch processor and that's where #10857 comes in.

The problem is SDL's current code quotes everything:
https://github.com/libsdl-org/SDL/blob/795d1ae1fb44f1321c4bb323a237d01c69a55579/src/process/windows/SDL_windowsprocess.c#L153

cmd.exe in particular does not like this, and it messes with their quote parsing thingy.

```c
#include <stdio.h>
#include <windows.h>

int main() {
    AttachConsole(ATTACH_PARENT_PROCESS );
    STARTUPINFO si;
    PROCESS_INFORMATION pi;

    ZeroMemory( &si, sizeof(si) );
    si.cb = sizeof(si);
    ZeroMemory( &pi, sizeof(pi) );

    // Start the child process. 
    if( !CreateProcess( NULL,   // No module name (use command line)
        "cmd.exe \"/c\" \"echo hello world\"",        // Command line
        NULL,           // Process handle not inheritable
        NULL,           // Thread handle not inheritable
        FALSE,          // Set handle inheritance to FALSE
        0,              // No creation flags
        NULL,           // Use parent's environment block
        NULL,           // Use parent's starting directory 
        &si,            // Pointer to STARTUPINFO structure
        &pi )           // Pointer to PROCESS_INFORMATION structure
    ) 
    {
        printf( "CreateProcess failed (%d).\n", GetLastError() );
        return 1;
    }

    // Wait until child process exits.
    WaitForSingleObject( pi.hProcess, INFINITE );

    DWORD exitCode =0;
    GetExitCodeProcess(pi.hProcess, &exitCode);
    printf("exit code %d\n", exitCode);

    // Close process and thread handles. 
    CloseHandle( pi.hProcess );
    CloseHandle( pi.hThread );
    return 0;
}
```
Produces this output:
```
# ./test | tee /dev/null
'"echo hello world' is not recognized as an internal or external command,
operable program or batch file.
exit code 1
```

# The Solution(?)

Do not quote arguments without whitespaces or special characters (``&()[]{}^=;!'+,`~``).
I am not sure what other work is needed here.
Another alternative is to let library users work around this by escaping the lpCmdline themselves, via a property.

# References

https://learn.microsoft.com/en-us/archive/blogs/twistylittlepassagesallalike/everyone-quotes-command-line-arguments-the-wrong-way
 
#10857 covers the section after "The correct solution", aptly named `cmd.exe`, while this issue is based on the "The correct solution" section.

### PR DESCRIPTION
**Pull request by takase1121**
This PR avoids quoting strings if it does not have newlines, as well as adding `SDL_PROP_PROCESS_CREATE_CMDLINE_STRING` as an alternative.

## Description

This issue was described in #12945.
This PR offers two solutions:

1. SDL will not quote strings unless it needs to (if it includes whitespaces).
2. `SDL_CreateProcessWithProperties` will accept another property called `SDL_PROP_PROCESS_CREATE_CMDLINE_STRING`, which lets library users pass an escaped command line to `CreateProcess` directly.
   This is useful for SDL wrappers that needed to allow users to call old executables that has their own command line escaping.

Take `cmd.exe /S /C` as example: `/S` will strip first and last double quotes from the command line, after `/C` itself.

| Method | Passed to `CreateProcess` | Passed to batch processing |
| ------ | ------------------------- | -------------------------- |
| SDL<br>`{"cmd.exe", "/s", "/c", "echo \"hello world\"", NULL}` | `cmd.exe /s /c "echo \"hello world\""`|  `echo \"hello world\"`|
| Raw string<br>`cmd.exe /s /c "echo "hello world""` |  `cmd.exe /s /c "echo "hello world""` |  `echo "hello world"` |

The code should not interfere with #10857.

## Existing Issue(s)

Fixes #12945.

### CODE REVIEW

File: src/process/windows/SDL_windowsprocess.c [hunk 1]
```diff
@@ -106,18 +106,21 @@ static bool join_arguments(const char * const *args, LPWSTR *args_out)
     len = 0;
     for (i = 0; args[i]; i++) {
         const char *a = args[i];
+        bool quotes = *a == '\0' || strpbrk(a, " \r\n\t\v") != NULL;
```
Comment (takase1121) [inline src/process/windows/SDL_windowsprocess.c:109]:
```suggestion
        bool quotes = *a == '\0' || SDL_strpbrk(a, " \r\n\t\v") != NULL;
```

File: src/process/windows/SDL_windowsprocess.c [hunk 2]
```diff
@@ -149,8 +152,11 @@ static bool join_arguments(const char * const *args, LPWSTR *args_out)
     i_out = 0;
     for (i = 0; args[i]; i++) {
         const char *a = args[i];
+        bool quotes = *a == '\0' || strpbrk(a, " \r\n\t\v") != NULL;
```
Comment (takase1121) [inline src/process/windows/SDL_windowsprocess.c:155]:
```suggestion
        bool quotes = *a == '\0' || SDL_strpbrk(a, " \r\n\t\v") != NULL;
```

File: include/SDL3/SDL_process.h [hunk 3]
```diff
@@ -195,6 +195,12 @@ typedef enum SDL_ProcessIO
  *   run in the background. In this case the default input and output is
  *   `SDL_PROCESS_STDIO_NULL` and the exitcode of the process is not
  *   available, and will always be 0.
+ * - `SDL_PROP_PROCESS_CREATE_CMDLINE_STRING`: a string containing the program
+ *   to run and any parameters. This string is passed directly to
+ *   `CreateProcess` on Windows, and does nothing on other platforms.
+ *   This property is only important if you want to start programs that does
+ *   non-standard command-line processing, and in most cases using
+ *   `SDL_PROP_PROCESS_CREATE_ARGS_POINTER` is sufficient.
```
Comment (madebr) [inline include/SDL3/SDL_process.h:203]: Having this option does not feel very safe to me?
What does it allow which the current behavior does not?

Comment (takase1121) [reply include/SDL3/SDL_process.h:203]: Unfortunately yes. This is an option that you shouldn't use unless you know what you're doing, **but** is needed because Windows have 3 main types of argument escaping (UCRT, CommandLineToArgvW, and cmd.exe) which are slightly different to each other and can cause issues. See my examples in the PR comment about cmd.exe /s /c, which is legitimately a good way to use cmd.exe and to avoid lots of escaping.

Other language runtimes have this features as well:

- node.js(windowsVerbatimArguments):https://nodejs.org/api/child_process.html#child_processexecfilefile-args-options-callback
- Python: https://github.com/python/cpython/blob/af5799f3056b0eee61fc09587633500a3690e67e/Lib/subprocess.py#L1461

Comment (takase1121) [reply include/SDL3/SDL_process.h:203]: Another way could be adding a callback to allow user to customize how the arguments are escaped - like join_cmdline. That'll probably scare away users that didn't have a solid justification for using this feature.

Comment (takase1121) [reply include/SDL3/SDL_process.h:203]: Just for context: command-line parsing is delegated to the callee application, often done as a part of libc startup code. Thus, it can't fail because of "syntax errors", so they're just propagated to the parsed argc and argv themselves.

cmd.exe inherited it's parsing from DOS, and MSVCRT and UCRT applications all have slightly different ways of parsing the command line. This means applications compiled on different compilers (e.g. MINGW64 and UCRT64) could use different schemes. The SDL escaping is good for UCRT and probably works for MSVCRT, but can fail for cmd.exe.

**Comment by takase1121** [comment]
Can I know the consensus for this? We (Lite XL) is considering to port our Process API to SDL process API to avoid all the POSIX/Win32 sphagetti.

**Comment by slouken** [comment]
This seems fine to me. It's unfortunate that quoting needs to be done differently for different command interpreters, but that makes sense.
