### PR TITLE
Fix CMake script on FreeBSD

### LINKED ISSUE #4133: CMake script is broken on FreeBSD
The CMake script is currently unusable on FreeBSD; it currently shows an syntax error likely related to the `sdlchecks.cmake` POSIX thread flag tests.

### PR DESCRIPTION
**Pull request by Cacodemon345**
This PR fixes CMake script on FreeBSD.

Fixes #4133.

### CODE REVIEW

File: src/stdlib/SDL_iconv.c [hunk 1]
```diff
@@ -31,6 +31,10 @@
 #include "SDL_endian.h"
 
 #if defined(HAVE_ICONV) && defined(HAVE_ICONV_H)
+#ifdef __FreeBSD__
+/* Define LIBICONV_PLUG to use iconv from the base instead of ports and avoid linker errors. */
```
Comment (sezero) [inline src/stdlib/SDL_iconv.c:35]: This part doesn't belong here - you already made a PR for that.

Comment (Cacodemon345) [reply src/stdlib/SDL_iconv.c]: Fixed.

**Comment by christianrauch** [comment]
It looks like this PR makes the build fail, at least on Linux:
```
CMake Error at cmake/sdlchecks.cmake:802 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  cmake/sdlchecks.cmake:809 (CheckEGL)
  CMakeLists.txt:1198 (CheckEGLKMSDRM)
```
Not sure why this didn't tricker the CI via this PR, but it does on this: https://github.com/libsdl-org/SDL/pull/4068

**Comment by flibitijibibo** [comment]
Can reproduce this error on my local setup as well.

**Comment by Cacodemon345** [comment]
The replace command has exactly 4 arguments so I am not so sure about that.

**Comment by Cacodemon345** [comment]
Anyway I got a fix in #4186. I will need to be more careful next time.
