### PR TITLE
opengl: Fixes for sRGB framebuffer support.

### LINKED ISSUE #13055: SDL2 and 3: wgl GLES 2.0 context by default created as srgb capable with no way to disable it
When initializing an OpenGL ES 2.0 context on windows via wgl, the context is created with srgb capability enabled by default, which my application doesn't support. The issue comes with the fact that by default the `WGL_FRAMEBUFFER_SRGB_CAPABLE_ARB` flag is "don't care" per the OpenGL spec, but sdl only explicitly set it if the value is nonzero
https://github.com/libsdl-org/SDL/blob/d16371b923fed57e5df676a84435baf1d1061a6a/src/video/windows/SDL_windowsopengl.c#L648-L651
so the application will receive an incompatible context.
Would always setting that value, even when 0 be an acceptable fix? And in case, should the same be done in the other opengl context creation functions?

### PR DESCRIPTION
**Pull request by icculus**
This changes the default for SDL_GL_FRAMEBUFFER_SRGB_CAPABLE to -1 (for "don't care"). Minor ABI break, but technically this never worked correctly.

Fixes #13055.

### CODE REVIEW

File: src/video/windows/SDL_windowsopengl.c [hunk 1]
```diff
@@ -651,9 +659,9 @@ static bool WIN_GL_SetupWindowInternal(SDL_VideoDevice *_this, SDL_Window *windo
         *iAttr++ = WGL_TYPE_RGBA_FLOAT_ARB;
     }
 
-    if (_this->gl_config.framebuffer_srgb_capable) {
+    if ((_this->gl_config.framebuffer_srgb_capable >= 0) && _this->gl_data->HAS_WGL_ARB_framebuffer_sRGB) {
```
Comment (slouken) [inline src/video/windows/SDL_windowsopengl.c:662]: I don't see this being initialized to -1?

Comment (icculus) [reply src/video/windows/SDL_windowsopengl.c:662]: Oh, yeah, that's probably important.  🤦‍♀️

Comment (slouken) [reply src/video/windows/SDL_windowsopengl.c:662]: :D

Comment (icculus) [reply src/video/windows/SDL_windowsopengl.c:662]: Resolved in 9d5c6daaefd7f6b3a32a706cb0e684a41812f7a7.

File: src/video/windows/SDL_windowsopengl.c [hunk 2]
```diff
@@ -556,7 +560,11 @@ static int WIN_GL_ChoosePixelFormatARB(SDL_VideoDevice *_this, int *iAttribs, fl
                                                     &matching);
 
             // Check whether we actually got an SRGB capable buffer
-            _this->gl_data->wglGetPixelFormatAttribivARB(hdc, pixel_format, 0, 1, &qAttrib, &srgb);
+            int srgb = 0;
```
Comment (slouken) [inline src/video/windows/SDL_windowsopengl.c:563]: Should this be -1?

Comment (icculus) [reply src/video/windows/SDL_windowsopengl.c:563]: We want to assume it's disabled if the extension is missing, right?

Comment (slouken) [reply src/video/windows/SDL_windowsopengl.c:563]: Mmm, sure.

Are you testing this on both NVIDIA and AMD? We should document in the header if there are any quirks there.

Comment (icculus) [reply src/video/windows/SDL_windowsopengl.c:563]: I don't have an AMD card, but this whole thing is 100% at the mercy of the GL drivers and we already know Nvidia doesn't cooperate. The best documentation would be to say "this is a request and it might not be fulfilled."

Comment (slouken) [reply src/video/windows/SDL_windowsopengl.c:563]: > The best documentation would be to say "this is a request and it might not be fulfilled."

Let's add that then?

Comment (icculus) [reply src/video/windows/SDL_windowsopengl.c:563]: Updated the header comment in b827166df0637e705e1148beb00fd8bdb9a1d93d.
