### PR TITLE
[SDL3] Fixed PS2 joystick analog sticks not enabled

### LINKED ISSUE #14813: [PS2] Analog Stick Not Working
We recently started porting [Chocolate Quake](https://github.com/Henrique194/chocolate-quake) to the PS2 platform and noticed that the analog sticks are not working. It appears that SDL never emits axis events when the analog sticks are moved. After discussing this with the PCSX2 developers, it seems this may be related to the absence of a `padSetMainMode` call, meaning the analog sticks are never properly enabled.

### PR DESCRIPTION
**Pull request by Henrique194**
## Description

SDL was not configuring the joystick in DualShock mode, which caused the analog sticks to never be enabled.

## Existing Issue(s)

Closes #14813

### CODE REVIEW

File: src/joystick/ps2/SDL_sysjoystick.c [hunk 1]
```diff
@@ -208,6 +266,8 @@ static bool PS2_JoystickOpen(SDL_Joystick *joystick, int device_index)
             return false;
         }
     }
+    PS2_InitializePad();
+
     joystick->nbuttons = PS2_BUTTONS;
     joystick->naxes = PS2_TOTAL_AXIS;
```
Comment (ccawley2011) [inline src/joystick/ps2/SDL_sysjoystick.c:274]: Is it possible to use the information determined by the new `PS2_InitializePad` function to provide more detailed values for these variables?

File: src/joystick/ps2/SDL_sysjoystick.c [hunk 2]
```diff
@@ -191,6 +191,64 @@ static SDL_JoystickID PS2_JoystickGetDeviceInstanceID(int device_index)
     return device_index + 1;
 }
 
+static void PS2_WaitPadReady(int port, int slot) {
```
Comment (slouken) [inline src/joystick/ps2/SDL_sysjoystick.c]:
```suggestion
static void PS2_WaitPadReady(int port, int slot)
{
```

File: src/joystick/ps2/SDL_sysjoystick.c [hunk 3]
```diff
@@ -191,6 +191,64 @@ static SDL_JoystickID PS2_JoystickGetDeviceInstanceID(int device_index)
...
+    int state;
+    do {
+        state = padGetState(port, slot);
```
Comment (slouken) [inline src/joystick/ps2/SDL_sysjoystick.c:199]: Should there be a delay in here if the state isn't ready? e.g. `SDL_Delay(1)`
Should there be an eventual timeout in case the pad is in a stuck state for some reason?

File: src/joystick/ps2/SDL_sysjoystick.c [hunk 4]
```diff
@@ -191,6 +191,64 @@ static SDL_JoystickID PS2_JoystickGetDeviceInstanceID(int device_index)
...
+    } while ((state != PAD_STATE_STABLE) && (state != PAD_STATE_FINDCTP1));
+}
+
+static void PS2_InitializePad(int port, int slot) {
```
Comment (slouken) [inline src/joystick/ps2/SDL_sysjoystick.c]:
```suggestion
static void PS2_InitializePad(int port, int slot)
{
```

File: src/joystick/ps2/SDL_sysjoystick.c (hunk 2 above)
Comment (Henrique194) [reply src/joystick/ps2/SDL_sysjoystick.c]: Fixed.

File: src/joystick/ps2/SDL_sysjoystick.c (hunk 4 above)
Comment (Henrique194) [reply src/joystick/ps2/SDL_sysjoystick.c]: Fixed.

File: src/joystick/ps2/SDL_sysjoystick.c [hunk 5]
```diff
@@ -191,6 +191,66 @@ static SDL_JoystickID PS2_JoystickGetDeviceInstanceID(int device_index)
...
+    do {
+        state = padGetState(port, slot);
+    } while ((state != PAD_STATE_STABLE) && (state != PAD_STATE_FINDCTP1));
+}
+
+static void PS2_InitializePad(int port, int slot)
+{
+    int modes;
+    int i;
+    int actuators;
```
Comment (sezero) [inline src/joystick/ps2/SDL_sysjoystick.c]: `actuators` isn't used and is resulting in the CI build failure.

Comment (Henrique194) [reply src/joystick/ps2/SDL_sysjoystick.c]: Fixed.

File: src/joystick/ps2/SDL_sysjoystick.c (hunk 1 above)
Comment (slouken) [reply src/joystick/ps2/SDL_sysjoystick.c:274]: @Henrique194, can you please respond here?

File: src/joystick/ps2/SDL_sysjoystick.c (hunk 3 above)
Comment (slouken) [reply src/joystick/ps2/SDL_sysjoystick.c:199]: @Henrique194, this needs to be addressed before this PR is merged.

Comment (Henrique194) [reply src/joystick/ps2/SDL_sysjoystick.c:199]: Fixed.

File: src/joystick/ps2/SDL_sysjoystick.c (hunk 1 above)
Comment (Henrique194) [reply src/joystick/ps2/SDL_sysjoystick.c:274]: @ccawley2011
That is actually my first time coding for the PS2, so I'm not very familiar with libpad, but I'll see what I can do.

File: src/joystick/ps2/SDL_sysjoystick.c [hunk 6]
```diff
@@ -191,6 +191,66 @@ static SDL_JoystickID PS2_JoystickGetDeviceInstanceID(int device_index)
...
 }
 
+static void PS2_WaitPadReady(int port, int slot)
+{
+    int state;
+    do {
+        SDL_Delay(1);
+        state = padGetState(port, slot);
+    } while ((state != PAD_STATE_STABLE) && (state != PAD_STATE_FINDCTP1));
+}
```
Comment (slouken) [inline src/joystick/ps2/SDL_sysjoystick.c:201]:
```suggestion
static void PS2_WaitPadReady(int port, int slot)
{
    int state = padGetState(port, slot);
    while ((state != PAD_STATE_STABLE) && (state != PAD_STATE_FINDCTP1)) {
        SDL_Delay(1);
        state = padGetState(port, slot);
    }
}
```

File: src/joystick/ps2/SDL_sysjoystick.c (hunk 1 above)
Comment (slouken) [reply src/joystick/ps2/SDL_sysjoystick.c:274]: This doesn't need to be done as part of this PR. I made a suggestion above so we don't always delay in PS2_WaitPadReady(), and if that looks good, I think this is good to merge.

File: src/joystick/ps2/SDL_sysjoystick.c (hunk 6 above)
Comment (Henrique194) [reply src/joystick/ps2/SDL_sysjoystick.c:201]: Fixed.

**Comment by slouken** [comment]
Merged, thanks!
