### PR TITLE
pen: Only create touch emulation device when a pen is present

### LINKED ISSUE #15330: SDL_GetTouchDeviceType delivers wrong type?
Hi!

It seems like on my laptop `SDL_GetTouchDeviceType` delivers a wrong type. It only has a touchpad, also the windows settings claim the same (so no touch capable screen).  ;)
The function returns `SDL_TOUCH_DEVICE_DIRECT` (with name `pen_input`) though.
Unless i'm mistaken this should not be the case, otherwise the documentation and source level comments are not really clear (plus i wouldn't know how to distinguish between pads and touch screens then).
(Windows 11 25H2, latest SDL3 release 3.4.4)

Thanks!

### PR DESCRIPTION
**Pull request by cgutman**
- [x] I confirm that I am the author of this code and release it to the SDL project under the Zlib license. This contribution does not contain code from other sources, including code generated by a Large Language Model ("AI").

## Description
The cause for the phantom `pen_input` touch device was [this code](https://github.com/libsdl-org/SDL/blob/e1e6cbe6ecf78da703829c62ff5335e7e9a16774/src/events/SDL_mouse.c#L195-L201) which creates the device by default during video init. This can confuse apps into thinking there's a real touchscreen present, so let's only create it when an actual pen device is present.

This change _might_ confuse apps that are expecting all touch devices to be present at startup, but the documentation for `SDL_GetTouchDevices()` warns against assuming that.

## Existing Issue(s)
Fixes #15330

### CODE REVIEW

File: src/events/SDL_mouse.c [hunk 1]
```diff
@@ -194,16 +194,9 @@ static void SDLCALL SDL_PenTouchEventsChanged(void *userdata, const char *name,
...
-        if (!mouse->added_pen_touch_device) {
-            SDL_AddTouch(SDL_PEN_TOUCHID, SDL_TOUCH_DEVICE_DIRECT, "pen_input");
-            mouse->added_pen_touch_device = true;
-        }
-    } else {
-        if (mouse->added_pen_touch_device) {
-            SDL_DelTouch(SDL_PEN_TOUCHID);
-            mouse->added_pen_touch_device = false;
-        }
+    if (!mouse->pen_touch_events && mouse->added_pen_touch_device) {
```
Comment (slouken) [inline src/events/SDL_mouse.c:197]: This doesn't seem right. If someone enables pen touch events after the first device has been added, we won't add it here. Should we?
