### PR TITLE
Fix Windows file dialog memory management

### LINKED ISSUE #11713: Random characters appearing in file dialog default file name field (Windows)
FAO @Semphriss 🎁🎄🎁

image

### PR DESCRIPTION
**Pull request by Semphriss**
## Description

This fixes the memory issue with multithreading in the Windows implementation of file dialogs.

I've also fixed a few more issues where I saw them. For example, the arguments passed to the thread functions weren't freed. I ran the program again with `--trackmem` and it said `Memory allocations: Total: 0.00 Kb in 0 allocations, 112 unknown frees`, hoping that's alright.

@AntTheAlchemist Can you confirm that this fixes the problem?

## Existing Issue(s)

Fixes #11713 (hopefully)

### CODE REVIEW

File: src/dialog/windows/SDL_windowsdialog.c [hunk 1]
```diff
@@ -34,29 +34,49 @@
 typedef struct
 {
     bool is_save;
-    const SDL_DialogFileFilter *filters;
-    int nfilters;
-    const char* default_file;
+    wchar_t *filters_str;
+    char* default_file;
```
Comment (slouken) [inline src/dialog/windows/SDL_windowsdialog.c:38]:
```suggestion
    char *default_file;
```
SDL style is to have `*` next to the variable name. Can you adjust the code below as well?

Comment (Semphriss) [reply src/dialog/windows/SDL_windowsdialog.c]: I've realized that I did that mistake not only in the commit but also in the previously written code. Thanks regexes for making my correcting job easy :^)

I've kept it in a separate commit to avoid putting too many changes in a single commit, but I can squash them if necessary.

**Comment by AntTheAlchemist** [comment]
Very quick test and I got a heap related crash after selecting a file. 

```
...Invalid address specified to RtlValidateHeap( 00430000, 092B5C08 )
A breakpoint instruction (__debugbreak() statement or a similar call) was executed...
```

I don't know what this means. I don't know what's caused it. Posting this here for now and I'm now going to dig deeper. Here's the call stack:

```
ntdll.dll!77d3b46a()
[Frames below may be incorrect and/or missing, no symbols loaded for ntdll.dll]
[External Code]
PixelEditor.exe!__acrt_unlock(__acrt_lock_id _Lock) Line 60
	at minkernel\crts\ucrt\src\appcrt\internal\locks.cpp(60)
[External Code]
PixelEditor.exe!_free_dbg(void * block, int block_use) Line 1031
	at minkernel\crts\ucrt\src\appcrt\heap\debug_heap.cpp(1031)
[External Code]
SDL3.dll!SDL_RunThread(SDL_Thread * thread) Line 328
	at C:\Users\User\Documents\POW\SDL\src\thread\SDL_thread.c(328)
SDL3.dll!RunThread(void * data) Line 46
	at C:\Users\User\Documents\POW\SDL\src\thread\windows\SDL_systhread.c(46)
SDL3.dll!RunThreadViaBeginThreadEx(void * data) Line 60
	at C:\Users\User\Documents\POW\SDL\src\thread\windows\SDL_systhread.c(60)
SDL3.dll!thread_start<unsigned int (__stdcall*)(void *),1>(void * const parameter) Line 97
	at minkernel\crts\ucrt\src\appcrt\startup\thread.cpp(97)
[External Code]
```

**Comment by AntTheAlchemist** [comment]
@Semphriss `SDL_free(args)` in `windows_file_dialog_thread()` crashes (@ `*statusloc = userfunc(userdata)` inside `SDL_RunThread()`). Is this because `args` is already freed with a call to `freeWinArgs(args)` at the end of `windows_ShowFileDialog()` ?

**Comment by Semphriss** [comment]
> @Semphriss `SDL_free(args)` in `windows_file_dialog_thread()` crashes (@ `*statusloc = userfunc(userdata)` inside `SDL_RunThread()`). Is this because `args` is already freed with a call to `freeWinArgs(args)` at the end of `windows_ShowFileDialog()` ?

That sounds correct. I have no idea why I didn't get a double-free bug on my machine. There's the same problem in the folder function, I'll fix them both.

**Comment by icculus** [comment]
Is this one good to go? Can I click "merge" on it?

**Comment by Semphriss** [comment]
It should be, if there's another bug I can fix it in a later PR.

@AntTheAlchemist Have you had a chance to test with the latest commit on this PR? Sorry to put that burden on you, I don't currently have access to my Windows and it appears my testing in Wine isn't the most reliable fallback.

**Comment by AntTheAlchemist** [comment]
Seems to work now, on the surface. @Semphriss didn't sound too confident - maybe it needs more testing.

**Comment by AntTheAlchemist** [comment]
@Semphriss Jinx! We both posted exactly the same time, lol.

No burden at all. I'm please to be able to help. I've tested using filters / no filters, userdata, and default path. If it was going to fail now, I guess I would have shown up. Let's merge.

**Comment by Semphriss** [comment]
It's difficult to be confident when I've made three relatively basic mistakes in a row :^)

I had plans to do a more robust automatic test suite for trays and dialogs before 3.2.0, but for now I'm focusing on fixing the emergencies.

**Comment by slouken** [comment]
> I had plans to do a more robust automatic test suite for trays and dialogs before 3.2.0

too late... :D

**Comment by RT2Code** [comment]
Thanks for the fix, it looks like it mostly works, but I'm sorry to report that the issue persists for folder dialog titles:
Screenshot (12)

**Comment by icculus** [comment]
Hey, @Semphriss, there doesn't seem to be a way to send a private message on GitHub, but I'm looking for your postal address for an SDL3-release celebration thing. Can you drop me an email at icculus@icculus.org so we can discuss? Thanks!

**Comment by Semphriss** [comment]
@icculus Sorry for the delay! I've just sent you an email from my committer email address.

**Comment by Semphriss** [comment]
Speaking of which, @slouken I'm slowly becoming available again, so it should be good to assign issues to me :) I'll also resume work on my other PRs.

**Comment by slouken** [comment]
> Speaking of which, @slouken I'm slowly becoming available again, so it should be good to assign issues to me :) I'll also resume work on my other PRs.

Welcome back! It's all quiet here. :)
