### PR TITLE
Rewrite/fix bugs in `SDL_strtol` and friends

### LINKED ISSUE #10750: Clarify expected behavior of `SDL_strtol` and friends
Extracted from discussion in https://github.com/libsdl-org/SDL/pull/10741#discussion_r1748088833.

SDL's implements and exposes a subset of the C standard library. Most often, when the corresponding libc function is available, SDL simply forwards the call to the libc function; however, when the libc function is unavailable, SDL provides its own custom implementation.

The problem is that SDL's homemade implementations do not always match the behavior of the corresponding libc function, and its unclear whether these differences are bugs or intended.

For example, the homemade implementation of `SDL_strtol` does not handle uppercase `0X` prefixed numbers, octal numbers or base 36 numbers in the same way as libc `strtol`:

1\. Comment out `#cmakedefine HAVE_STRTOL 1` in `SDL_build_config.h.cmake` to make the build process act as if `strtol` is missing from the libc, forcing SDL to use its homemade implementation.

2\. Build SDL using CMake.

3\. Compile and run the following program:
```c
#include <stdlib.h>
#include <stdio.h>
#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>

int main(int argc, char **argv) {
    long parsed;

    parsed = SDL_strtol("0X123", NULL, 0);
    printf("%ld\n", parsed);

    parsed = strtol("0X123", NULL, 0);
    printf("%ld\n", parsed);

    parsed = SDL_strtol("0123", NULL, 0);
    printf("%ld\n", parsed);

    parsed = strtol("0123", NULL, 0);
    printf("%ld\n", parsed);

    parsed = SDL_strtol("xyz", NULL, 36);
    printf("%ld\n", parsed);

    parsed = strtol("xyz", NULL, 36);
    printf("%ld\n", parsed);

    return 0;
}
```
4. It outputs
```
0
291
123
83
0
44027
```
demonstrating the difference in behavior between SDL and libc.

Now, the vast majority of all built SDL libraries floating around in the wild are likely to have been compiled against a libc that provide the functions, so this is probably not an huge in practice since the homemade SDL implementations are almost never used.

But the discrepancy does make it more difficult to document some of the APIs listed in `SDL_stdinc.h`, since it's not clear which differences in behavior are intentional and which are bugs, making it difficult for users to make assumptions about the expected behavior. Most importantly, if a difference is intentional, the documentation should clearly state what behavior the user should expect, and if it's a bug, it should probably be fixed.

### PR DESCRIPTION
**Pull request by castholm**
## Description

I believe this fixes all the unintended bugs in

- `SDL_strtol`,
- `SDL_strtoul`,
- `SDL_strtoll`,
- `SDL_strtoull`, and
- `SDL_wcstol`.

In addition, it also adds support for octals and other bases. See the test cases for examples. Covering every single edge case and combination of important parameters would be impractical but I believe this makes the implementations for these functions compliant with the libc specs ([strtol/strtoll](https://pubs.opengroup.org/onlinepubs/9799919799.2024edition/functions/strtol.html), [strtoul/strtoull](https://pubs.opengroup.org/onlinepubs/9799919799.2024edition/functions/strtoul.html), [wcstol](https://pubs.opengroup.org/onlinepubs/9799919799.2024edition/functions/wcstol.html)).

It also improves `SDL_strtod` slightly (use `unsigned long long` to parse the integer part; handle leading whitespace and positive signs).

I ran the tests with an SDL built with `-DSDL_LIBC=OFF`.

The core implementation itself is probably not as good as what you could get if you outright stole it from something like musl, but it works.

I don't actually program a lot in C so please let me know if anything I wrote looks off or unconventional. Note that I also added a compile-time assert that asserts that signed integers use two's complement. I'm not even sure if SDL would otherwise support one's complement or other crazy representations, but I felt this was necessary since `#include <limits.h>` isn't guaranteed to be available and obtaining numeric limits without it would be inconvenient otherwise. If you have any other suggestions I'd be eager to hear them out.

## Existing Issue(s)

Closes #10750

### CODE REVIEW

File: src/events/SDL_pen_c.h [hunk 1]
```diff
@@ -24,7 +24,6 @@
 #ifndef SDL_pen_c_h_
 #define SDL_pen_c_h_
 
-#include "../../include/SDL3/SDL_pen.h"
```
Comment (castholm) [inline src/events/SDL_pen_c.h:27]: I actually noticed this a few months ago, it's the only relative path inclusion that exits out of `src` and enters `include`. It caused some problems with a port of SDL to a different build system, so I hope you don't mind me sneaking this in.

File: test/testautomation_stdlib.c [hunk 2]
```diff
@@ -1228,6 +1228,123 @@ stdlib_strpbrk(void *arg)
     }
     return TEST_COMPLETED;
 }
+
+#undef SDL_wcstol
```
Comment (slouken) [inline test/testautomation_stdlib.c:1232]: Do you need this undef?

Comment (castholm) [reply test/testautomation_stdlib.c:1232]: I don't actually know, but some of the other tests in this file have `#undef SDL_strnlen` above them so I took the safe route and copied them.

File: src/stdlib/SDL_string.c [hunk 3]
```diff
@@ -374,42 +374,76 @@ static size_t SDL_ScanLong(const char *text, int count, int radix, long *valuep)
...
     bool negative = false;
 
-    if (*text == '-') {
-        negative = true;
+    if (radix != 0 && (radix < 2 || radix > 36)) {
+        return 0;
+    }
+
+    // don't use SDL_isspace here
+    // wchar_t could in theory be wider than int, which could make the conversion truncate bits
```
Comment (slouken) [inline src/stdlib/SDL_string.c:385]: I don't think that's true for any platform. It's probably worth compile-time asserting and using the SDL_is* functions here.

File: test/testautomation_stdlib.c (hunk 2 above)
Comment (slouken) [reply test/testautomation_stdlib.c:1232]: I think you can remove these entirely. This was from an older version of SDL that defined public symbols in terms of their C runtime counterparts.

File: include/SDL3/SDL_stdinc.h [hunk 4]
```diff
@@ -581,12 +581,14 @@ SDL_COMPILE_TIME_ASSERT(uint64_size, sizeof(Uint64) == 8);
 SDL_COMPILE_TIME_ASSERT(sint64_size, sizeof(Sint64) == 8);
 SDL_COMPILE_TIME_ASSERT(uint64_longlong, sizeof(Uint64) <= sizeof(unsigned long long));
 SDL_COMPILE_TIME_ASSERT(size_t_longlong, sizeof(size_t) <= sizeof(unsigned long long));
+SDL_COMPILE_TIME_ASSERT(wchar_t_int, sizeof(wchar_t) <= sizeof(int));
```
Comment (slouken) [inline include/SDL3/SDL_stdinc.h:584]: This should go in the implementation, where that constraint is needed.

**Comment by slouken** [comment]
This looks good in general. Feel free to make similar changes for the other numeric parsing functions.

Thanks!

**Comment by castholm** [comment]
> Feel free to make similar changes for the other numeric parsing functions.

Sure, I'm not sure I'll be able to get them all done immediately but I'll convert this to draft temporarily and do them all in one swoop as part of this PR.

**Review by slouken — APPROVED** [review]

**Comment by slouken** [comment]
Let me know when you're happy with this and I'll merge it. Thanks!

**Comment by castholm** [comment]
I think it's good to merge (provided the CI passes).

**Comment by castholm** [comment]
I'll take a look at the MinGW failures tomorrow, it's 2 am and I need to sleep. The problem appears to be that they handle the parsing of unsigned `-9999999999999999999999999999999999999999` differently from other libcs (the specs are not super clear on what is expected here). These tests are kinda redundant anyway unless we know for sure we're using our own impls of these functions, so maybe I'll put some `#ifdef HAVE_STRTOULL`s around the tests or fix them some other way.

**Comment by slouken** [comment]
> I'll take a look at the MinGW failures tomorrow, it's 2 am and I need to sleep. The problem appears to be that they handle the parsing of unsigned `-9999999999999999999999999999999999999999` differently from other libcs (the specs are not super clear on what is expected here). These tests are kinda redundant anyway unless we know for sure we're using our own impls of these functions, so maybe I'll put some `#ifdef HAVE_STRTOULL`s around the tests or fix them some other way.

Sounds good. If the behavior is undefined, we can omit the test.

File: test/testautomation_stdlib.c [hunk 5]
```diff
@@ -4,6 +4,7 @@
 #include <SDL3/SDL.h>
 #include <SDL3/SDL_test.h>
 #include "testautomation_suites.h"
+#include "SDL_build_config.h"
```
Comment (slouken) [inline test/testautomation_stdlib.c:7]: I would just drop these tests rather than conditionally test our implementation. We can just document the behavior as undefined, since it won't be consistent across platforms and C library implementations.

Comment (castholm) [reply test/testautomation_stdlib.c]: OK, I removed them.

**Comment by slouken** [comment]
This looks good to me. Let me know when you're comfortable with me merging!

**Comment by castholm** [comment]
I think I covered everything I wanted to, feel free to merge it.

**Comment by slouken** [comment]
Merged, thanks!

**Comment by sezero** [comment]
FYI:  I got this warning from gcc-4.9 when targeting i686:

```
/tmp/SDL3/test/testautomation_stdlib.c: In function 'stdlib_strtox':
/tmp/SDL3/test/testautomation_stdlib.c:1339:9: warning: this decimal constant is unsigned only in ISO C90
         STRTOX_TEST_CASE(SDL_strtoul, unsigned long, "%lu", "4294967295", 10, 4294967295, 10);
         ^
/tmp/SDL3/test/testautomation_stdlib.c:1340:9: warning: this decimal constant is unsigned only in ISO C90
         STRTOX_TEST_CASE(SDL_strtoul, unsigned long, "%lu", "4294967296", 10, 4294967295, 10);
         ^
```

**Comment by slouken** [comment]
Does this fix it?
```c
         STRTOX_TEST_CASE(SDL_strtoul, unsigned long, "%lu", "4294967295", 10, 4294967295u, 10);
         STRTOX_TEST_CASE(SDL_strtoul, unsigned long, "%lu", "4294967296", 10, 4294967295u, 10);
```

**Comment by sezero** [comment]
Another set of warnings are from my mingw toolchain about `%llu` use:
<details>

```
/tmp/SDL3/test/testautomation_stdlib.c: In function 'stdlib_strtox':
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1304:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "\t  123abcxyz", 0, 123, 6); // skip leading space
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1304:59: note: format string is defined here
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "\t  123abcxyz", 0, 123, 6); // skip leading space
                                                           ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1304:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "\t  123abcxyz", 0, 123, 6); // skip leading space
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1304:59: note: format string is defined here
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "\t  123abcxyz", 0, 123, 6); // skip leading space
                                                           ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: too many arguments for format [-Wformat-extra-args]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1304:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "\t  123abcxyz", 0, 123, 6); // skip leading space
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1305:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "+123abcxyz", 0, 123, 4);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1305:59: note: format string is defined here
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "+123abcxyz", 0, 123, 4);
                                                           ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1305:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "+123abcxyz", 0, 123, 4);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1305:59: note: format string is defined here
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "+123abcxyz", 0, 123, 4);
                                                           ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: too many arguments for format [-Wformat-extra-args]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1305:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "+123abcxyz", 0, 123, 4);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1306:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "+123abcxyz", 0, 123, 4);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1306:59: note: format string is defined here
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "+123abcxyz", 0, 123, 4);
                                                           ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1306:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "+123abcxyz", 0, 123, 4);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1306:59: note: format string is defined here
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "+123abcxyz", 0, 123, 4);
                                                           ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: too many arguments for format [-Wformat-extra-args]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1306:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "+123abcxyz", 0, 123, 4);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1307:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "-123abcxyz", 0, -123, 4);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1307:59: note: format string is defined here
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "-123abcxyz", 0, -123, 4);
                                                           ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1307:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "-123abcxyz", 0, -123, 4);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1307:59: note: format string is defined here
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "-123abcxyz", 0, -123, 4);
                                                           ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: too many arguments for format [-Wformat-extra-args]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1307:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "-123abcxyz", 0, -123, 4);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1308:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "9999999999999999999999999999999999999999abcxyz", 0, ullong_max, 40);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1308:59: note: format string is defined here
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "9999999999999999999999999999999999999999abcxyz", 0, ullong_max, 40);
                                                           ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1308:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "9999999999999999999999999999999999999999abcxyz", 0, ullong_max, 40);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1308:59: note: format string is defined here
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "9999999999999999999999999999999999999999abcxyz", 0, ullong_max, 40);
                                                           ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: too many arguments for format [-Wformat-extra-args]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1308:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "9999999999999999999999999999999999999999abcxyz", 0, ullong_max, 40);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1311:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "0x123abcxyz", 0, 0x123abc, 8);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1311:59: note: format string is defined here
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "0x123abcxyz", 0, 0x123abc, 8);
                                                           ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1311:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "0x123abcxyz", 0, 0x123abc, 8);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1311:59: note: format string is defined here
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "0x123abcxyz", 0, 0x123abc, 8);
                                                           ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: too many arguments for format [-Wformat-extra-args]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1311:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "0x123abcxyz", 0, 0x123abc, 8);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1312:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "0X123ABCXYZ", 0, 0x123abc, 8); // uppercase X
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1312:59: note: format string is defined here
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "0X123ABCXYZ", 0, 0x123abc, 8); // uppercase X
                                                           ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1312:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "0X123ABCXYZ", 0, 0x123abc, 8); // uppercase X
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1312:59: note: format string is defined here
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "0X123ABCXYZ", 0, 0x123abc, 8); // uppercase X
                                                           ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: too many arguments for format [-Wformat-extra-args]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1312:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "0X123ABCXYZ", 0, 0x123abc, 8); // uppercase X
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1315:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "0123abcxyz", 0, 0123, 4);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1315:59: note: format string is defined here
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "0123abcxyz", 0, 0123, 4);
                                                           ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1315:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "0123abcxyz", 0, 0123, 4);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1315:59: note: format string is defined here
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "0123abcxyz", 0, 0123, 4);
                                                           ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: too many arguments for format [-Wformat-extra-args]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1315:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "0123abcxyz", 0, 0123, 4);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1318:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "00110011", 2, 51, 8);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1318:59: note: format string is defined here
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "00110011", 2, 51, 8);
                                                           ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1318:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "00110011", 2, 51, 8);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1318:59: note: format string is defined here
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "00110011", 2, 51, 8);
                                                           ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: too many arguments for format [-Wformat-extra-args]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1318:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "00110011", 2, 51, 8);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1319:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "-uvwxyz", 32, -991, 3);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1319:59: note: format string is defined here
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "-uvwxyz", 32, -991, 3);
                                                           ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1319:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "-uvwxyz", 32, -991, 3);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1319:59: note: format string is defined here
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "-uvwxyz", 32, -991, 3);
                                                           ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: too many arguments for format [-Wformat-extra-args]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1319:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "-uvwxyz", 32, -991, 3);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1320:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "ZzZzZzZzZzZzZzZzZzZzZzZzZ", 36, ullong_max, 25);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1320:59: note: format string is defined here
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "ZzZzZzZzZzZzZzZzZzZzZzZzZ", 36, ullong_max, 25);
                                                           ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1320:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "ZzZzZzZzZzZzZzZzZzZzZzZzZ", 36, ullong_max, 25);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1320:59: note: format string is defined here
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "ZzZzZzZzZzZzZzZzZzZzZzZzZ", 36, ullong_max, 25);
                                                           ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: too many arguments for format [-Wformat-extra-args]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1320:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "ZzZzZzZzZzZzZzZzZzZzZzZzZ", 36, ullong_max, 25);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1322:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "-0", 10, 0, 2);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1322:59: note: format string is defined here
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "-0", 10, 0, 2);
                                                           ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1322:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "-0", 10, 0, 2);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1322:59: note: format string is defined here
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "-0", 10, 0, 2);
                                                           ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: too many arguments for format [-Wformat-extra-args]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1322:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "-0", 10, 0, 2);
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1323:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", " - 1", 0, 0, 0); // invalid input
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1323:59: note: format string is defined here
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", " - 1", 0, 0, 0); // invalid input
                                                           ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1323:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", " - 1", 0, 0, 0); // invalid input
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1323:59: note: format string is defined here
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", " - 1", 0, 0, 0); // invalid input
                                                           ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: too many arguments for format [-Wformat-extra-args]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1323:5: note: in expansion of macro 'STRTOX_TEST_CASE'
     STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", " - 1", 0, 0, 0); // invalid input
     ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1345:9: note: in expansion of macro 'STRTOX_TEST_CASE'
         STRTOX_TEST_CASE(SDL_strtoll, long long, "%lld", "9223372036854775807", 10, 9223372036854775807LL, 19);
         ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1345:53: note: format string is defined here
         STRTOX_TEST_CASE(SDL_strtoll, long long, "%lld", "9223372036854775807", 10, 9223372036854775807LL, 19);
                                                     ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1345:9: note: in expansion of macro 'STRTOX_TEST_CASE'
         STRTOX_TEST_CASE(SDL_strtoll, long long, "%lld", "9223372036854775807", 10, 9223372036854775807LL, 19);
         ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1345:53: note: format string is defined here
         STRTOX_TEST_CASE(SDL_strtoll, long long, "%lld", "9223372036854775807", 10, 9223372036854775807LL, 19);
                                                     ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: too many arguments for format [-Wformat-extra-args]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1345:9: note: in expansion of macro 'STRTOX_TEST_CASE'
         STRTOX_TEST_CASE(SDL_strtoll, long long, "%lld", "9223372036854775807", 10, 9223372036854775807LL, 19);
         ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1346:9: note: in expansion of macro 'STRTOX_TEST_CASE'
         STRTOX_TEST_CASE(SDL_strtoll, long long, "%lld", "9223372036854775808", 10, 9223372036854775807LL, 19);
         ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1346:53: note: format string is defined here
         STRTOX_TEST_CASE(SDL_strtoll, long long, "%lld", "9223372036854775808", 10, 9223372036854775807LL, 19);
                                                     ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1346:9: note: in expansion of macro 'STRTOX_TEST_CASE'
         STRTOX_TEST_CASE(SDL_strtoll, long long, "%lld", "9223372036854775808", 10, 9223372036854775807LL, 19);
         ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1346:53: note: format string is defined here
         STRTOX_TEST_CASE(SDL_strtoll, long long, "%lld", "9223372036854775808", 10, 9223372036854775807LL, 19);
                                                     ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: too many arguments for format [-Wformat-extra-args]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1346:9: note: in expansion of macro 'STRTOX_TEST_CASE'
         STRTOX_TEST_CASE(SDL_strtoll, long long, "%lld", "9223372036854775808", 10, 9223372036854775807LL, 19);
         ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1347:9: note: in expansion of macro 'STRTOX_TEST_CASE'
         STRTOX_TEST_CASE(SDL_strtoll, long long, "%lld", "-9223372036854775808", 10, -9223372036854775807LL - 1, 20);
         ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1347:53: note: format string is defined here
         STRTOX_TEST_CASE(SDL_strtoll, long long, "%lld", "-9223372036854775808", 10, -9223372036854775807LL - 1, 20);
                                                     ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1347:9: note: in expansion of macro 'STRTOX_TEST_CASE'
         STRTOX_TEST_CASE(SDL_strtoll, long long, "%lld", "-9223372036854775808", 10, -9223372036854775807LL - 1, 20);
         ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1347:53: note: format string is defined here
         STRTOX_TEST_CASE(SDL_strtoll, long long, "%lld", "-9223372036854775808", 10, -9223372036854775807LL - 1, 20);
                                                     ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: too many arguments for format [-Wformat-extra-args]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1347:9: note: in expansion of macro 'STRTOX_TEST_CASE'
         STRTOX_TEST_CASE(SDL_strtoll, long long, "%lld", "-9223372036854775808", 10, -9223372036854775807LL - 1, 20);
         ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1348:9: note: in expansion of macro 'STRTOX_TEST_CASE'
         STRTOX_TEST_CASE(SDL_strtoll, long long, "%lld", "-9223372036854775809", 10, -9223372036854775807LL - 1, 20);
         ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1348:53: note: format string is defined here
         STRTOX_TEST_CASE(SDL_strtoll, long long, "%lld", "-9223372036854775809", 10, -9223372036854775807LL - 1, 20);
                                                     ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1348:9: note: in expansion of macro 'STRTOX_TEST_CASE'
         STRTOX_TEST_CASE(SDL_strtoll, long long, "%lld", "-9223372036854775809", 10, -9223372036854775807LL - 1, 20);
         ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1348:53: note: format string is defined here
         STRTOX_TEST_CASE(SDL_strtoll, long long, "%lld", "-9223372036854775809", 10, -9223372036854775807LL - 1, 20);
                                                     ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: too many arguments for format [-Wformat-extra-args]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1348:9: note: in expansion of macro 'STRTOX_TEST_CASE'
         STRTOX_TEST_CASE(SDL_strtoll, long long, "%lld", "-9223372036854775809", 10, -9223372036854775807LL - 1, 20);
         ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1349:9: note: in expansion of macro 'STRTOX_TEST_CASE'
         STRTOX_TEST_CASE(SDL_strtoll, long long, "%lld", "-9999999999999999999999999999999999999999", 10, -9223372036854775807LL - 1, 41);
         ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1349:53: note: format string is defined here
         STRTOX_TEST_CASE(SDL_strtoll, long long, "%lld", "-9999999999999999999999999999999999999999", 10, -9223372036854775807LL - 1, 41);
                                                     ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1349:9: note: in expansion of macro 'STRTOX_TEST_CASE'
         STRTOX_TEST_CASE(SDL_strtoll, long long, "%lld", "-9999999999999999999999999999999999999999", 10, -9223372036854775807LL - 1, 41);
         ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1349:53: note: format string is defined here
         STRTOX_TEST_CASE(SDL_strtoll, long long, "%lld", "-9999999999999999999999999999999999999999", 10, -9223372036854775807LL - 1, 41);
                                                     ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: too many arguments for format [-Wformat-extra-args]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1349:9: note: in expansion of macro 'STRTOX_TEST_CASE'
         STRTOX_TEST_CASE(SDL_strtoll, long long, "%lld", "-9999999999999999999999999999999999999999", 10, -9223372036854775807LL - 1, 41);
         ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1351:9: note: in expansion of macro 'STRTOX_TEST_CASE'
         STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "18446744073709551615", 10, 18446744073709551615ULL, 20);
         ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1351:63: note: format string is defined here
         STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "18446744073709551615", 10, 18446744073709551615ULL, 20);
                                                               ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1351:9: note: in expansion of macro 'STRTOX_TEST_CASE'
         STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "18446744073709551615", 10, 18446744073709551615ULL, 20);
         ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1351:63: note: format string is defined here
         STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "18446744073709551615", 10, 18446744073709551615ULL, 20);
                                                               ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: too many arguments for format [-Wformat-extra-args]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1351:9: note: in expansion of macro 'STRTOX_TEST_CASE'
         STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "18446744073709551615", 10, 18446744073709551615ULL, 20);
         ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1352:9: note: in expansion of macro 'STRTOX_TEST_CASE'
         STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "18446744073709551616", 10, 18446744073709551615ULL, 20);
         ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1352:63: note: format string is defined here
         STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "18446744073709551616", 10, 18446744073709551615ULL, 20);
                                                               ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1352:9: note: in expansion of macro 'STRTOX_TEST_CASE'
         STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "18446744073709551616", 10, 18446744073709551615ULL, 20);
         ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1352:63: note: format string is defined here
         STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "18446744073709551616", 10, 18446744073709551615ULL, 20);
                                                               ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: too many arguments for format [-Wformat-extra-args]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1352:9: note: in expansion of macro 'STRTOX_TEST_CASE'
         STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "18446744073709551616", 10, 18446744073709551615ULL, 20);
         ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1353:9: note: in expansion of macro 'STRTOX_TEST_CASE'
         STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "-18446744073709551615", 10, 1, 21);
         ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1353:63: note: format string is defined here
         STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "-18446744073709551615", 10, 1, 21);
                                                               ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: unknown conversion type character 'l' in format [-Wformat=]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1353:9: note: in expansion of macro 'STRTOX_TEST_CASE'
         STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "-18446744073709551615", 10, 1, 21);
         ^~~~~~~~~~~~~~~~
/tmp/SDL3/test/testautomation_stdlib.c:1353:63: note: format string is defined here
         STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "-18446744073709551615", 10, 1, 21);
                                                               ^
/tmp/SDL3/test/testautomation_stdlib.c:1299:46: warning: too many arguments for format [-Wformat-extra-args]
         SDLTest_AssertCheck(r == expected_r, "Check result value, expected: " format_spec ", got: " format_spec, expected_r, r); \
                                              ^
/tmp/SDL3/test/testautomation_stdlib.c:1353:9: note: in expansion of macro 'STRTOX_TEST_CASE'
         STRTOX_TEST_CASE(SDL_strtoull, unsigned long long, "%llu", "-18446744073709551615", 10, 1, 21);
         ^~~~~~~~~~~~~~~~
```
</details>

One may think of using `SDL_PRIu64` etc. here, but since we are dealing specifically with `long long` and not a fixed 64 bit type, that may be wrong: i.e. `long long` may become 128 bit or something some day? (what is it with that Arm's `Cheri` thing, for e.g.?)

I.e. I don't have a non-ifdef'ed solution for this, and it's not a big thing either.

**Comment by sezero** [comment]
> Does this fix it?
> 
> ```c
>          STRTOX_TEST_CASE(SDL_strtoul, unsigned long, "%lu", "4294967295", 10, 4294967295u, 10);
>          STRTOX_TEST_CASE(SDL_strtoul, unsigned long, "%lu", "4294967296", 10, 4294967295u, 10);
> ```

Yes, it does.
