### PR TITLE
wayland: Call the Wayland hide/show functions directly when changing decoration modes

### LINKED ISSUE #6284: SDL completely broken on wayland SIGSEGV
not sure if to report this at libdecor or here, no SDL app works under wayland for me. below is a BT of running AMD's UMR. however this issue occurs in every SDL app, qemu and games included.

Arch Linux
Kernel 6.0 
sdl2-git 2.24.0.r291.g6b75a592a-1
sdl2_image-minimal-git release.2.6.0.r33.g71229fe-1
libdecor 0.1.0-3
EDIT: Add compositor
wlroots 0.15.1-6
wayfire-git 0.7.4.r214.gda7a929c-1

GDB BT
```
(gdb) run
Starting program: /usr/bin/umrgui
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffee2c16c0 (LWP 32604)]
[New Thread 0x7fffed9f36c0 (LWP 32605)]
[New Thread 0x7fffed1f26c0 (LWP 32607)]
[Thread 0x7fffed1f26c0 (LWP 32607) exited]
[New Thread 0x7fffed1f26c0 (LWP 32618)]
[Thread 0x7fffed1f26c0 (LWP 32618) exited]
[New Thread 0x7fffed1f26c0 (LWP 32628)]
[Thread 0x7fffed1f26c0 (LWP 32628) exited]
[New Thread 0x7fffed1f26c0 (LWP 32640)]
[Thread 0x7fffed1f26c0 (LWP 32640) exited]
[New Thread 0x7fffed1f26c0 (LWP 32652)]
[New Thread 0x7fffe65976c0 (LWP 32653)]
[New Thread 0x7fffe5d966c0 (LWP 32654)]
[New Thread 0x7fffe55956c0 (LWP 32655)]
[New Thread 0x7fffe4d946c0 (LWP 32656)]

Thread 1 "umrgui" received signal SIGSEGV, Segmentation fault.
0x00007fffeda53cf6 in libdecor_frame_set_visibility () from /usr/lib/libdecor-0.so.0
(gdb) bt
#0  0x00007fffeda53cf6 in libdecor_frame_set_visibility () at /usr/lib/libdecor-0.so.0
#1  0x00007ffff0d9c65b in  () at /usr/lib/libSDL2-2.0.so.0
#2  0x00007ffff0d4b557 in  () at /usr/lib/libSDL2-2.0.so.0
#3  0x00007ffff073a536 in  () at /usr/lib/libffi.so.8
#4  0x00007ffff0737037 in  () at /usr/lib/libffi.so.8
#5  0x00007fffedab6645 in  () at /usr/lib/libwayland-client.so.0
#6  0x00007fffedab6e03 in  () at /usr/lib/libwayland-client.so.0
#7  0x00007fffedab6ffc in wl_display_dispatch_queue_pending () at /usr/lib/libwayland-client.so.0
#8  0x00007fffedab9c60 in wl_display_roundtrip_queue () at /usr/lib/libwayland-client.so.0
#9  0x00007ffff0d4b557 in  () at /usr/lib/libSDL2-2.0.so.0
#10 0x00007ffff0d50626 in  () at /usr/lib/libSDL2-2.0.so.0
#11 0x00005555555a14a9 in  ()
#12 0x000055555558ad27 in main ()
(gdb)
```

### PR DESCRIPTION
**Pull request by Kontrabant**
Calling SDL_HideWindow() to destroy the window is a NOP if the SDL_WINDOW_SHOWN flag was never set. Bypass it and call the Wayland-specific function directly to ensure that the window is always destroyed before switching from server-side to client-side decorations, even if it hasn't been shown yet.

Likewise, call Wayland_ShowWindow() directly when the window isn't explicitly hidden to ensure that it is always recreated since the SDL_WINDOW_SHOWN flag won't be cleared, which, when set, renders SDL_ShowWindow() a NOP.

Fixes #6284

### CODE REVIEW

File: src/video/wayland/SDL_waylandwindow.c [hunk 1]
```diff
@@ -2088,7 +2093,7 @@ int Wayland_CreateWindow(_THIS, SDL_Window *window)
         (window->flags & (SDL_WINDOW_TOOLTIP | SDL_WINDOW_POPUP_MENU))
 #ifdef HAVE_LIBDECOR_H
     if (c->shell.libdecor && !IS_POPUP(window)) {
-        data->shell_surface_type = WAYLAND_SURFACE_LIBDECOR;
+        data->shell_surface_type = WAYLAND_SURFACE_XDG_TOPLEVEL;
```
Comment (slouken) [inline src/video/wayland/SDL_waylandwindow.c:2096]: Is this change right?

Comment (Kontrabant) [reply src/video/wayland/SDL_waylandwindow.c]: Fixed and pushed.

**Review by flibitijibibo — APPROVED** [review]

**Comment by sezero** [comment]
Should we apply this to release-2.24.x branch?

**Comment by slouken** [comment]
We shouldn't apply any Wayland fixes to the stable branch. Any changes need testing across a wide variety of environments.
