### PR TITLE
GPU: Fix Vulkan backend never checking deallocations

### LINKED ISSUE #12507: GPU renderer leaking memory every frame
win10.   SDL3.2.6 and 3.2.8

when renderer set to `gpu`, this leaks memory:

SDL_LockTexture( texture, nullptr, &pixels, &pitch );
{draw into the pixels[]}
SDL_UnlockTexture( texture );
SDL_RenderTexture( renderer, texture, &dest, &dest );
SDL_RenderPresent( renderer );

when renderer defaults to  `direct3d11`  the above works perfectly (as expected).

issue:  the above code should gracefully no-op or work or not leak piles of memory every frame.

I realize someone is likely going to say something like:  "you aren't supposed to do the above stuff with `gpu`"
, if that's the case, my bad, but still feel like it shouldn't be leaking huge amounts of memory.

### PR DESCRIPTION
**Pull request by thatcosmonaut**
Since we restructured presentation, in the typical path Wait is called before acquiring a swapchain texture to prevent the GPU from getting too far ahead. Wait triggers command buffer cleanup. However, originally the backend assumed that command buffers were always cleaned up inside of Submit, and if a command buffer was cleaned this triggered the deallocation check. In light workloads command buffers tend to be cleaned up inside of Wait. This meant that the deallocation was never triggered.

The fix is to set a flag on VulkanRenderer that is triggered when a memory region is freed and the allocation has 0 remaining used regions. If this flag is set to 1, we check for empty allocations and deallocate them in Submit. 

Resolves #12507

### CODE REVIEW

File: src/gpu/vulkan/SDL_gpu_vulkan.c [hunk 1]
```diff
@@ -1546,8 +1547,14 @@ static void VULKAN_INTERNAL_RemoveMemoryUsedRegion(
         usedRegion->offset,
         usedRegion->size);
 
+    if (usedRegion->allocation->usedRegionCount == 0)
+    {
+        renderer->checkEmptyAllocations = 1;
```
Comment (slouken) [inline src/gpu/vulkan/SDL_gpu_vulkan.c:1552]:
```suggestion
        renderer->checkEmptyAllocations = true;
```

File: src/gpu/vulkan/SDL_gpu_vulkan.c [hunk 2]
```diff
@@ -10512,6 +10516,8 @@ static bool VULKAN_Submit(
             }
         }
 
+        renderer->checkEmptyAllocations = 0;
```
Comment (slouken) [inline src/gpu/vulkan/SDL_gpu_vulkan.c:10519]:
```suggestion
        renderer->checkEmptyAllocations = false;
```

File: src/gpu/vulkan/SDL_gpu_vulkan.c [hunk 3]
```diff
@@ -1546,8 +1547,14 @@ static void VULKAN_INTERNAL_RemoveMemoryUsedRegion(
...
         usedRegion->size);
 
+    if (usedRegion->allocation->usedRegionCount == 0)
+    {
+        renderer->checkEmptyAllocations = 1;
+    }
+
     SDL_free(usedRegion);
 
+
```
Comment (slouken) [inline src/gpu/vulkan/SDL_gpu_vulkan.c:1557]:
```suggestion
```

File: src/gpu/vulkan/SDL_gpu_vulkan.c [hunk 4]
```diff
@@ -1546,6 +1547,11 @@ static void VULKAN_INTERNAL_RemoveMemoryUsedRegion(
         usedRegion->offset,
         usedRegion->size);
 
+    if (usedRegion->allocation->usedRegionCount == 0)
```
Comment (TheSpydog) [inline src/gpu/vulkan/SDL_gpu_vulkan.c:1550]: `{` should be on the same line

**Review by TheSpydog — COMMENTED** [review]
Looks good to me! Just one style thing aside from what Sam caught.

**Review by slouken — APPROVED** [review]
