### PR TITLE
wayland client-side decorations

### LINKED ISSUE #3739: wayland client-side decorations
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* ~~[set of patches for window decorations (sdl_decoration_patches.tar.xz, application/x-xz, 2020-06-15 22:33:47 +0000, 7332 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4384)~~
* [testscale with decorations (sdl_decoration_scale.png, image/png, 2020-06-15 22:35:42 +0000, 166638 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4385)
* [testsprite2 with decorations (sdl_decoration_sprite2.png, image/png, 2020-06-15 22:36:22 +0000, 34977 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4386)
* ~~[set of patches for window decorations (ver 2) (sdl_decoration_patches.tar.xz, text/plain, 2021-01-26 22:00:39 +0000, 7224 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4708)~~
* ~~[libdecoration Draft (libdecoration_dynamic_wip.diff, text/plain, 2021-01-30 07:24:42 +0000, 19723 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4736)~~
* [libdecoration API fixes (0001-API-Avoid-stdbool-do-not-include-wayland-client.h.patch, text/plain, 2021-02-03 22:57:40 +0000, 3948 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4756)
* [Whitespace fix (wlwhitespace.diff, text/plain, 2021-02-05 00:12:34 +0000, 796 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4762)
* [libdecoration Support (libdecoration.diff, text/plain, 2021-02-05 21:01:47 +0000, 27458 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4765)

**Reported in version:** 2.0.15
**Reported for operating system, platform:** Linux, All

# Comments on the original bug report:

On 2020-06-15 22:33:47 +0000, Christian Rauch wrote:

> Created attachment 4384
> set of patches for window decorations
> 
> The attached set of patches implement client-side window decorations on Wayland using 'libdecoration' from https://gitlab.gnome.org/jadahl/libdecoration.
> 
> All patches are compressed into a single archive as I am unable to add multiple attachments. You can follow the upstream work at https://github.com/christianrauch/SDL/tree/decoration.
> 
> One patch additionally enables AddressSanitizer for debug builds (remove if you don't want this) and wl_proxy tag support to distinguish between owners of a wl_surface in callbacks. The libdecoration dependency is downloaded directly from upstream at build-time.
> 
> This fixes https://bugzilla.libsdl.org/show_bug.cgi?id=2710
> 
> Cheers and thanks for making Linux gaming happen :-)

On 2020-06-15 22:35:42 +0000, Christian Rauch wrote:

> Created attachment 4385
> testscale with decorations

On 2020-06-15 22:36:22 +0000, Christian Rauch wrote:

> Created attachment 4386
> testsprite2 with decorations

On 2020-09-11 11:49:48 +0000, Lothar Serra Mari wrote:

> Thanks a lot for this patch!
> 
> In my opinion, this is clearly a step in the right direction, since it seems unlikely that the GNOME developers will ever change their mind.
> 
> This provides a clean solution for all SDL2 applications, so I'd really appreciate to see this merged on day.
> 
> I gave this a try on my own - looking good so far! (Tested with the current master branch of ScummVM which is an SDL2 application).

On 2020-10-29 16:58:08 +0000, David Heidelberg (okias) wrote:

> Do I understand right, this could make move ahead in case of:
> 
> Allowing apps run under Wayland backend ([patch] Wayland: SDL applications start in XWayland by default) [1]
> and would close [2]?
> 
> Thank you guys!
> 
> [1] https://bugzilla.libsdl.org/show_bug.cgi?id=3948
> [2] https://bugzilla.libsdl.org/show_bug.cgi?id=4845

On 2020-10-31 14:22:31 +0000, Christian Rauch wrote:

> This would indeed implement the decorations and close bug 4845.
> 
> It will also bring SDL closer to full Wayland support, but if this will be enabled by default (bug 3948) is up to the developers. So far, I have not received any feedback from developers on the integration of client-side decorations, so I am not sure if there is even interest in fully supporting Wayland.

On 2020-11-18 15:46:40 +0000, Ryan C. Gordon wrote:

> *** Bug 4845 has been marked as a duplicate of this bug. ***

On 2020-11-18 15:48:54 +0000, Ryan C. Gordon wrote:

> (In reply to Christian Rauch from comment # 5)
> > decorations, so I am not sure if there is even interest in fully supporting
> > Wayland.
> 
> I haven't looked at these patches yet--and won't until after 2.0.14 ships--but I am _definitely_ interested in this. It seems to me that libdecoration is the only reasonable way forward here for client-side decorations in SDL.
> 
> --ryan.

On 2021-01-23 20:16:36 +0000, Ethan Lee wrote:

> Some feedback having looked at the Wayland driver recently...
> 
> For SDL, there are two functions in particular that are available in the X11 driver that libdecoration might care about: GetWindowBordersSize and SetWindowResizable. SetWindowResizable was thankfully easy to implement since all we have to do is ignore/react based on what our window flags are, but looking at the callbacks I wasn't sure if libdecoration was able to tell the difference between a fixed-size and resizable window, since all that work is handled in a callback rather than a readable/writeable attribute like in X11:
> 
> https://hg.libsdl.org/SDL/file/a3d4219798f6/src/video/x11/SDL_x11window.c#l1072
> 
> GetWindowBordersSize is less important to me but is worth noting for full X11 parity - is there a way for us to get the size of the window borders generated by libdecoration?
> 
> Aside from that I didn't notice anything major; the current patchset will have to be rewritten to replace ifdef-y stuff with dynamic loading of libdecoration (falling back when unavailable) but that's purely on the SDL side of things.

On 2021-01-23 21:26:59 +0000, Christian Rauch wrote:

> Note that the most recent version will be available at https://github.com/christianrauch/SDL/tree/decoration as I will frequently rebase on SDL master and also adapt the implementation to libdecoration changes. I will create a new patch set once the changes look good to you. (I don't want to spam you with new patch sets every time I rebase or update the implementation.)
> 
> (In reply to Ethan Lee from comment # 8)
> > I wasn't sure if libdecoration was able to tell the difference between
> > a fixed-size and resizable window
> libdecoration has "capabilities": https://gitlab.gnome.org/jadahl/libdecoration/-/blob/6150ef8f/src/libdecoration.h#L135-137 to set/unset MOVE/RESIZE/MINIMIZE actions. All this has to be handle client-side, so libdecoration will just ignore these requests. There is no protocol yet to prevent this server-side.
> 
> > GetWindowBordersSize is less important to me but is worth noting for full
> > X11 parity - is there a way for us to get the size of the window borders
> > generated by libdecoration?
> This information is definitely available internally, but it is not fully exposed to clients so far. The window size is stored in "libdecor_configuration", which is private, and the content size can be obtained via the public "libdecor_configuration_get_content_size".
> 
> I am sure we can add API for getting the decoration border size if there is demand.
> 
> 
> > The current patchset will have to be rewritten to replace ifdef-y stuff with
> > dynamic loading of libdecoration (falling back when unavailable) but that's 
> > purely on the SDL side of things.
> Is this something you could help me with?

On 2021-01-23 21:32:17 +0000, Ethan Lee wrote:

> I can definitely help with the dynamic loading part, sure. The hard part will be adding it to configure.ac, while the rest is just adding it to the gelatinous blob of shell "stuff" we have already.
> 
> I may be wrong on this but I believe GetWindowBordersSize was among the additions to SDL that was specifically for GUI implementation support, with the primary consumer being Unreal Engine 4 - so while it's not used in a lot of different engines it is _definitely_ popular if only because it's used in the most popular AAA-scale engine on the market.

On 2021-01-23 21:39:24 +0000, Ethan Lee wrote:

> Just grepped the UE4 source code and can confirm it is used in both the editor as well as the end-user runtime, so GetWindowBordersSize is definitely actively used.
> 
> I also found the symbol in the Unity binary but couldn't confirm if it was in use, though I suspect the Unity Editor at minimum uses it for roughly the same purpose since they have since moved to SDL for Linux support.

On 2021-01-26 04:28:27 +0000, Sam Lantinga wrote:

> Can you make libdecoration optional, dynamically loading and using it when available, like some of the other SDL dependencies?

On 2021-01-26 04:30:49 +0000, Ethan Lee wrote:

> I believe that's the plan - Christian: Can you rebase your existing patchset against default? I may need some help with the autoconf side of things but I can try to work on the dynamic loading this week.

On 2021-01-26 22:00:39 +0000, Christian Rauch wrote:

> Created attachment 4708
> set of patches for window decorations (ver 2)
> 
> patch set for client-side decorations

On 2021-01-26 22:04:28 +0000, Christian Rauch wrote:

> (In reply to Ethan Lee from comment # 13)
> > Can you rebase your existing patchset against default?
> 
> I rebased on master and uploaded a new (ver 2) patch set.

On 2021-01-27 19:49:22 +0000, Sam Lantinga wrote:

> In case anyone has trouble with it, the attachment "set of patches for window decorations (ver 2)" is tar.xz format.

On 2021-01-27 20:23:13 +0000, Christian Rauch wrote:

> (In reply to Sam Lantinga from comment # 16)
> > In case anyone has trouble with it, the attachment "set of patches for
> > window decorations (ver 2)" is tar.xz format.
> 
> The patch-set contains multiple commits that I compressed into a single archive. Let me know if you need the patches in a different format.
> 
> Also feel free to merge the patches that are unrelated to the decorations (AddressSanitizer, memory fixes, ...).

On 2021-01-29 13:53:08 +0000, Ellie wrote:

> Would it be possible to integrate this such that libdecoration is found via dlopen() and picked up from the Linux system it is on, while otherwise not requiring it via full dynamic link to be present?
> 
> My apologies if it's already handled like that, I'm asking because this would make statically building SDL2 easier: it wouldn't require baking libdecoration too, and instead a static portable SDL2 app could then just pick it up & use it if present and otherwise still work on KDE, non-Wayland GNOME, Phosh, and others as expected.
> 
> If that's too much work that's fine, I just thought it wouldn't hurt to suggest this approach.

On 2021-01-29 15:28:18 +0000, Ethan Lee wrote:

> dlopen is the only way we'd ever do it!
> 
> I'll try to take a look at this today.

On 2021-01-30 07:24:42 +0000, Ethan Lee wrote:

> Created attachment 4736
> libdecoration Draft
> 
> Attached is a diff that reworks patches 2 and 4 into something that would be more likely to land in upstream. I ignored patch 1, skipped 4 because the build system is a whole other issue, and skipped 3 because that should probably be sent in as its own patch separately from this issue.
> 
> In this diff I added a ton of 'FIXME libdecoration' blocks for someone else to assess - some of it is on the side of libdecoration while others are mostly dealing with the integration of libdecoration.h, which was surprisingly difficult to figure out without adding HAVE_LIBDECORATION_H all over the place (my guess is, we'll be adding HAVE_LIBDECORATION_H all over the place). It's possible that we'll have to do the dynamic loading of libdecoration separately from SDL_waylanddyn.h/SDL_waylandsym.h, which would suck but may be necessary since everything else is always available to us.
> 
> Hopefully this is enough for someone to go on for getting this wrapped up!

On 2021-01-30 15:14:25 +0000, Christian Rauch wrote:

> (In reply to Ethan Lee from comment # 20)
> > Created attachment 4736 [details]
> > libdecoration Draft
> > 
> > Attached is a diff that reworks patches 2 and 4 into something that would be
> > more likely to land in upstream. I ignored patch 1, skipped 4 because the
> > build system is a whole other issue, and skipped 3 because that should
> > probably be sent in as its own patch separately from this issue.
> 
> Thanks!
> 
> I am unable to apply the patches on top of my branch / patch-set (neither via git nor via hg). This is probably because I am not very familiar with this system. I am using web interfaces like GitLab, Bitbucket or GitHub mostly.
> 
> Can you give me a hint in which order I have to apply the patches onto the current tip/master/default?

On 2021-01-30 16:36:44 +0000, Ethan Lee wrote:

> Made a git mirror, should be easier to work with:
> 
> https://github.com/flibitijibibo/SDL-mirror/commit/7e7a961a927ce283584cd3fbf0c90c037921aa48

On 2021-01-30 20:44:54 +0000, Sam Lantinga wrote:

> This looks pretty good.
> 
> Do you need to set data->shell.libdecoration = NULL after this call?
> libdecor_unref(data->shell.libdecoration)

On 2021-01-30 20:45:20 +0000, Sam Lantinga wrote:

> Also, have you done testing with and without libdecoration being available?

On 2021-01-30 21:45:03 +0000, Ethan Lee wrote:

> >Do you need to set data->shell.libdecoration = NULL after this call?
> libdecor_unref(data->shell.libdecoration)
> 
> Yeah, we should - branch updated.
> 
> >Also, have you done testing with and without libdecoration being available?
> 
> I've actually been working on this cleanup without even having the libdecoration source on my PC... I've been doing build tests by forward declaring what we use wherever I could (no spot was very good, which is probably the only big issue on the source side of things, maybe the build system changes will fix that). For the most part this patchset just corrects the ifdef goo so that the new backend doesn't delete the existing functionality.

On 2021-01-30 22:12:26 +0000, Ellie wrote:

> I am wondering now, are there any plans to convince distributions to preinstall libdecoration as a sort of wayland core component with any wayland desktop? Because otherwise it might be actually interesting to possibly statically link it, although it seems more reasonable to me to treat it as external infrastructure component by the distro. But e.g. on Fedora 33 where I have GNOME installed there is no libdecoration to be found, even though I run GNOME Wayland - so pretty much *the* environment where it really would be necessary. Just throwing it in here in case that gives some useful ideas about whether dlopen() will be the only possible path or if it should be, and/or if some distributors might need to be poked once this is in.

On 2021-01-31 00:24:03 +0000, Christian Rauch wrote:

> (In reply to Ellie from comment # 26)
> > I am wondering now, are there any plans to convince distributions to
> > preinstall libdecoration as a sort of wayland core component with any
> > wayland desktop? Because otherwise it might be actually interesting to
> > possibly statically link it, although it seems more reasonable to me to
> > treat it as external infrastructure component by the distro.
> 
> Yes, in the long term libdecoration should be packaged for distributions as probably many more projects will want to use a library to implement decorations on wayland. Until libdecoration in widely available, I guess projects have to provide their own copy of shared objects or just link statically. The plugins that actually draw the decorations are dynamically loaded, with the idea that this could be done dependant on the desktop environment.
> 
> Saying that, it would be useful to decide this now. I used #ifdefs all over the wayland backend assuming that the decorations are enabled/disabled at compile-time. If it is only used via dlopen, I assume that there should be no "#ifdef DECORATION" left and everything should be forward declared?
> 
> @Ethan Lee
> I rebased your patch on top of my decoration branch:
> https://github.com/christianrauch/SDL/tree/decoration
> It does not compile, as you said, and it will take me a while to figure out how to transform the remaining code to the dlopen behaviour. If you want to continue on this, you can maybe just fork from there and send a PR to my repo, I will then upload the patches here once things work as expected.

On 2021-01-31 00:44:35 +0000, Ellie wrote:

> I would prefer if distributions shipped it, I am just wondering if anyone has asked any if they plan to. Because it would need to be preinstalled with desktop environments and I imagine it might be harder to convince distributions this is the case. (No user will know this needs to be manually installed, and if it's just pulled in via deps of specific programs that use it then e.g. AppImage-based programs from the web will be severely handicapped.)
> 
> Now if distros DONT play along with this, the use is dlopen() only could be a bit problematic since dlopen() would prevent easy fully static link into the program, wouldn't it? So programs meant to be shipped without additional files (e.g. think of an installer using SDL2) would then be left out. The projects I am working on tend to be of this kind, this is why I brought it up.

On 2021-01-31 01:19:02 +0000, Ethan Lee wrote:

> >If you want to continue on this, you can maybe just fork from there and send a PR to my repo, I will then upload the patches here once things work as expected.
> 
> I can test patches as they roll in, but I won't be able to do much from here on out other than review minor style things. Hopefully the dlopen changes got a bunch of busy work out of the way though!

On 2021-02-01 16:18:17 +0000, Cameron Gutman wrote:

> I'm glad this is getting closer to fruition.
> 
> I left some review comments on your latest commit: https://github.com/christianrauch/SDL/commit/cdd9ce0ab61119a33428e39fb8f958e2ed66f9b2

On 2021-02-03 00:13:56 +0000, Christian Rauch wrote:

> I got the dlopen-ing working. I created a new branch for the time being:
> https://github.com/christianrauch/SDL/tree/decoration_dlopen
> 
> The symbols are now resolved at runtime. If the "libdecoration.so" cannot be found it will fall back to the previous xdg surfaces without decorations.
> 
> I did not fix any of the FIXME since I wanted to get the basic dlopen function running first.
> 
> Two issues are left:
> 1) I had to set the library name "libdecoration.so" manually in "sdlchecks.cmake". "FindLibraryAndSONAME(decoration)" did not work for me.
> 
> 2) For some reason, some of the symbol renaming ("WAYLAND_libdecor_" -> "libdecor_") causes conflicts. E.g.:
> "#define libdecor_unref (*WAYLAND_libdecor_unref)"
> works, but
> "#define libdecor_new (*WAYLAND_libdecor_new)"
> gives me "error: conflicting types for 'WAYLAND_libdecor_new'" (with the conflicting symbol in header "libdecoration.h"). It looks like all functions that return some value (non-void) cannot be renamed like this.
> @Ethan Is this supposed to work, or do I have to use the "WAYLAND_" symbols?

On 2021-02-03 22:03:41 +0000, Ethan Lee wrote:

> Buildfixes: https://github.com/flibitijibibo/SDL-mirror/commit/7d2dbc529e4ece6bfb28bcb62902dddec607df19

On 2021-02-03 22:23:24 +0000, Ethan Lee wrote:

> One more commit, this fully compiles now:
> 
> https://github.com/flibitijibibo/SDL-mirror/commit/1860847fdf38f61a5eb761b0d27f4ece5f96ba01
> 
> Linking is a different story... it's mysteriously double-defining the dynamic function pointers for some reason.

On 2021-02-03 22:39:15 +0000, Ethan Lee wrote:

> Found the bug: libdecoration.h includes wayland-client.h, which basically means including libdecoration.h can't work at all! We need to include libdecoration after this line...
> 
> https://hg.libsdl.org/SDL/file/53efc2c1b4c8/src/video/wayland/SDL_waylanddyn.h#l40
> 
> ... because if we don't we end up macro'ing over the libdecoration.h function declarations, leading to double definitions. Problem is, by including it there, we trip this error handler (or rather we should, but it doesn't check for WAYLAND_CLIENT_H, another unrelated bug):
> 
> https://hg.libsdl.org/SDL/file/53efc2c1b4c8/src/video/wayland/SDL_waylanddyn.h#l67
> 
> So the two things we need from libdecoration are:
> 
> 1. Replace stdbool.h with uint8_t
> 2. Forward declare the related wayland-client.h structs and include this header in the libdecoration source, rather than the API header
> 
> Once that's done, all of the libdecoration.h includes can be deleted in favor of that one spot in waylanddyn.h, and everything should compile and link properly after that.

On 2021-02-03 22:57:40 +0000, Ethan Lee wrote:

> Created attachment 4756
> libdecoration API fixes
> 
> Apologies for the spam, but since I was proposing API changed I figured I may as well write them in...
> 
> With the attached patch to libdecoration, SDL-libdecoration now fully compiles and links with the following branch:
> 
> https://github.com/flibitijibibo/SDL-mirror/tree/decoration_dlopen

On 2021-02-03 23:26:31 +0000, Christian Rauch wrote:

> (In reply to Ethan Lee from comment # 35)
> > Created attachment 4756 [details]
> > libdecoration API fixes
> > 
> > Apologies for the spam, but since I was proposing API changed I figured I
> > may as well write them in...
> > 
> > With the attached patch to libdecoration, SDL-libdecoration now fully
> > compiles and links with the following branch:
> > 
> > https://github.com/flibitijibibo/SDL-mirror/tree/decoration_dlopen
> 
> Thanks for your linking fixes.
> 
> Actually, your previous commit "Almost linking..." already worked in my setup. Meaning that it linked successfully and the test executables also worked as expected. On the contrary, your next commit "libdecoration links!" does not compile on my setup :-)
> 
> Is there a SDL CI somewhere, where these things can be tested on "neutral" ground?
> 
> Btw, feel free to send pull-request via GitHub directly to my branch to simplify the development there. We can then post the merged/squashed patches here again when they are ready for review. I will squash some of your commits already into my branch and rewrite the history. So you may have to fetch changed and rebase again.

On 2021-02-05 00:12:34 +0000, Ethan Lee wrote:

> Created attachment 4762
> Whitespace fix
> 
> On the code, side, this branch is now ready for review:
> 
> https://github.com/christianrauch/SDL/tree/decoration_dlopen
> 
> The CMake stuff may be different in the final patch, however - more than likely we'll wait for libdecoration's first official release (AKA the ABI freeze), then instead of having it as an external project we'll depend on the distribution to provide it when building.
> 
> There are a couple other small diffs in that branch, but I filed # 5531 and attached another quick patch here deal with those.

On 2021-02-05 01:33:19 +0000, Sam Lantinga wrote:

> We definitely shouldn't ship with support for libdecoration before it reaches first stable release. Looking at it, I can definitely see that it's going to evolve quite a bit from here.

On 2021-02-05 01:38:04 +0000, Ellie wrote:

> Maybe it could be merged a build option that is disabled by default for now? So curious people can manually build SDL2 and test libdecoration use. (My apologies if that was the plan all along.)

On 2021-02-05 01:40:46 +0000, Christian Rauch wrote:

> (In reply to Ethan Lee from comment # 37)
> > On the code, side, this branch is now ready for review:
> > 
> > https://github.com/christianrauch/SDL/tree/decoration_dlopen
> 
> Nevermind my previous comment about linking issues. I overlooked that you attached a patch for libdecoration.
> The "decoration_dlopen" now has two commits:
> 1. "dynamic libdecoration loading" this is with Ethan's initial dlopen changes and some minor changes from my side, and works with the upstream libdecoration
> 2. "use libdecoration header (with custom patch)" is the one that only works with Ethan's libdecoration patch
> 
> > The CMake stuff may be different in the final patch, however - more than
> > likely we'll wait for libdecoration's first official release (AKA the ABI
> > freeze), then instead of having it as an external project we'll depend on
> > the distribution to provide it when building.
> 
> I agree with waiting for a released version with ABI freeze. However, I doubt that distributions will pick that up quickly, especially since nothing depends on it right now (chicken or egg problem) and the Wayland support is not even active by default.
> I would still propose to depend on an upstream released version for now, so that the Wayland+Decoration functionality can be tested together in real applications.

On 2021-02-05 03:31:59 +0000, Ethan Lee wrote:

> As soon as a tag is established we can apply the final version of this change, and proposing the new package should be pretty straightforward with SDL to show as a primary consumer. I imagine with Wayland approaching critical mass at this point it won't be that hard of a pitch, particularly for any distribution shipping GNOME by default.
> 
> For now we can just keep the libdecoration patch as a separate thing to be rebased every now and then. Just about the only thing we could do to polish this further...
> 
> - Change `DECORATION` to `HAVE_LIBDECORATION_H`
> - Add ifdefs to libdecoration paths, to ensure building without libdecoration is still possible
> - Add support for both dynamic loading and dynamic linking paths
> - autoconf support
> - SetWindowResizable, SetWindowBordered support
> - GetWindowBordersSize support
> 
> Once all that's done we can squash the whole diff down to a single hg commit to be hosted here, and as long as someone keeps it up to date we can import it the same day the ABI is frozen.

On 2021-02-05 14:07:06 +0000, Sam Lantinga wrote:

> (In reply to Ethan Lee from comment # 41)
> > Once all that's done we can squash the whole diff down to a single hg commit
> > to be hosted here, and as long as someone keeps it up to date we can import
> > it the same day the ABI is frozen.
> 
> That sounds like a good plan. I'll leave this bug here on WAITING until then.

On 2021-02-05 21:01:47 +0000, Ethan Lee wrote:

> Created attachment 4765
> libdecoration Support
> 
> Attaching an updated patch to obsolete the others, omits the CMake changes for now. This includes the 5531 patch, whitespace patch, and unused SDL_DisplayMode variable fix.
> 
> Updated TODO:
> 
> - Remaining 'FIXME libdecoration' lines, mostly API issues
> - CMake support for both dynamic loading and dynamic linking
> - autoconf support

On 2021-02-05 21:23:21 +0000, Christian Rauch wrote:

> (In reply to Ethan Lee from comment # 43)
> > Created attachment 4765 [details]
> > libdecoration Support
> > 
> > Attaching an updated patch to obsolete the others, omits the CMake changes
> > for now. This includes the 5531 patch, whitespace patch, and unused
> > SDL_DisplayMode variable fix.
> 
> I am bit confused. This patch contains changes that are already part of the "decoration" / "decoration_dlopen" branch. Is this just an alternative version to these branches or does the patch represent the same version just with squashed commits?

On 2021-02-05 21:25:28 +0000, Ethan Lee wrote:

> This is a squashed version that can be imported into Mercurial directly. It's the same thing as the branch I have submitted as a pull request to the Git version.

On 2021-02-05 21:49:50 +0000, Christian Rauch wrote:

> (In reply to Ethan Lee from comment # 45)
> > This is a squashed version that can be imported into Mercurial directly.
> > It's the same thing as the branch I have submitted as a pull request to the
> > Git version.
> 
> Hm, I never received a PR to my GitHub branches. How would you like to proceed to integrate your changes into my branch? I am likely to apply more changes to my branch before an initial version of libdecoration gets released.
> I would prefer to get PRs on GitHub or alternatively patches that I can apply on top of my branch. I also propose to keep non-decoration commits (e.g. white-space fixes, unused variables, ...) separate.

On 2021-02-05 21:51:20 +0000, Ethan Lee wrote:

> You may need to watch the repo, for some reason it doesn't always happen. You're looking for this:
> 
> https://github.com/christianrauch/SDL/pull/1

### PR DESCRIPTION
**Pull request by christianrauch**
The attached set of patches implement client-side window decorations on Wayland using 'libdecoration' from https://gitlab.gnome.org/jadahl/libdecoration. The libdecoration dependency is downloaded directly from upstream at build-time.

sdl_decoration_scale
sdl_decoration_sprite2

This fixes https://bugzilla.libsdl.org/show_bug.cgi?id=2710

This fixes #3739.

Cheers and thanks for making Linux gaming happen :-)

### CODE REVIEW

File: src/video/wayland/SDL_waylandwindow.c [hunk 1]
```diff
@@ -622,6 +704,11 @@ Wayland_SetWindowBordered(_THIS, SDL_Window * window, SDL_bool bordered)
 {
     SDL_WindowData *wind = window->driverdata;
     const SDL_VideoData *viddata = (const SDL_VideoData *) _this->driverdata;
+#ifdef HAVE_LIBDECORATION_H
+    if (viddata->shell.libdecoration) {
+        SDL_SetError("FIXME libdecoration: Implement toggling decorations");
+    } else
+#endif
```
Comment (icculus) [inline src/video/wayland/SDL_waylandwindow.c:711]: This isn't a non-negotiable requirement to get this PR merged, but do we know if this FIXME is easy to implement, hard to implement, or impossible to implement, with the current state of libdecoration?

File: cmake/sdlchecks.cmake [hunk 2]
```diff
@@ -662,6 +662,22 @@ macro(CheckWayland)
...
+        ExternalProject_Add(libdecoration
+          PREFIX "${CMAKE_CURRENT_BINARY_DIR}/extern/libdecoration"
+          GIT_REPOSITORY https://gitlab.gnome.org/jadahl/libdecoration.git
+          GIT_TAG master
+          CONFIGURE_COMMAND meson --prefix "${CMAKE_CURRENT_BINARY_DIR}/install" --libdir "lib" ../libdecoration
+          BUILD_COMMAND ninja
+          INSTALL_COMMAND ninja install
+        )
+
+        set(SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_LIBDECORATION "\"libdecoration.so\"")
```
Comment (icculus) [inline cmake/sdlchecks.cmake:676]: I would _really_ like to not have this pull in external code at configure time, especially if we have to count on meson being installed to make this work.

Generally we check if the header/lib is available on the system and either enable the feature, or not, from there.

Is libdecoration not available in distros yet?

**Review by icculus — CHANGES_REQUESTED** [review]
Overall this looks pretty good. I'm willing to merge this as-is, with the FIXME in place, if we can solve the external project dependency I mentioned.

File: cmake/sdlchecks.cmake (hunk 2 above)
Comment (flibitijibibo) [reply cmake/sdlchecks.cmake:676]: At the moment libdecoration is still in development, the ABI hasn't frozen yet. This probably won't be in distributions until 1.0 is tagged.

**Comment by flibitijibibo** [comment]
I only have 3 concerns left at this point, other than the ABI freeze:

- Do we need to get autoconf support in first?
- Do we care that this introduces stdbool? I know we normally target C89 but I dunno if the Wayland stuff requires that... I did make a patch to libdecoration that fixed that as well as the wayland-client.h include (hence all the struct declarations in the headers).
- How do we want to prioritize libdecoration on the list of backends? Should it be ranked above or below xdg-shell/server-side decorations?

File: src/video/wayland/SDL_waylandwindow.c (hunk 1 above)
Comment (christianrauch) [reply src/video/wayland/SDL_waylandwindow.c:711]: There is a PR pending for this https://gitlab.gnome.org/jadahl/libdecoration/-/merge_requests/20, but it depends on `xdg-decoration` supporting this too https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/17.

File: cmake/sdlchecks.cmake (hunk 2 above)
Comment (christianrauch) [reply cmake/sdlchecks.cmake:676]: I agree that the final merged support should not pull in the dependency like this. How is SDL handling third-party dependencies that are not distributed by distributions yet? In the age of flatpak and snaps, this is not an issue since these third-party dependencies can be pulled in manually from source.

`libdecoration` has not had a release yet. Some pending PRs are to be merged and a 0.1 release is imminent (cc @jadahl). But even then, it will take a while until this is picked up by distributions.

@icculus What do you propose?
- Do you want to wait until a first libdecoration 0.1 release is distributed by distributions, before supporting Wayland? If so, which distributions would that be?
- Should there be a way for SDL to depend on third-party libraries?

Comment (christianrauch) [reply cmake/sdlchecks.cmake:676]: The SDL source tree already contains it's own set of `wayland-protocols` instead of depending on the definitions supplied by the distributions. Should all third-party dependencies be integrated this way directly in the source three?

**Comment by christianrauch** [comment]
> * Do we need to get autoconf support in first?

The [SDL Debian package](https://salsa.debian.org/sdl-team/libsdl2/-/blob/master/debian/rules) is still using the autoconf build script. I can look into integrating the libdecoration dependency into the script, once there is a released version.

> * Do we care that this introduces stdbool? I know we normally target C89 but I dunno if the Wayland stuff requires that... I did make a patch to libdecoration that fixed that as well as the wayland-client.h include (hence all the struct declarations in the headers).

Is C89 compatibility still a requirement? I would say that every distribution that includes Wayland also includes a C99 capable compiler. What would be the benefit of restricting the Wayland support to standards that are older than the Linux kernel itself?

> * How do we want to prioritize libdecoration on the list of backends? Should it be ranked above or below xdg-shell/server-side decorations?

If you want client-side decorations via libdecoration, it **must** come first. Prioritising `xdg-shell` over libdecoration effectively disables the library and makes this PR obsolet.

**Comment by icculus** [comment]
> - Do we need to get autoconf support in first?

We need it, but we can merge this and add that later, as long as we do it before 2.0.16 ships.

> - Do we care that this introduces stdbool?

I'd have to look again, but if the headers use stdbool, that is tolerable, but we should not otherwise introduce it in our code.

> - How do we want to prioritize libdecoration on the list of backends? Should it be ranked above or below xdg-shell/server-side decorations?

Prefer over xdg-shell, but maybe SSD is preferred over this? What happens if libdecoration is available but you're running KDE? Do you get GTK decorations?

**Comment by jadahl** [comment]
> Prefer over xdg-shell, but maybe SSD is preferred over this? What happens if libdecoration is available but you're running KDE? Do you get GTK decorations?

libdecoration supports xdg-toplevel-decoration if available, and use SSD if that is preferred by the compositor.

**Comment by flibitijibibo** [comment]
> > Prefer over xdg-shell, but maybe SSD is preferred over this? What happens if libdecoration is available but you're running KDE? Do you get GTK decorations?
> 
> libdecoration supports xdg-toplevel-decoration if available, and use SSD if that is preferred by the compositor.

Ah cool, that was the only reason I asked - so yeah, where the libdecor path is at now works for me. So once the ABI is frozen this should be good to go I think, that should buy enough time for someone to write in the autoconf stuff.

File: src/video/wayland/SDL_waylandwindow.c [hunk 3]
```diff
@@ -924,12 +1105,37 @@ void Wayland_SetWindowSize(_THIS, SDL_Window * window)
...
+Wayland_GetWindowBordersSize(_THIS, SDL_Window * window, int *top, int *left, int *bottom, int *right)
+{
+#ifdef HAVE_LIBDECORATION_H
+    SDL_VideoData *viddata = (SDL_VideoData *) _this->driverdata;
+    if (viddata->shell.libdecoration) {
+        *top = 0;
+        *left = 0;
+        *bottom = 0;
+        *right = 0;
+        return SDL_SetError("FIXME libdecoration: Support GetWindowBordersSize");
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandwindow.c:1118]: Forgot to mention here - if it helps with the API design on libdecor's part, we're okay with this having a return value indicating lack of support in the backend. From what I understand this is something CSD can do pretty easily but SSD/xdg-decoration don't and won't support this, so having an error path for those situations is fine.

**Comment by slouken** [comment]
Yup, just be be clear, this should not be pulled until libdecoration has hit ABI freeze.

File: src/video/wayland/SDL_waylandwindow.c (hunk 3 above)
Comment (jadahl) [reply src/video/wayland/SDL_waylandwindow.c:1118]: I think the best thing to do is to always return 0 no matter what. These values have no use case under Wayland, and the fact that there might be subtle differences depending on the configuration, any accidental use would be fragile, so things would be more predictable if it'd just always be assumed to be 0.

Comment (flibitijibibo) [reply src/video/wayland/SDL_waylandwindow.c:1118]: I'm not so sure about that - @icculus, I know this is in UE4 but do you recall what made this necessary? As far as I can tell it's used for mouse input but I don't have a good setup to check how Wayland behaves without this.

File: cmake/sdlchecks.cmake (hunk 2 above)
Comment (icculus) [reply cmake/sdlchecks.cmake:676]: To be clear, I'm ignorant of obvious details here, so:

- If libdecoration is just a C callable API, we will require the headers be available on the system at build time and will dynamically load the shared library at runtime. If it's not in distributions yet, that's not our problem; if we see it when configuring, it's enabled, otherwise it's not. This lets the bleeding edge install it from source before the world catches up, but the binary that is built will work with or without the library on the end-user's system.
- If it's just a wayland protocol, that's a no-brainer, we just put the protocol files in SDL's tree and call it a day. At runtime we either have the protocol or we don't and we have to handle both cases anyhow. Assuming they're doing things in the usual Wayland way, we can commit before ABI is stable because the protocol name will change and we'll ignore the changed version (and later, we can decide to upgrade or support both codepaths as appropriate...for this it sounds like we'd just dump support for the pre-0.1 release).

But it would be helpful to for @jadahl to say how far from a stable ABI we are at the moment.

Comment (jadahl) [reply cmake/sdlchecks.cmake:676]: Libdecoration is C API/ABI, that aims to lock into an ABI in the near future. I intend to package it for Fedora (F35) after that happens, and I hope it'll show up elsewhere as well. I'm sure you will see comments about it here when that happens.

File: src/video/wayland/SDL_waylandwindow.c (hunk 3 above)
Comment (jadahl) [reply src/video/wayland/SDL_waylandwindow.c:1118]: Pointer/mouse input in Wayland is always relative to a `wl_surface`.

One place it might be relevant is for placing `xdg_popup` surfaces; it would need to take the non-drop-shadow part of the window border size into account, e.g. the title bar. How exactly is popup positioning (menus etc) handled with SDL?

**Review by pkf1994 — COMMENTED** [review]
###Good###

**Comment by christianrauch** [comment]
Can someone tell me why the CI is trying to link against `libdecor` although `WAYLAND_LIBDECOR` is not defined (`WAYLAND_LIBDECOR       (Wanted: ON): OFF`)? I don't see this issue in my local builds.

**Comment by flibitijibibo** [comment]
This got clobbered slightly by https://github.com/libsdl-org/SDL/commit/57a927e8d7f4290c7aa696c86144ac88c3bcac3d. Nothing major, it just collides at SetWindowMin/MaxSize, the fix will look roughly the same as the other places where xdg/zxdg paths exist.

**Comment by christianrauch** [comment]
> This got clobbered slightly by [57a927e](https://github.com/libsdl-org/SDL/commit/57a927e8d7f4290c7aa696c86144ac88c3bcac3d).

I rebased and in the process squashed the commits to make the rebase easier. It works but I may have still forgotten something.

File: src/video/wayland/SDL_waylandwindow.c [hunk 4]
```diff
@@ -977,6 +1129,13 @@ Wayland_SetWindowMaximumSize(_THIS, SDL_Window * window)
     SDL_WindowData *wind = window->driverdata;
 
     if (window->flags & SDL_WINDOW_RESIZABLE) {
+#ifdef HAVE_LIBDECOR_H
+        if (data->shell.libdecor) {
+            libdecor_frame_set_max_content_size(wind->shell_surface.libdecor.frame,
+                                                window->max_w,
+                                                window->max_h);
+        }
+#else
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandwindow.c:1138]:
```suggestion
        } else
#endif
```
Along with removing the `#endif` slightly below.

**Review by flibitijibibo — CHANGES_REQUESTED** [review]
Only found one thing, the rest looks okay.

**Review by flibitijibibo — APPROVED** [review]

File: CMakeLists.txt [hunk 5]
```diff
@@ -2322,6 +2326,11 @@ if(SDL_STATIC)
   if(IOS OR TVOS)
     set_property(TARGET SDL2-static APPEND_STRING PROPERTY COMPILE_FLAGS "-fobjc-arc")
   endif()
+  if(WAYLAND_LIBDECOR)
+    target_include_directories(SDL2-static PRIVATE "${libdeocr_INCLUDE_DIRS}")
+    target_link_libraries(SDL2-static "${libdecor_LIBRARIES}")
+
```
Comment (flibitijibibo) [inline CMakeLists.txt:2332]:
```suggestion
```

File: src/video/wayland/SDL_waylandwindow.c [hunk 6]
```diff
@@ -652,6 +738,16 @@ Wayland_SetWindowResizable(_THIS, SDL_Window * window, SDL_bool resizable)
...
 
+#ifdef HAVE_LIBDECOR_H
+    if (data->shell.libdecor) {
+        if (resizable) {
+            libdecor_frame_set_capabilities(wind->shell_surface.libdecor.frame, LIBDECOR_ACTION_RESIZE);
+        } else {
+            libdecor_frame_unset_capabilities(wind->shell_surface.libdecor.frame, LIBDECOR_ACTION_RESIZE);
+        }
+    }
+    else
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandwindow.c:749]:
```suggestion
    } else
```

File: src/video/wayland/SDL_waylandwindow.c [hunk 7]
```diff
@@ -958,6 +1102,14 @@ Wayland_SetWindowMinimumSize(_THIS, SDL_Window * window)
     SDL_WindowData *wind = window->driverdata;
 
     if (window->flags & SDL_WINDOW_RESIZABLE) {
+#ifdef HAVE_LIBDECOR_H
+        if (data->shell.libdecor) {
+        libdecor_frame_set_min_content_size(wind->shell_surface.libdecor.frame,
+                                            window->min_w,
+                                            window->min_h);
+        }
+        else
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandwindow.c:1111]:
```suggestion
        } else
```

**Review by flibitijibibo — COMMENTED** [review]
A bunch of tiny spacing changes since I had a couple minutes to burn.

**Comment by DragonSWDev** [comment]
What is left to do before this pull request will be merged?

**Comment by christianrauch** [comment]
> What is left to do before this pull request will be merged?

`libdecor` has to tag a release. It would probably also help if the released version gets distributed but distributions (Debian, ...).

File: src/video/wayland/SDL_waylandwindow.c [hunk 8]
```diff
@@ -958,6 +1101,13 @@ Wayland_SetWindowMinimumSize(_THIS, SDL_Window * window)
     SDL_WindowData *wind = window->driverdata;
 
     if (window->flags & SDL_WINDOW_RESIZABLE) {
+#ifdef HAVE_LIBDECOR_H
+        if (data->shell.libdecor) {
+        libdecor_frame_set_min_content_size(wind->shell_surface.libdecor.frame,
+                                            window->min_w,
+                                            window->min_h);
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandwindow.c:1108]: Latest pass. Why do I keep missing these...

```suggestion
            libdecor_frame_set_min_content_size(wind->shell_surface.libdecor.frame,
                                                window->min_w,
                                                window->min_h);
```

File: src/video/wayland/SDL_waylandwindow.c [hunk 9]
```diff
@@ -372,6 +395,64 @@ static const struct xdg_toplevel_listener toplevel_listener_xdg = {
...
+{
+    SDL_WindowData *wind = user_data;
+    SDL_Window *window = wind->sdlwindow;
+    int width, height;
+    struct libdecor_state *state;
+
+    /* window size */
+    if (!libdecor_configuration_get_content_size(configuration, frame, &width, &height)) {
+            width = window->w;
+            height = window->h;
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandwindow.c:412]:
```suggestion
        width = window->w;
        height = window->h;
```

File: src/video/wayland/SDL_waylandvideo.c [hunk 10]
```diff
@@ -386,6 +391,21 @@ static const struct xdg_wm_base_listener shell_listener_xdg = {
 };
 
 
+#ifdef HAVE_LIBDECOR_H
+static void
+libdecor_error(struct libdecor *context,
+                    enum libdecor_error error,
+                    const char *message)
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandvideo.c:398]:
```suggestion
               enum libdecor_error error,
               const char *message)
```

**Review by flibitijibibo — COMMENTED** [review]
Ah... I'm bad at this.

**Comment by DragonSWDev** [comment]
> > What is left to do before this pull request will be merged?
> 
> `libdecor` has to tag a release. It would probably also help if the released version gets distributed but distributions (Debian, ...).

Thanks for answer. Probably we can expect distributions to pickup libdecor when libraries like SDL will merge support for it. I hope it will happen soon, SSD vs CSD issue needs to be fixed and I think libdecor is good way to do it.

File: CMakeLists.txt [hunk 11]
```diff
@@ -2406,6 +2407,9 @@ if(SDL_SHARED)
     set_property(TARGET SDL2 APPEND_STRING PROPERTY COMPILE_FLAGS "-fobjc-arc")
     target_compile_definitions(SDL2 PRIVATE IOS_DYLIB=1)
   endif()
+  if(WAYLAND_LIBDECOR)
+    target_include_directories(SDL2 PRIVATE "${libdeocr_INCLUDE_DIRS}")
```
Comment (flibitijibibo) [inline CMakeLists.txt:2411]: Just realized this and the line further down has `libdeocr` rather than `libdecor` - could this be why we need the "libdecor-0.1" folder in the `#include`s? From what I can tell the pkg-config for libdecor already includes it.

Comment (christianrauch) [reply CMakeLists.txt]: I had `libdecor-0.1/` in the `#include` because I did not realise that I was actually adding the include dir in CMake.

I just realised now that there is a typo in the CMake variable. This is fixed now and including `libdecor.h` is enought.

File: src/video/wayland/SDL_waylanddyn.h [hunk 12]
```diff
@@ -100,6 +114,30 @@ void SDL_WAYLAND_UnloadSymbols(void);
 #define wl_data_source_interface (*WAYLAND_wl_data_source_interface)
 #define wl_data_device_manager_interface (*WAYLAND_wl_data_device_manager_interface)
 
+#ifdef HAVE_LIBDECOR_H
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylanddyn.h:117]: This was the only issue I was able to find in the build process as of the latest revision - this resolves a linker error where the libdecor includes that happen later get ripped up by these defines and cause double definitions. With this I'm able to build libdecor+SDL and run CSD successfully, albeit with some unrelated issues (will try and write up everything on Monday).

```suggestion
#ifdef HAVE_LIBDECOR_H
/* Must be included before our defines */
#include <libdecor.h>

```

Comment (christianrauch) [reply src/video/wayland/SDL_waylanddyn.h:117]: Is this a linking error on your local system? I didn't see it on my configuration or the CI.

Comment (flibitijibibo) [reply src/video/wayland/SDL_waylanddyn.h:117]: Yes, this was on my Wayland test box - Fedora 33 Workstation, libdecoration installed to `/usr/local/`, with `dnf builddep SDL2`.

**Comment by ell1e** [comment]
Can I just remark something visual: I think in the example screenshot the title bar looks very cramped, very 1995 (and not in a good way, IMHO).

GNOME and also Windows 10 use larger title bars these days, which is also relevant for touch devices:

GNOME:


Windows 10:


While KDE less so, it still looks larger than the libdecoration one:



Compare this to the measly looking one from the demonstration screenshot:


I think it makes sense to aim more for a Windows 10/GNOME size for the libdecoration default. E.g. this also impacts devices like the PineTab or PinePhone where touch is pretty central, so going really minimal on the height not only looks dated but can be an actual accessibility problem.

**Comment by christianrauch** [comment]
The `cairo` plugin is the most minimal but functional plugin in `libdecor`. Its primary purpose is to extend and test the core API to support all common decoration functions (move / resize / minimise / maximise / close).

You can implement additional, more complex plugins. The idea is then that the library would select an appropriate plugin for the desktop. I am currently working on a GTK plugin. Every help in realising this is welcome :-)

My personal opinion about decorations:
1. increasing the titlebar size from currently 24px to GTK's 37px (the non-`GtkHeaderBar` version, e.g. as shown with XWayland) does not improve the usability much
2. using the `GtkHeaderBar` without additional widgets is a waste of space (especially on small phone screens)
3. using stacking window managers on a small phone screen does not make sense at all

**Comment by ell1e** [comment]
> increasing the titlebar size from currently 24px to GTK's 37px (the non-GtkHeaderBar version, e.g. as shown with XWayland) does not improve the usability much

Can you elaborate why not? I think especially on a tablet actually it does. We're talking about 54% larger target area here.

> using the GtkHeaderBar without additional widgets is a waste of space (especially on small phone screens)

Have you tried windowed GTK+ apps on a PinePhone or Librem 5 at all? It's not very significant, try it out yourself. And there is a real problem with accurately pressing any buttons, on a phone in particular, on a title bar that somehow tries to be minimal for whatever misguided reason.

> using stacking window managers on a small phone screen does not make sense at all

All Linux phones support seamless convergence, also there is still fullscreen for when you want the full multimedia space. So all of them use a stacked window manager, and it works fine. I can only suggest again to try one of the Linux phones for yourself, it works fine.

I think the default should be maximum accessibility, not some needless misguided attempt to minimize space. Defaults are very important because many apps will not change them. Therefore, I don't think the common defaults are good.

**Comment by christianrauch** [comment]
Is your concern about to the "90's" UI style of the decoration or its usability on touch screen devices?

I am not against larger UI elements for touch devices, I am just not convinced anybody would use stacked window managers on small touch screens to move and resize application windows.

> I think especially on a tablet or phone, actually it does.

Until we see mass usage of stacked window managers on 5~10 inch touch screens, I really don't see the point of bothering with these details. If you want to use decorations on a particular system, you should go with the UI guidelines there and probably use their toolkit if you really have to (i.e. GTK in the Librem 5 case).

> Have you tried windowed GTK+ apps on a PinePhone or Librem 5 yourself?

Nope, I don't own such devices. But Android and iOS are pretty successful, even without using stacked window managers. If you attach a large screen to experience "seamless convergence" then you probably also don't need thick title bars without widgets.

If you really must use titlebars on phones or tablets, I would suggest drawing the decoration with the same toolkit that is used for applications to match the UI scale. The `cairo` plugin is meant for classical desktops as this is where stacked window managers are used most often. If you need a different plugin to match another type of device, then we will happily review patches that implement decorations for this device's specific toolkit.

**Comment by ell1e** [comment]
> I am not against larger UI elements for touch devices, I am just not convinced anybody would use stacked window managers on small touch screens to move and resize application windows.

> Until we see mass usage of stacked window managers on 5~10 inch touch screens,

Again, Phosh is a stacked window manager. As is Unity Mir I think? So I'm not sure what there is to convince, people mostly *only* use stacked window manager on Linux phones *right now*.

About 99% of Linux phones use it. Is that not good enough? There are also Linux laptops with touch screens, and the PineTab.

> Is your concern about to the "90's" UI style of the decoration or its usability on touch screen devices?

Purely the usability.

**Comment by ell1e** [comment]
I forgot I guess I can just show a screenshot. This is PinePhone+Phosh, a stacked window manager that is probably the most widely used one on Linux phones (or maybe it's UBports/Ubuntu Touch's Mir, which to my knowledge is also stacked). Please note the visible, large sized title bar:

bla

So this really isn't a theoretical use case, linux phones do run stacked window managers.

**Comment by flibitijibibo** [comment]
This might be something to file on https://gitlab.gnome.org/jadahl/libdecoration, as I believe the decoration is backend-specific. On KDE for example my test windows are using the same decorations as everything else on the desktop.

**Comment by flibitijibibo** [comment]
Right, so I finally got a chance to mess around with this... it's nice to finally have a title bar on GNOME for the first time. But it looks like some work is needed, not sure where in the chain it's needed but hopefully this data helps:

Here's FEZ before this patchset, borderless and all:

Screenshot from 2021-03-13 23-20-13

The KDE decorations work fine, but we get an interesting result from libdecor for GNOME...

Screenshot from 2021-03-13 23-20-59

This isn't total nonsense - the window FNA creates at first is 800x480, so it's likely the decoration just doesn't catch up when we show the window resized at 1280x720. I figured a resize might get its attention...

Screenshot from 2021-03-13 23-21-26

Nope. Maybe toggling fullscreen and back...?

Screenshot from 2021-03-13 23-21-49

Oof. So it _really_ wants to stick to the first resolution it sees. As far as I can tell we're doing the min/max updates correctly, and manually adding them to SetWindowSize for the libdecor path had no effect.

It'd probably help to have more data, so: I just did a _ton_ of updates to my catalog recently, so all you have to do is overwrite `lib64/libSDL2-2.0.so.0` and be sure libdecor is in your LD_LIBRARY_PATH to test CSD. Here are all the FNA games I still personally maintain on Steam and should work with a patched SDL binary:

- Capsized
- Gateways
- Escape Goat 1 & 2
- Soulcaster I/II
- FEZ
- A Virus Named TOM
- Rogue Legacy
- Dust: An Elysian Tail
- Blueberry Garden
- Fist Puncher
- Skulls of the Shogun
- TowerFall Ascension
- Apotheon
- Bleed 1 & 2
- Rex Rocket
- Wyv and Keep
- Wizorb
- Mercenary Kings
- Cryptark
- Before the Echo
- The Adventures of Shuggy
- Salt and Sanctuary
- Hidden in Plain Sight
- Quadrilateral Cowboy Art Book
- Owlboy (this one has some outdated binaries, maybe try something else...)
- Flinthook
- Charlie Murder
- The Dishwasher: Vampire Smile
- Full Metal Furies
- Flotilla
- Growing Pains
- Unexplored
- SUMICO
- Streets of Rage 4

The Celeste Steam beta also should have updated binaries. There are some other games like Bastion and Murder Miners but I dunno what FNA revision they're on these days.

**Comment by christianrauch** [comment]
> This is PinePhone+Phosh, a stacked window manager that is probably the most widely used one on Linux phones

This does show a `GtkHeaderBar` but I haven't seen this used in a stacking window manager on a small touch screen yet. With stacking window manager, I really mean having multiple windows shown at the same time, partially overlapping, and the ability to move and resize them. As shown there, this is just a dedicated space with additional widgets for opening/saving files but does not contain anything related to window management.

> Some apps on the PinePhone (I assume via Qt/GTK+ patching) simply show no title bar buttons in non-convergence/mobile mode at all, but then still render the title bar at its normal size with the program name.

You can easily enable/disable the min/max/close buttons in the `GtkHeaderBar` via standard API.

I guess how useful _that_ is is a bit questionable, but I suppose at least it's consistent with everything having title bars as in every stacked WM. So even on that front, I fail to see the point of deviating for the sake of it.

I have not yet seen examples of stacked windows on PinePhone+Phosh. All applications I've seen on screenshots are filling the entire screen. Having decorations to maximise or resize the window does not make sense in this setting.

Anyway, I don't want to prolong this discussion any longer. The `cairo` plugin was not designed for touch interfaces. Implementing a design that fits all devices types will not be possible without implementing something that adapts automatically to the device, especially when moving an application on the fly from a small touch screen to a regular desktop in the convergence case. It's more likely that you will need a plugin with a render engine that is adaptable online.

If you need a specific decoration plugin, please suggest a patch in the upstream project.

**Comment by christianrauch** [comment]
@flibitijibibo I own Capsized and Wizorb. I just quickly checked the normal mode in XWayland and Capsized starts straight into window mode, where the window is not resizeable. Wizorb starts in fullscreen mode, with the option to switch to window mode, but the window is also not resizeable.
So my initial guess is that this is related to the resize capability. If the capability is unset, the window is supposed to ignore all user-driven resize operations, including the maximise button or the grap-resizing from the window edges.

Do you have a minimal SDL example that would reproduce this behaviour? The `testscale` SDL example uses a fixed-sized window and keeps its size constant.

**Comment by DragonSWDev** [comment]
@christianrauch I checked resize issue as well and I confirm it. I made a very simple example that can show this issue:
[https://gist.github.com/DragonSWDev/a43d5db1069d9ff24f047e85292a52c8](url)

If you run this using SDL2 library with libdecor support you will get this:
Screenshot

**Comment by christianrauch** [comment]
> @christianrauch I've checked resize issue as well and I confirm it. I made a very simple example that can show this issue.

Thanks for the example.

The explanation is now smiple: The window is resized even though the SDL flags define that it is non-resizeable. On X11, this looks like:
Bildschirmfoto von 2021-03-14 13-18-21

Not sure what the expected behaviour is, but I think the window should not resize if it is defined as non-resizeable.

**Comment by flibitijibibo** [comment]
SDL_WINDOW_RESIZABLE refers to user-driven resizes, i.e. dragging the borders or double clicking the title bar. Programmatic resizes are only limited to the min/max values, if they have been set.

**Comment by christianrauch** [comment]
> Another test program: [#4065 (comment)](https://github.com/libsdl-org/SDL/pull/4065#issuecomment-778409619)

That's a useful test program to test the transition between window states. Would you mind pushing this into the repo too?

`libdecor` is actually missing a function to programmatically set the window size. I am not sure if this functionality belongs to the client or the decoration.

**Comment by ell1e** [comment]
I just wanted to add this additional small note:

> Anyway, I don't want to prolong this discussion any longer. The cairo plugin was not designed for touch interfaces. Implementing a design that fits all devices types will not be possible without implementing something that adapts automatically to the device, especially when moving an application on the fly from a small touch screen to a regular desktop in the convergence case. It's more likely that you will need a plugin with a render engine that is adaptable online.

Somehow that makes me think my entire point was missed...? Oh well. I'll make an upstream ticket soon enough.

**Comment by DragonSWDev** [comment]
@christianrauch Qemu presents exactly same issue despite window is resizable. Difference is that Qemu window fixes itself when it loses focus or when you resize or maximize it.

**Comment by flibitijibibo** [comment]
> > Another test program: [#4065 (comment)](https://github.com/libsdl-org/SDL/pull/4065#issuecomment-778409619)
> 
> That's a useful test program to test the transition between window states. Would you mind pushing this into the repo too?
> 
> `libdecor` is actually missing a function to programmatically set the window size. I am not sure if this functionality belongs to the client or the decoration.

This might be able to go into testwm2, maybe... I'll have to defer to Sam or Ryan for that.

**Comment by christianrauch** [comment]
I add the implementation for `Wayland_SetWindowSize`.

**Comment by flibitijibibo** [comment]
Latest commit fixes resizing! For whatever reason going from windowed -> fullscreen -> windowed results in a window with the wrong size (it's one resolution out of date I think), but I haven't looked into why yet.

**Comment by flibitijibibo** [comment]
Found something else that was interesting: With Vulkan specifically it looks like... maybe the decoration's gradient effect? Gets drawn on the opposite side of the window:

vkdecoration

Just about the only thing I can think of that FNA3D does that's abnormal is our use of VK_KHR_maintenance1, which lets us do D3D-style axis flipping without having to do anything in the vertex shader.

**Comment by flibitijibibo** [comment]
I believe both Capsized and Wizorb should work if you pass `/gldevice:Vulkan` as a launch option, but the `testvulkan` sample in SDL should work as a minimal test as well.

**Comment by christianrauch** [comment]
`testvulkan` works fine for me and gives the correct content and frame dimensions.

I am not able to run steam games with SDL preloaded like:
`LD_PRELOAD=[build-path]/build-SDL-Desktop-Release/libSDL2-2.0.so SDL_VIDEODRIVER=wayland ./Capsized /gldevice:Vulkan`
because it fails with Vulkan initialisation:
```
Couldn't find XDG_DATA_HOME.
Fall back to hardcoded ~/.local/share/Capsized/.
Vulkan: SDL_Vulkan_LoadLibrary failed!
No supported FNA3D driver found!
```

I am getting the `SDL_Vulkan_LoadLibrary failed!` also without `/gldevice:Vulkan` and this is the same library used for the `testvulkan` example that works.

**Comment by flibitijibibo** [comment]
Must be LD_PRELOAD acting up - try the same value with SDL_DYNAMIC_API instead.

**Comment by christianrauch** [comment]
> Must be LD_PRELOAD acting up - try the same value with SDL_DYNAMIC_API instead.

Yes, that does the trick:
`SDL_LIB=[build-path]/build-SDL-Desktop-Release/libSDL2-2.0.so LD_PRELOAD=$SDL_LIB SDL_DYNAMIC_API=$SDL_LIB SDL_VIDEODRIVER=wayland ~/.steam/steamapps/common/Capsized/Capsized /gldevice:Vulkan`

I can reproduce the same effect now (content outside of frame) with `Capsized` in windowed mode using Vulkan, but it behaves as expected with OpenGL.

However, even if I start the program in fullscreen, the GNOME Shell application overview (Meta/Win Key) will show decorations around the window which is supposed to be fullscreen. Your shell test code, that switches to fullscreen via `SDLK_3` does not show this behaviour, i.e. the fullscreen window will not have decorations.

**Comment by flibitijibibo** [comment]
Odd! For reference, here's what I lovingly call FNA's WM Gauntlet:

https://github.com/FNA-XNA/FNA/blob/master/src/FNAPlatform/SDL2_FNAPlatform.cs#L406

**Comment by flibitijibibo** [comment]
I was able to reproduce the issue with vkQuake:

vkqd

**Comment by flibitijibibo** [comment]
Yet Another Twist! When forcing the window to be resizable, the issue goes away. Shoving `window->flags |= SDL_WINDOW_RESIZABLE;` near the top of Wayland_CreateWindow is enough to force it.

At the same time I found an interesting bug that may actually be related: It appears the decorations themselves have a different focus than the window it's on. If you take the above fix and try to resize the window, it breaks pretty hard! This is because of a safety feature we have in FNA that prevents excessive resizing on various platforms:

https://github.com/FNA-XNA/FNA/blob/master/src/FNAPlatform/SDL2_FNAPlatform.cs#L935-L945

For whatever reason, SDL_WINDOW_INPUT_FOCUS flag is not set despite the fact that we're dragging the window frame all over the place. My reason for assuming it's the decoration is because when resizing via double-clicking the titlebar, the INPUT_FOCUS flag is properly set. If we can propagate the decoration's focus to the window itself it should resolve this issue, and depending on how closely linked this is to the resizable fix it may also fix the weird shadow bug.

File: src/video/wayland/SDL_waylandwindow.c [hunk 13]
```diff
@@ -994,8 +1151,24 @@ void Wayland_SetWindowSize(_THIS, SDL_Window * window)
...
+        /* TODO: check if this is really needed as this should be handled by
+         * 'Wayland_SetWindowResizable' and LIBDECOR_ACTION_RESIZE
+         */
+        if (data->shell.libdecor) {
+            libdecor_frame_set_min_content_size(wind->shell_surface.libdecor.frame,
+                                                window->w,
+                                                window->h);
+            libdecor_frame_set_max_content_size(wind->shell_surface.libdecor.frame,
+                                                window->w,
+                                                window->h);
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandwindow.c:1169]: Boy I'm just spamming this thread aren't I...

Commenting this section fixes the shadow bug on Vulkan. It's possible that the content size limits are unintentionally clamping values needed by the plugin to render content outside of our window rectangle? In any case it seems like your TODO checks out, removing this fixes a bug and it doesn't seem to affect resizability because libdecor has a separate toggle for that feature.

Comment (christianrauch) [reply src/video/wayland/SDL_waylandwindow.c:1169]: Even after this, I still see some mismatching between the content and the decoration size when the chosen resolution is higher than the native display resolution. In this case, the window decoration will appear maximised, while the content will be shown at the chosen resolution, partially outside of the window frame (and window geometry).

**Comment by flibitijibibo** [comment]
Should probably start an issue tracker for this... @christianrauch, this might be good to have in the OP:

- [ ] Fullscreen sometimes shows decorations, should be hidden
- [ ] Decorations are clamped to display size while the window itself is not
- [ ] `INPUT_FOCUS` window flag is dropped when clicking on decorations
- [ ] Vulkan windows have shadows rendering in the wrong place (has a fix)
- [ ] Going from windowed -> fullscreen -> windowed results in an incorrect title bar size

**Comment by flibitijibibo** [comment]
Opened up https://github.com/christianrauch/SDL/pull/2 for autoconf support. Whoever merges this into upstream will need to rerun autogen.sh afterward.

File: src/video/wayland/SDL_waylandwindow.c (hunk 13 above)
Comment (icculus) [reply src/video/wayland/SDL_waylandwindow.c:1169]: > Boy I'm just spamming this thread aren't I...

I'm pleased this work is getting so much attention, actually.  :)

**Comment by christianrauch** [comment]
@flibitijibibo I pushed a couple of changes to fix various issues with the decoration mode. This now depends on libdecor PR of mine for working properly.

There is one issue left where the decorations are shown for fullscreen windows. I only see this with the Capsized example and it behaves differently for OpenGL and Vulkan. On OpenGL, the decorations are shown in the overview, but if I toggle between the fullscreen application and the overview mode, the fullscreen mode is correctly restored. On Vulkan, the decorations are shown and when toggling the overview mode, it keeps a border on top and also shrinks the decoration size in the overview with every toggling.

I don't see this with the SDL examples (e.g. `testscale`) when switching to the fullscreen mode (Ctrl+Enter).
@flibitijibibo Do you set the fullscreen mode in a different way than how it's done via the SDL API (i.e. `SDL_SetWindowFullscreen(window, SDL_WINDOW_FULLSCREEN)`)?

**Comment by flibitijibibo** [comment]
We use SDL_WINDOW_FULLSCREEN_DESKTOP, unsetting this mode for focus loss:

https://github.com/FNA-XNA/FNA/blob/master/src/FNAPlatform/SDL2_FNAPlatform.cs#L500

https://github.com/FNA-XNA/FNA/blob/master/src/FNAPlatform/SDL2_FNAPlatform.cs#L895

**Comment by flibitijibibo** [comment]
Just tested the latest, from the list above only the shadow rendering was fixed (I don't have a test for the display size clamp but I'll take your word for it). The windowed -> fullscreen -> windowed issue still persists (and with Vulkan fullscreen doesn't work at all, but I don't recall if it was like that before) and input focus is still taken away when the decoration surface is being controlled.

**Comment by flibitijibibo** [comment]
On the FNA side I've taken out that focus fullscreen toggle... maybe this will make Wayland happy, not sure. Either way it was an odd thing that we've had for about 8 years to deal with X desktops, it might have been a Windows thing too at some point but I can't make it happen anymore.

https://github.com/FNA-XNA/FNA/commit/c75ca3e0fcb2f61dc541f8eab861a326c00a3708

**Comment by flibitijibibo** [comment]
This gets stomped on a little bit by #4285, but probably in a positive way - it shrinks a lot of the backend-specific stuff and fixes window size clamping, and may very well fix some of the frame size oddities I've been seeing with libdecor when ported over.

**Comment by flibitijibibo** [comment]
All the latest Wayland commits from other patches have been merged, so this should be good to rebase (and hopefully it will make life a bit easier and also fix some bugs that were unrelated to libdecor).

**Comment by slouken** [comment]
> All the latest Wayland commits from other patches have been merged, so this should be good to rebase (and hopefully it will make life a bit easier and also fix some bugs that were unrelated to libdecor).

It looks like it doesn't cleanly merge, can you take a look?

**Comment by flibitijibibo** [comment]
Made a merged version here:

https://github.com/flibitijibibo/SDL/tree/decoration

**Comment by christianrauch** [comment]
Your merged branch made my desktop crash :-)

I did a rebase on the new master and things seem to work. The only behaviour change that I observed is that the window (e.g. with `testvulkan`) is now created always in the top left of the screen.

**Comment by flibitijibibo** [comment]
>Your merged branch made my desktop crash :-)

nailedit.xcf

>I did a rebase on the new master and things seem to work. The only behaviour change that I observed is that the window (e.g. with testvulkan) is now created always in the top left of the screen.

This is something I've been noticing all throughout my Wayland work... is there any sort of defined behavior for where a window will end up? I'm starting to miss my SDL_WINDOWPOS_CENTERED a bit...

**Comment by flibitijibibo** [comment]
It wouldn't be a day that ends with 'y' without a commit stomping this... sorry Christian >_<

But, once again this should shrink the amount of stuff that libdecor does, the change is that we create/destroy the xdg_toplevel/xdg_surface in ShowWindow/HideWindow, rather than CreateWindow/DestroyWindow.

**Comment by flibitijibibo** [comment]
Merged tree, with a lot of the new NULL checks needed to run:

https://github.com/flibitijibibo/SDL/tree/decoration

**Comment by christianrauch** [comment]
> Merged tree, with a lot of the new NULL checks needed to run:

These merge commits make it (at least for me) hard to track the changes. I usually prefer rebases with changes to the commits directly to see a linear history of changes. Could you just rebase your fork in the tip of main?

File: src/video/wayland/SDL_waylandwindow.c [hunk 14]
```diff
@@ -102,6 +129,25 @@ SetFullscreen(SDL_Window *window, struct wl_output *output)
      */
     CommitMinMaxDimensions(window);
 
+#ifdef HAVE_LIBDECOR_H
+    if (viddata->shell.libdecor) {
+        const bool cap_resize = libdecor_frame_has_capability(
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandwindow.c:134]: Needs a null check for wind->shell_surface.libdecor.frame

File: src/video/wayland/SDL_waylandwindow.c [hunk 15]
```diff
@@ -448,8 +494,94 @@ static const struct xdg_toplevel_listener toplevel_listener_xdg = {
...
+
+    /* window state */
+    Wayland_SetWindowResizable(SDL_GetVideoDevice(), window,
+                               window->flags & SDL_WINDOW_RESIZABLE);
+
+    if (!libdecor_configuration_get_window_state(configuration, &window_state)) {
+        window_state = LIBDECOR_WINDOW_STATE_NONE;
+    }
+
+    if (window_state & LIBDECOR_WINDOW_STATE_MAXIMIZED) {
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandwindow.c:534]: This section I think has to check the existing window flags and send SDL_SendWindowEvent with `MAXIMIZED`/`RESTORED` to set these while also notifying the application that a user maximize/restore has happened. The other backends probably need this too now that I think about it...

File: src/video/wayland/SDL_waylandwindow.c [hunk 16]
```diff
@@ -855,6 +1019,21 @@ Wayland_RestoreWindow(_THIS, SDL_Window * window)
      */
     window->flags &= ~SDL_WINDOW_MAXIMIZED;
 
+#ifdef HAVE_LIBDECOR_H
+    if (viddata->shell.libdecor) {
+        const bool cap_resize = libdecor_frame_has_capability(
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandwindow.c:1024]: Needs a null check for wind->shell_surface.libdecor.frame

File: src/video/wayland/SDL_waylandwindow.c [hunk 17]
```diff
@@ -890,7 +1074,20 @@ Wayland_SetWindowBordered(_THIS, SDL_Window * window, SDL_bool bordered)
 void
 Wayland_SetWindowResizable(_THIS, SDL_Window * window, SDL_bool resizable)
 {
-    CommitMinMaxDimensions(window);
+#ifdef HAVE_LIBDECOR_H
+    const SDL_WindowData *wind = window->driverdata;
+
+    if (wind->shell_surface.libdecor.frame) {
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandwindow.c:1080]: This might be an issue if the shell surface is a union... but the null check is right at least. May just need to check the libdecor context in addition to this.

File: src/video/wayland/SDL_waylandwindow.c [hunk 18]
```diff
@@ -908,6 +1105,24 @@ Wayland_MaximizeWindow(_THIS, SDL_Window * window)
      */
     window->flags |= SDL_WINDOW_MAXIMIZED;
 
+#ifdef HAVE_LIBDECOR_H
+    if (viddata->shell.libdecor) {
+        const bool cap_resize = libdecor_frame_has_capability(
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandwindow.c:1110]: Needs a null check for wind->shell_surface.libdecor.frame

File: src/video/wayland/SDL_waylandwindow.c [hunk 19]
```diff
@@ -934,6 +1149,11 @@ Wayland_MinimizeWindow(_THIS, SDL_Window * window)
     SDL_WindowData *wind = window->driverdata;
     SDL_VideoData *viddata = (SDL_VideoData *) _this->driverdata;
 
+#ifdef HAVE_LIBDECOR_H
+    if (viddata->shell.libdecor) {
+        libdecor_frame_set_minimized(wind->shell_surface.libdecor.frame);
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandwindow.c:1154]: Needs a null check for wind->shell_surface.libdecor.frame

File: src/video/wayland/SDL_waylandwindow.c [hunk 20]
```diff
@@ -1140,25 +1369,64 @@ void Wayland_SetWindowSize(_THIS, SDL_Window * window)
...
 
     wl_surface_set_buffer_scale(wind->surface, get_window_scale_factor(window));
 
     if (wind->egl_window) {
         WAYLAND_wl_egl_window_resize(wind->egl_window, window->w * get_window_scale_factor(window), window->h * get_window_scale_factor(window), 0, 0);
     }
 
+#ifdef HAVE_LIBDECOR_H
+    if (data->shell.libdecor) {
+        state = libdecor_state_new(window->w, window->h);
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandwindow.c:1384]: Needs a null check for wind->shell_surface.libdecor.frame, once it's shown it should be the correct size...?

**Review by flibitijibibo — CHANGES_REQUESTED** [review]
This review is basically just a list of things that I screwed up by writing the HideWindow refactor.

**Comment by christianrauch** [comment]
@flibitijibibo Which issues with this libdecor integration are still unresolved from your side? Regarding your issue list https://github.com/libsdl-org/SDL/pull/4068#issuecomment-801585379, the two fullscreen issues should be resolved. I pushed one commit touching the `SDL_WINDOW_INPUT_FOCUS` but not sure if this resolved the remaining issue there.
If there are unresolved issues, can you provide ways to reproduce them with the integrated test examples?

**Comment by flibitijibibo** [comment]
I'm hoping to have my office back at full capacity on Friday, so I'll try to do one more test run using a bunch of games over the weekend. Dropping a build into any arbitrary title is probably the best way to make sure the libdecor path handles the really weird things games will do.

**Comment by flibitijibibo** [comment]
A re-test shows that the input focus flag is now properly set while resizing, and I'm not seeing the titlebar for fullscreen windows in activity view. The only bugs I'm aware of at this point:

- Toggling between windowed and fullscreen still results in completely unpredictable results. Sometimes the titlebar will be the wrong size, sometimes the window will conform to an incorrect title bar size, sometimes fullscreen mode will be restricted to the wrong size, sometimes fullscreen/windowed toggling is okay. I don't think I've had two consecutive tests act the same, which points to a really bad race condition somewhere. Capsized is an extremely good test for this because it has a lot of inconvenient, annoying hardcoded resolutions that you can mix and match with fullscreen/windowed mode. Just cycle all the options a whole bunch and it'll happen as soon as the very first time you apply changes.
- The titlebar buttons are also inconsistent - this might be external to us the decoration is presumably an external surface that reads its own input events, but in some cases they won't highlight when the cursor is over them, and even when highlighted it may not register the click action. If it matters, this is on a 200% DPI display.

Still on the TODO are borderless toggling as well as window borders size, though the latter still requires a revision to xdg-decoration before we can even try to implement that.

Something I did think about while going over this patch again: What is it about xdg-decoration that we can just plug in our own xdg_toplevel and have decorations work, while libdecoration effectively has to reimplement _all_ of xdg-shell as a separate path? Would it make the library any easier to write if we just sent our own toplevel, or libdecor sent _us_ a toplevel, so that we could use the same path we already have and libdecoration can just hook to the standard events? It would shrink this patchset by a _lot_ and would probably reduce the chance of error by a lot as well, since we know xdg-shell by itself works really well as-is, leaving little room for misinterpretation by the decorator.

**Comment by christianrauch** [comment]
Thanks for looking into this again. I haven't tried Capsized again since it requires Steam running and it takes time until I get into the settings screen for toggling fullscreen / floating mode. So debugging with the retailed Capsized version on Steam is quite time-consuming. 

Could you provide a minimal example with your framework that shows all these issues? Maybe a Capsized version without the game content and the intro, just the settings screen and the toggling functionality. Or a minimal FNA demo (that's the framework Capsized works with, right?) that shows these glitches.

> Still on the TODO are borderless toggling as well as window borders size

How important are these points for getting this to merge? The borderless toggling would probably be possible, without the xdg-decoration support. As discussed before, the window border size will probably never become available, even when using only the xdg-decoration protocol.

> What is it about xdg-decoration that we can just plug in our own xdg_toplevel and have decorations work, while libdecoration effectively has to reimplement all of xdg-shell as a separate path? Would it make the library any easier to write if we just sent our own toplevel

I think there would not be much benefit as most of the functionality comes from the event handling. Yes, the nice thing about xdg-decoration with server-side decorations is that you only have to pass your toplevel and then are done.
But with client-side decorations you have to manage everything, including all the pointer and resize events, that would otherwise be handled by the server. If libdecor would only operate on the client's xdg_toplevel, then both (the client and the library) would have to negotiate who handles all the events sent by the server. By encapsulating the toplevel in libdecor, we can handle all the events for the client.
Maybe @jadahl could say if using xdg-toplevel directly would make things easier.

**Comment by flibitijibibo** [comment]
For FNA's purposes border size can be skipped before this gets merged - borderless however is life-or-death as it's a feature games actively advertise to end users.

Totally forgot that Capsized has a murderously long intro - if you go into ~/.local/share/Capsized/Config.cfg, you can set DeveloperMode to true and it'll completely skip the opening logos and drop straight to the title screen.

**Comment by christianrauch** [comment]
@flibitijibibo The good news is that the issue with switching fullscreen <-> floating should be gone when the window is non-resizable. The bad news is that this also needs a mutter / GNOME Shell fix that is still under review: https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1795.

File: src/video/wayland/SDL_waylandevents.c [hunk 21]
```diff
@@ -328,8 +337,18 @@ ProcessHitTest(struct SDL_WaylandInput *input, uint32_t serial)
...
 
+#ifdef HAVE_LIBDECOR_H
+        /* ditto for libdecor. */
+        const uint32_t *directions_libdecor = directions_wl;
+#endif
+
         switch (rc) {
             case SDL_HITTEST_DRAGGABLE:
+#ifdef HAVE_LIBDECOR_H
+                if (input->display->shell.libdecor) {
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandevents.c:348]: This and the block below need a null check for `window_data->shell_surface.libdecor.frame`, similar to the toplevel null checks.

**Review by flibitijibibo — CHANGES_REQUESTED** [review]
Aside from the one comment (and #4386) this pretty much matches what the other paths do, so it _should_ work when Mutter is patched, I think.

I think the only other note I can think of is that this will get stepped on one final time by #4323, since that patch removes the multi-backend struct. I expect that (or an equivalent of it) to get merged once the 2.0.16 dust settles, so it may be worth checking to see what conflicts there are over there.  Maybe we can change #4323 to use a single-member struct that will temporarily look goofy but make it really easy to apply and test CSD support?

**Comment by Conan-Kudo** [comment]
> 
> * Do we need to get autoconf support in first?

[I switched Fedora's SDL2 package to CMake this week](https://src.fedoraproject.org/rpms/SDL2/c/104dfc214cb0fdf928f17df6b6cdfc2ede148f13), in preparation for this (and because CMake is just better...).

**Comment by ell1e** [comment]
>  Do we need to get autoconf support in first? ... CMake is just better

I do my static builds with autoconf because cross compilation for that "just works" with a single option. After some googling I think I'm not the only one who think CMake's cross compile behavior is a pain to work with as an end user. Therefore, please do not leave autoconf behind. (I don't mind if CMake also works, to each their own.)

**Comment by flibitijibibo** [comment]
We took care of the autoconf support for this patchset a while ago.

File: src/video/wayland/SDL_waylandwindow.c [hunk 22]
```diff
@@ -448,8 +489,105 @@ static const struct xdg_toplevel_listener toplevel_listener_xdg = {
...
+
+    window->w = wind->resize.width;
+    window->h = wind->resize.height;
+
+    /* window state */
+    if (!libdecor_configuration_get_window_state(configuration, &window_state)) {
+        window_state = LIBDECOR_WINDOW_STATE_NONE;
+    }
+
+    if (window_state & LIBDECOR_WINDOW_STATE_MAXIMIZED) {
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandwindow.c:526]: This should have the patch from #4386 applied here.

File: src/video/wayland/SDL_waylandwindow.c [hunk 23]
```diff
@@ -448,8 +489,105 @@ static const struct xdg_toplevel_listener toplevel_listener_xdg = {
...
+        window->flags |= SDL_WINDOW_INPUT_FOCUS;
+    }
+    else {
+        window->flags &= ~SDL_WINDOW_INPUT_FOCUS;
+    }
+
+    /* The fullscreen flag is already set my some other entity when 'SDL_SetWindowFullscreen'
+     * is called, but we will set it here again in case the compositor requests fullscreen.
+     */
+    if (window_state & LIBDECOR_WINDOW_STATE_FULLSCREEN) {
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandwindow.c:543]: This should probably replicate what we do in xdg-shell, but tbh I don't fully recall why the xdg-shell fullscreen behavior is written the way it is... may need to look at the revision history for that.

File: src/video/wayland/SDL_waylandwindow.c [hunk 24]
```diff
@@ -448,8 +489,105 @@ static const struct xdg_toplevel_listener toplevel_listener_xdg = {
...
+    if (wind->sdlwindow->flags & SDL_WINDOW_OPENGL) {
+        SDL_GL_SwapWindow(wind->sdlwindow);
+    }
+    else if (wind->sdlwindow->flags & SDL_WINDOW_VULKAN) {
+        wl_surface_commit(wind->surface);
+    }
+    else {
+        wl_surface_commit(wind->surface);
+    }
+}
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandwindow.c:583]: Should this be like the eglSwapBuffers workaround we have for xdg-shell? Wasn't sure if this was the libdecor equivalent of that function or if this is something different entirely. Either way the SwapWindow call is a bit scary since it sounds like this could be executed mid-frame, which would look pretty bad (if not just outright crash depending on when it happens).

**Review by flibitijibibo — CHANGES_REQUESTED** [review]
The patchset looks pretty good at this point, it really only comes down to the callbacks and whether or not we need to replicate the xdg-shell callbacks there (maximized/restored we definitely want, fullscreen and commit I'm not 100% sure).

File: src/video/wayland/SDL_waylandwindow.c (hunk 24 above)
Comment (christianrauch) [reply src/video/wayland/SDL_waylandwindow.c:585]: libdecor invokes `decoration_frame_commit` when it needs the toplevel surface to commit its state so that the compositor updates the toplevel surface and its subsurfaces (i.e. the decoration subsurfaces). This is required, when the visual of the decorations change, e.g. when the mouse-over changes the button colour or when the client sets a new title.

If the client commits the toplevel anyway (e.g. an `eglSwapBuffers` will do that), then this would not be required. But in general, libdecor needs a way to tell the client that the decoration visuals changed and the client has to commit its toplevel.

Doing it this way is the naive version as it may commit a partial toplevel state. Better would be to synchronise this with the main loop. Ideas?

File: src/video/wayland/SDL_waylandwindow.c (hunk 23 above)
Comment (christianrauch) [reply src/video/wayland/SDL_waylandwindow.c:545]: You mean calling `SetFullscreen` in `handle_configure_xdg_toplevel`? That should not be required. The window flags are already set and `libdecor_frame_commit` will take care of setting the right decoration state. The rest is then just that the client redraws the toplevel content at the new fullscreen dimension.

If you see issues with setting the fullscreen mode, let me know.

Comment (flibitijibibo) [reply src/video/wayland/SDL_waylandwindow.c:549]: Will do - I should probably git blame to see why the other backends do the toggle, I'm still not sure _how_ it would desync like that and we have other workarounds that we're planning to remove soon, so it could be a bogus fix like the others too.

Comment (flibitijibibo) [reply src/video/wayland/SDL_waylandwindow.c:549]: Found the commit: https://github.com/libsdl-org/SDL/commit/19236b462a8af09670c9fd5490cea293d3fc2b75

So apparently it's to accommodate minimize on focus loss? I think?

File: src/video/wayland/SDL_waylandwindow.c [hunk 25]
```diff
@@ -448,8 +491,109 @@ static const struct xdg_toplevel_listener toplevel_listener_xdg = {
...
+
+    /* The fullscreen flag is already set my some other entity when 'SDL_SetWindowFullscreen'
+     * is called, but we will set it here again in case the compositor requests fullscreen.
+     */
+    if (window_state & LIBDECOR_WINDOW_STATE_FULLSCREEN) {
+        window->flags |= SDL_WINDOW_FULLSCREEN;
+    }
+    else {
+        window->flags &= ~SDL_WINDOW_FULLSCREEN;
+    }
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandwindow.c:554]: Redid this to match xdg-shell and fix bugs related to redundancy, which caused events to not fire.

```suggestion
   /* Always send maximized/restored/focus events; if the event is redundant it will
     * automatically be discarded (see src/events/SDL_windowevents.c).
     *
     * No, we do not get minimize events from libdecor.
     */
    if (!(window_state & LIBDECOR_WINDOW_STATE_FULLSCREEN)) {
        window->flags &= ~SDL_WINDOW_FULLSCREEN_DESKTOP;
        SDL_SendWindowEvent(window,
                            (window_state & LIBDECOR_WINDOW_STATE_MAXIMIZED) ?
                                SDL_WINDOWEVENT_MAXIMIZED :
                                SDL_WINDOWEVENT_RESTORED,
                            0, 0);
    } else {
        window->flags |= SDL_WINDOW_FULLSCREEN_DESKTOP;
    }
    SDL_SendWindowEvent(window,
                        (window_state & LIBDECOR_WINDOW_STATE_ACTIVE) ?
                            SDL_WINDOWEVENT_FOCUS_GAINED :
                            SDL_WINDOWEVENT_FOCUS_LOST,
                        0, 0);
```

**Review by flibitijibibo — CHANGES_REQUESTED** [review]
A quick redo of the window events.

**Review by flibitijibibo — APPROVED** [review]
Latest seems to cover everything again. Still dunno about the GL path for decoration_frame_commit but if everything's still running at 60 then it's probably fine. Once libdecor and GNOME are ready to test again I'll give it another go!

File: src/video/wayland/SDL_waylandwindow.c (hunk 23 above)
Comment (cgutman) [reply src/video/wayland/SDL_waylandwindow.c]: I did it to correctly return to full-screen after the user unminimizes the application (on Mutter, at least). IIRC, without that, it will be restored to windowed mode rather than returning to full-screen mode.

File: src/video/wayland/SDL_waylandwindow.c [hunk 26]
```diff
@@ -102,6 +129,24 @@ SetFullscreen(SDL_Window *window, struct wl_output *output)
      */
     CommitMinMaxDimensions(window);
 
+#ifdef HAVE_LIBDECOR_H
+    if (viddata->shell.libdecor) {
+        if (wind->shell_surface.libdecor.frame == NULL) {
+            return; /* Can't do anything yet, wait for ShowWindow */
+        }
+        if (output) {
+            if (!(window->flags & SDL_WINDOW_RESIZABLE)) {
```
Comment (cgutman) [inline src/video/wayland/SDL_waylandwindow.c:138]: This should be `if (window->flags & SDL_WINDOW_RESIZABLE)` right?

File: src/video/wayland/SDL_waylandwindow.c [hunk 27]
```diff
@@ -102,6 +129,24 @@ SetFullscreen(SDL_Window *window, struct wl_output *output)
...
+                libdecor_frame_set_capabilities(wind->shell_surface.libdecor.frame, LIBDECOR_ACTION_RESIZE);
```
Comment (cgutman) [inline src/video/wayland/SDL_waylandwindow.c:139]: IIUC you need to set `LIBDECOR_ACTION_RESIZE` before entry into full-screen (even if the window was not configured to be resizable by the user). When you un-fullscreen, you unset `LIBDECOR_ACTION_RESIZE` if the window was not meant to be resizable.

It may be worth a comment to that effect, because setting `LIBDECOR_ACTION_RESIZE` when `!(window->flags & SDL_WINDOW_RESIZABLE)` seems like a mistake on first reading.

File: src/video/wayland/SDL_waylandwindow.c [hunk 28]
```diff
@@ -898,7 +1080,24 @@ Wayland_SetWindowBordered(_THIS, SDL_Window * window, SDL_bool bordered)
...
+        }
+        if (resizable) {
+            libdecor_frame_set_capabilities(wind->shell_surface.libdecor.frame, LIBDECOR_ACTION_RESIZE);
+        } else {
+            libdecor_frame_unset_capabilities(wind->shell_surface.libdecor.frame, LIBDECOR_ACTION_RESIZE);
+        }
+    } else
+#endif
+    {
+        CommitMinMaxDimensions(window);
```
Comment (cgutman) [inline src/video/wayland/SDL_waylandwindow.c:1099]: You still need to call `CommitMinMaxDimensions()` even in the libdecor case, no?

If minimum/maximum size changes were made while the window was not resizable, then min/max size as far as libdecor is concerned will currently be set to ` window->w` and `window->h`, rather than the appropriate `window->min_*` and `window->max_*` values.

File: src/video/wayland/SDL_waylandwindow.c (hunk 23 above)
Comment (flibitijibibo) [reply src/video/wayland/SDL_waylandwindow.c]: Ah, this is a good point - we should check this again with SDL_VIDEO_MINIMIZE_ON_LOST_FOCUS=1 with both xdg-shell and libdecor. If it's no longer necessary it can go in the 2.0.18 removal pile.

Comment (cgutman) [reply src/video/wayland/SDL_waylandwindow.c]: In my case, I called `SDL_MinimizeWindow()` when a certain key combo is pressed. It wasn't SDL_VIDEO_MINIMIZE_ON_LOST_FOCUS=1 that was minimizing on my behalf.

File: src/video/wayland/SDL_waylandwindow.c [hunk 29]
```diff
@@ -448,8 +491,102 @@ static const struct xdg_toplevel_listener toplevel_listener_xdg = {
...
+    if (!(window_state & LIBDECOR_WINDOW_STATE_FULLSCREEN)) {
+        window->flags &= ~SDL_WINDOW_FULLSCREEN_DESKTOP;
+        SDL_SendWindowEvent(window,
+                            (window_state & LIBDECOR_WINDOW_STATE_MAXIMIZED) ?
+                                SDL_WINDOWEVENT_MAXIMIZED :
+                                SDL_WINDOWEVENT_RESTORED,
+                            0, 0);
+    } else {
+        window->flags |= SDL_WINDOW_FULLSCREEN_DESKTOP;
+    }
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandwindow.c:542]: I was able to confirm that @cgutman's fullscreen fix is still required for xdg-shell and is also required for libdecor, both on GNOME and Plasma. This patch takes care of everything, tested with SOR4 using a wedged-in key to test SDL_MinimizeWindow:

```suggestion
    if (window_state & LIBDECOR_WINDOW_STATE_FULLSCREEN) {
        window->flags |= SDL_WINDOW_FULLSCREEN_DESKTOP;
    } else {
        if (window->flags & SDL_WINDOW_FULLSCREEN_DESKTOP) {
            /* We might need to re-enter fullscreen after being restored from minimized */
            SDL_WaylandOutputData *driverdata = (SDL_WaylandOutputData *) SDL_GetDisplayForWindow(window)->driverdata;
            SetFullscreen(window, driverdata->output);
        } else {
            SDL_SendWindowEvent(window,
                                (window_state & LIBDECOR_WINDOW_STATE_MAXIMIZED) ?
                                    SDL_WINDOWEVENT_MAXIMIZED :
                                    SDL_WINDOWEVENT_RESTORED,
                                0, 0);
        }
    }
```

File: src/video/wayland/SDL_waylandwindow.c [hunk 30]
```diff
@@ -448,8 +491,102 @@ static const struct xdg_toplevel_listener toplevel_listener_xdg = {
...
+
+    if (wind->sdlwindow->flags & SDL_WINDOW_OPENGL) {
+        SDL_GL_SwapWindow(wind->sdlwindow);
+    }
+    else if (wind->sdlwindow->flags & SDL_WINDOW_VULKAN) {
+        wl_surface_commit(wind->surface);
+    }
+    else {
+        wl_surface_commit(wind->surface);
+    }
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandwindow.c:581]: Minor style fix:
```suggestion
    if (wind->sdlwindow->flags & SDL_WINDOW_OPENGL) {
        SDL_GL_SwapWindow(wind->sdlwindow);
    } else {
        wl_surface_commit(wind->surface);
    }
```

File: src/video/wayland/SDL_waylandwindow.c (hunk 28 above)
Comment (flibitijibibo) [reply src/video/wayland/SDL_waylandwindow.c:1099]: Agreed, if not the full function call we at least need to set window->max_w/h here, but it'd probably be better to call CommitMinMaxDimensions here for maximum safety.

**Review by flibitijibibo — CHANGES_REQUESTED** [review]
Did a quick test of the fullscreen stuff with Streets of Rage 4, found a couple more things but everything else seems okay!

File: src/video/wayland/SDL_waylandwindow.c (hunk 30 above)
Comment (christianrauch) [reply src/video/wayland/SDL_waylandwindow.c]: Hm, this removed the case for `SDL_WINDOW_VULKAN`? This was required for Capsized I think. Not sure if the original issue now disappeared through a different change.

Comment (christianrauch) [reply src/video/wayland/SDL_waylandwindow.c]: Ah, never mind. You just combined the two cases. I left it this way in case there is a "proper way" in Vulkan to force a surface update.

File: src/video/wayland/SDL_waylandwindow.c (hunk 29 above)
Comment (christianrauch) [reply src/video/wayland/SDL_waylandwindow.c]: It seems that after this, I am getting fullscreen issues with Capsized again. The SDL demos and Capsized used to work with the state before this, including transitioning between fullscreen and floating mode.

@flibitijibibo Can you confirm that you see the Capsized issues again?

Comment (flibitijibibo) [reply src/video/wayland/SDL_waylandwindow.c]: It looks like there's a bug somewhere in libdecor - it's claiming fullscreen state when it's not, possibly vice versa. The easiest test is to set the game to fullscreen and simply alt-tab, it will shrink to windowed mode even though it should still be in fullscreen mode (just in the background instead of in front). This appears to be unique to libdecor, and the configure callback we get on alt-tab claims that fullscreen is the current state when it is not. Interestingly, even if I shove a SetFullscreen call into the `LIBDECOR_WINDOW_STATE_FULLSCREEN` path it still doesn't work.

Aside from that it seems exactly as broken and inconsistent as it was before on my PC, except for resizable windows where this is now working correctly (SOR4 is the go-to example).

Comment (christianrauch) [reply src/video/wayland/SDL_waylandwindow.c]: Well, going straight into fullscreen when starting Capsized always worked. But it does not work after this change.

If I undo this change, the fullscreen mode works again with Capsized. Reading the raw wayland log (WAYLAND_DEBUG=1) I see that `set_fullscreen` is called twice now: Once right after initialisation, and the second time right after the configure event that follows the fullscreen event. That seems wrong.

I think the configure event is a result of requesting fullscreen. The configure event is only to inform the client that the surface properties changed. E.g. it carries the fullscreen flag because the user or compositor requested the fullscreen mode and the server is setting fullscreen mode and informing the client. It is not asking the client to request fullscreen mode again. In the configure callback, we should only update the internal state flags, send out notifications and redraw new content if the size changed. But this should not request the same mode (maximise, fullscreen, ...) again.

Comment (flibitijibibo) [reply src/video/wayland/SDL_waylandwindow.c]: It sounds like everything is really out of sync then - I would double check everything with xdg-shell first just to see what the existing behavior is like. At least on GNOME 40 fullscreen seems okay (minus the alt tab behavior).

Comment (christianrauch) [reply src/video/wayland/SDL_waylandwindow.c]: An initial test with xdg-shell shows that the min/max limits are not recognised so that the window will be resizeable. You can check this by pressing Alt+Space, e.g.with the `testscale` example, and see that the "Maximise" option is available. With libdecor this is greyed out (as it should) because the window is defined as non-maximisable. Taking these limits into account make it harder to switch between modes (floating, maximised, fullscreen).

In any case, I don't think there is a requirement to mimic the xdg-shell code paths. Both ways should be close to the X11 behaviour, minus all the things that are intentionally not possible with Wayland (e.g. setting the window position). That may involve different code paths.

Comment (flibitijibibo) [reply src/video/wayland/SDL_waylandwindow.c]: > In any case, I don't think there is a requirement to mimic the xdg-shell code paths. Both ways should be close to the X11 behaviour, minus all the things that are intentionally not possible with Wayland (e.g. setting the window position). That may involve different code paths.

This is true. I suppose at this point I would add SDL_MinimizeWindow during fullscreen to the list of tests, @cgutman may have one but I just shoved it into a local FNA build. Alt-tabbing back should return it to fullscreen mode.

**Comment by christianrauch** [comment]
@flibitijibibo I noticed that Capsized, for getting a surface with the size of the full screen, initially resizes the window to my full screen size instead of directly requesting the fullscreen mode. That means it initially calls `Wayland_SetWindowSize` with 1366 x 768 and afterwards calls `Wayland_SetWindowFullscreen` multiple times.
And just before going into the floating mode, it calls `Wayland_SetWindowFullscreen` yet again and sets the window size to the desired floating dimensions, while the fullscreen flags are set.

This all looks quite supsisious. Why are you not just using the fullscreen and un-fullscreen API? I am not sure if we have to support clients that call API in random order. Can you provide a minimal example in pure SDL that defines the desired behaviour and produces the issues you see? It would be useful to have a set of tests in SDL that are expected to work for different sequences of SDL API calls. After all, the sequence of functions calls is also part of the API.

File: src/video/wayland/SDL_waylandwindow.c (hunk 29 above)
Comment (christianrauch) [reply src/video/wayland/SDL_waylandwindow.c]: The patch removed the unsetting of the fullscreen flag via ` window->flags &= ~SDL_WINDOW_FULLSCREEN_DESKTOP;`. This caused the wrong fullscreen mode.

**Comment by slouken** [comment]
> This all looks quite supsisious. Why are you not just using the fullscreen and un-fullscreen API? I am not sure if we have to support clients that call API in random order. Can you provide a minimal example in pure SDL that defines the desired behaviour and produces the issues you see? It would be useful to have a set of tests in SDL that are expected to work for different sequences of SDL API calls. After all, the sequence of functions calls is also part of the API.

The SDL API calls are intended to work in any order unless specifically documented otherwise.

**Comment by flibitijibibo** [comment]
Latest revision on main fixes a tiny batch of things that I found while testing my catalog of games - some of them may actually help with libdecor as there were a few oddities with xdg-shell mode changes that were caught and may help make the libdecor version consistent as well.

**Comment by christianrauch** [comment]
I pushed an additional patch to prevent window resizing when in a fixed state (fullscreen, maximised) while trying to investigate the Capsized fullscreen -> floating issue.

The remaining issue comes from the fact that Capsized "resizes" the floating window to the screen size instead of requesting a fullscreen mode. It then unsets the fullscreen and then sets fullscreen mode. All this happens before the toplevel surface has actually received the first configure event from the Wayland compositor. Usually, you wait for the first configure event from the Wayland compositor and then request a fullscreen mode once. The compositor will then respond with a new configure event that carries the expected toplevel size and its state (fullscreen resolution and fullscreen mode in this case).

`libdecor` tries to be clever and stores the floating state of a window before going into fullscreen or maximised mode, so that when the client unsets fullscreen or maximised (goes back to floating mode) it will provide the client with the floating dimensions it had before. Since Capsized requested to resize the floating window to the fullscreen resolution (1366 x 768 in my case) before actually requesting the fullscreen mode, `libdecor` assumes that this fullscreen resolution is the floating window size. Once you unset the fullscreen mode, it therefore restores to the floating mode at fullscreen resolution. That is, the frame is rendered at fullscreen resolution, but the attached buffer still has the window size (1280 x 720 in my case).
The proper solution to this would be to stop jamming random resize and un/fullscreen requests but use the expected order. A workaround would be to A) either resize again to the desired window size once the window is floating again (i.e. resize to 1280 x 720 once in floating mode), or B) implement the automatic restoring to floating dimensions manually in SDL and override the libdecor behaviour.

On top of this all, the window states managed by Wayland and SDL are completely out of sync. For example, the `window->flags` already has `SDL_WINDOW_FULLSCREEN` set, before the window received its first configure event with the window state from the compositor.

**Comment by flibitijibibo** [comment]
That all sounds about right to me.

On the subject of test cases I ran a _bunch_ of them last week and they all checked out, so we can add to the testing list other than the FNA catalog...

Vulkan+OpenGL:
- Portal 2 (32-bit)
- L4D2 (32-bit)
- Dota 2
- Jackbox Party Pack 7 Steam beta
- Unity 2021 games (don't know any yet)
- Superliminal

OpenGL only:
- Unity 2017+ games (Dream Daddy, Anodyne 2, Later Alligator)
- Baba Is You
- Super Hexagon
- Wonder Boy: The Dragon's Trap
- Eversion
- VVVVVV (source available!)
- Proteus
- They Bleed Pixels
- 5D Chess

Vulkan only:
- Metro Exodus

I haven't checked any Feral games yet but they're probably worth looking at as well, if they don't require X for anything.

File: src/video/wayland/SDL_waylandwindow.c [hunk 31]
```diff
@@ -600,7 +600,13 @@ decoration_frame_close(struct libdecor_frame *frame, void *user_data)
 static void
 decoration_frame_commit(struct libdecor_frame *frame, void *user_data)
 {
-    /* No-op */
+    SDL_WindowData *wind = user_data;
+
+    if (wind->sdlwindow->flags & SDL_WINDOW_OPENGL) {
+        SDL_GL_SwapWindow(wind->sdlwindow);
```
Comment (jadahl) [inline src/video/wayland/SDL_waylandwindow.c:615]: This should probably be something like sending a `SDL_WINDOWEVENT_EXPOSED` (so that the window content gets redrawn), as I think "randomly" calling `eglSwapBuffers()` (which I assume is what this eventually results in) might not be a good idea, as that means potentially swapping to an empty or old buffer.

Comment (christianrauch) [reply src/video/wayland/SDL_waylandwindow.c]: Right, that was actually causing glitches when resizing while updating the title.

**Comment by hyarsan** [comment]
For whatever reason, I keep getting the following error when trying to compile it with `./configure` & `make`:
```C
/home/yari/code/git/SDL/src/video/wayland/SDL_waylandvideo.c: In function 'display_handle_global':
/home/yari/code/git/SDL/src/video/wayland/SDL_waylandvideo.c:470:25: error: 'struct <anonymous>' has no member named 'libdecor'
  470 |     } else if (!d->shell.libdecor &&
      |                         ^
/home/yari/code/git/SDL/src/video/wayland/SDL_waylandvideo.c:474:25: error: 'struct <anonymous>' has no member named 'libdecor'
  474 |     } else if (!d->shell.libdecor &&
      |                         ^
/home/yari/code/git/SDL/src/video/wayland/SDL_waylandvideo.c:478:25: error: 'struct <anonymous>' has no member named 'libdecor'
  478 |     } else if (!d->shell.libdecor &&
      |                         ^
make: *** [Makefile:726: build/SDL_waylandvideo.lo] Error 1
```
I would appreciate being able to test this...

**Comment by christianrauch** [comment]
> For whatever reason, I keep getting the following error when trying to compile it with `./configure` & `make`:

That part was not guarded by `#ifdef HAVE_LIBDECOR_H`. That is fixed now. I pushed an update to this branch and rewrote the history.

> I would appreciate being able to test this...

If you use CMake to build this, then Wayland (`VIDEO_WAYLAND`) and the decorations (`WAYLAND_LIBDECOR`) are enabled by default. Not sure if this is enabled by default with autoconf. But from the commit, I read that you have to provide `--enable-libdecor` to enable this.

**Comment by hyarsan** [comment]
I can't get CMake to find my libdecoration git clone after all the things I've tried... any help please?
It keeps disabling `WAYLAND_LIBDECOR` because it can't find it.

**Comment by christianrauch** [comment]
> I can't get CMake to find my libdecoration git clone after all the things I've tried... any help please?
> It keeps disabling `WAYLAND_LIBDECOR` because it can't find it.

Did you properly install libdecor? According to the documentation at https://gitlab.gnome.org/jadahl/libdecoration, this is:
```
meson build --buildtype release
meson install -C build
```

If you compile this on Ubuntu, you can use my ppa at https://launchpad.net/~christianrauch/+archive/ubuntu/libdecoration and simply install libdecor via `sudo apt install libdecor-dev`.

**Comment by hyarsan** [comment]
I've tried both those commands and the `libdecoration-git` AUR package, but CMake keeps saying:
`WAYLAND_LIBDECOR       (Wanted: ON): OFF`
`CFLAGS="-I/usr/include/libdecor-0.1" cmake ../SDL/` doesn't work as well...
libdecoration and your fork of SDL are both up to date, and I've tried both `decoration` and `decoration_extern` branches.
Why so unlucky? What command or tool do you use for compiling with CMake?

**Comment by sulix** [comment]
FYI: This has a minor behaviour regression compared to the old xdg-shell on KDE/KWin. In particular, if the window is not resizable (i.e. ``SDL_WINDOW_RESIZABLE`` is not set), a maximize button does appear in the title bar. Clicking it doesn't do anything, so it's not actively harmful, but it technically shouldn't be there, and indeed isn't when libdecor is not used.

**Comment by christianrauch** [comment]
> I've tried both those commands and the `libdecoration-git` AUR package, but CMake keeps saying:
> `WAYLAND_LIBDECOR (Wanted: ON): OFF`
> `CFLAGS="-I/usr/include/libdecor-0.1" cmake ../SDL/` doesn't work as well...
> libdecoration and your fork of SDL are both up to date, and I've tried both `decoration` and `decoration_extern` branches.
> Why so unlucky? What command or tool do you use for compiling with CMake?

Have you verified that `libdecor` gets properly installed? You should have a file hierarchy like:
```
/usr/include/libdecor-0.1/libdecor.h
/usr/lib/x86_64-linux-gnu/libdecor-0.1.a
/usr/lib/x86_64-linux-gnu/libdecor-0.1.so
/usr/lib/x86_64-linux-gnu/libdecor/plugins-1/libdecor-cairo.so
/usr/lib/x86_64-linux-gnu/pkgconfig/libdecor-0.1.pc
```

From thereon, CMake should find `libdecor-0.1` via pkg-config. CMake should do this by default. For reference, here is my [CMakeCache.txt](https://github.com/libsdl-org/SDL/files/6769151/CMakeCache.txt).

**Comment by christianrauch** [comment]
> In particular, if the window is not resizable (i.e. `SDL_WINDOW_RESIZABLE` is not set), a maximize button does appear in the title bar. Clicking it doesn't do anything, so it's not actively harmful, but it technically shouldn't be there, and indeed isn't when libdecor is not used.

This button should be greyed out to indicate that it does not have a function. If this is not the case, please open an upsream issue. If you just don't like the style then propose a patch or help with the [GTK plugin](https://gitlab.gnome.org/jadahl/libdecoration/-/merge_requests/43) :-)

**Comment by jadahl** [comment]
> FYI: This has a minor behaviour regression compared to the old xdg-shell on KDE/KWin. In particular, if the window is not resizable (i.e. `SDL_WINDOW_RESIZABLE` is not set), a maximize button does appear in the title bar. Clicking it doesn't do anything, so it's not actively harmful, but it technically shouldn't be there, and indeed isn't when libdecor is not used.

Maybe the 'min/max' that is needed for this isn't communicated to libdecor in this case.

**Comment by sulix** [comment]
I looked a little more into it, and wasn't able to work out the cause. KWin is using server-side decorations, so I'd expect it to behave identically regardless of whether libdecor is being used.

I did find a couple of bugs (I'll try to file and/or fix them in the next day or so) in libdecor related to the plugin's ``frame_get_window_size_for`` incorrectly adding the csd title height when server-side decorations are used. This didn't fix the maximize button appearing, though. A cursory look at ``WAYLAND_DEBUG=1`` showed they both were setting ``xdg_toplevel.set_min_size(640, 480)`` and ``xdg_toplevel.set_max_size(640, 480)`` (with the aforementioned bugs fixed), so maybe it's a timing/ordering thing.

**Comment by flibitijibibo** [comment]
The maximize button in KWin is a bit hit-and-miss, I found that the only way to get it to really behave is to create the decorations well after the window has been configured:

https://github.com/libsdl-org/SDL/commit/efbb6ff9d70e791d755c9ece95f248d1055b10ab

That part I wouldn't worry about for now, I'm pretty sure it's a KWin bug but I never got enough information to file a report.

**Comment by sulix** [comment]
Yeah, ``libdecor`` definitely seems to create the decorations immediately.

I've filed a bug with KDE — it does seem that this should work. I don't have enough information to make it a particularly useful report, but maybe the KWin folks will have a better idea:
https://bugs.kde.org/show_bug.cgi?id=439578

That being said, I wouldn't object to there being a workaround for this in libdecor if it's easy to do, as buggy versions of KDE might hang around for a while. Of course, it didn't look like it was trivial to workaround from my experiments…

I've also sent a fix for the few coordinate issues I found in libdecor:
https://gitlab.gnome.org/jadahl/libdecoration/-/merge_requests/65

**Comment by sulix** [comment]
> I've filed a bug with KDE — it does seem that this should work. I don't have enough information to make it a particularly useful report, but maybe the KWin folks will have a better idea:
> https://bugs.kde.org/show_bug.cgi?id=439578

This bug is now fixed in upstream KWin, and the maximize button now is correctly hidden with libdecor if I run it against the latest KWin git. The fix should be in KDE Plasma 5.23.

**Comment by smcv** [comment]
> The SDL Debian package is still using the autoconf build script

If CMake has become the preferred build system, we can move to CMake (not for Debian 11, which is in hard freeze, but certainly for Debian 12). `INSTALL.txt` currently reads as though Autotools is preferred and CMake is an alternative: is this still accurate?

For packages that have more than one build system, we usually keep using the one that seemed like it was recommended at the time we first packaged it, unless the upstream maintainer tells us that it has been deprecated and recommends that redistributors move to a replacement. For example, when GLib deprecated Autotools and started recommending Meson, they announced that in the release notes and we switched; but GTK 3 has Autotools and Meson in parallel with no particular recommendation of which one is considered better, so we have continued to use Autotools.

**Comment by christianrauch** [comment]
@icculus @flibitijibibo @smcv An initial "0.1" release of `libdecor` is imminent. We are currently trying to figure out a versioning scheme for the so files (https://gitlab.gnome.org/jadahl/libdecor/-/merge_requests/71, cc @jadahl) and would like to get some feedback/recommendation on how versioning and linking of versioned so files are done in SDL and Debian. We basically want to make sure that we 1) do not accidentally break the ABI/API of a linked so file but also 2) want to be able to update a so-file with ABI/API compatible bugfixes etc. without SDL requiring to relink libdecor so that distributions could provide an update to libdecor without breakage.

**Comment by jadahl** [comment]
Just tagged 0.1.0: https://gitlab.gnome.org/jadahl/libdecor/-/releases/0.1.0 will start packaging this for Fedora.

**Comment by Conan-Kudo** [comment]
@jadahl Ping me on Matrix/IRC with the review request and I'll take it on (if I haven't seen it yet).

**Comment by jadahl** [comment]
> @jadahl Ping me on Matrix/IRC with the review request and I'll take it on (if I haven't seen it yet).

Will do!

**Comment by flibitijibibo** [comment]
I'm unable to spend any more time on this, but the versioning scheme seems fine to me (really all we care about is that `libdecor-0.so.0` will always be there when the package is available) and the only concerns left on our end are still listed in the files tab as review comments (I think I only saw 3?).

Once those are addressed and the build files are updated for the official naming system, this is good for final review.

File: src/video/wayland/SDL_waylandwindow.c (hunk 28 above)
Comment (christianrauch) [reply src/video/wayland/SDL_waylandwindow.c:1265]: Removing the `LIBDECOR_ACTION_RESIZE` capability will already cause setting the min/max limits to the current content dimensions (as represented within libdecor). `CommitMinMaxDimensions` will also set the min/max limits, but those used by SDL. So I don't think we should set min/max limits twice.

File: src/video/wayland/SDL_waylandwindow.c (hunk 23 above)
Comment (christianrauch) [reply src/video/wayland/SDL_waylandwindow.c:568]: I am totally lost here. We already do a `SetFullscreen(window, driverdata->output);` in the else block here. Could you summarise what is missing here and how this shows up as a bug?

**Comment by christianrauch** [comment]
I added the fixed version `0.1.0` to the CI script and updated the library name to `libdecor-0`.

@smcv Could you help me with getting `libdecor` uploaded into the Debian package archive? I mean not the current stable archive, but the unstable archive that is going to become Debian 12 eventually and from which Ubuntu and other downstream distros fork their packages from. I have a [daily libdecor ppa](https://launchpad.net/~christianrauch/+archive/ubuntu/libdecoration) for Ubuntu 20.04 but I still need someone to help me in adopting this for Debian and with the sufficient upload rights.

File: src/video/wayland/SDL_waylandwindow.c (hunk 23 above)
Comment (flibitijibibo) [reply src/video/wayland/SDL_waylandwindow.c:568]: Just realized:

```
        window->flags &= ~SDL_WINDOW_FULLSCREEN;
         if (window->flags & SDL_WINDOW_FULLSCREEN) {
```

This will never trip, right? The first line needs to be cut, other than that I think we're all set.

File: src/video/wayland/SDL_waylandwindow.c (hunk 28 above)
Comment (flibitijibibo) [reply src/video/wayland/SDL_waylandwindow.c:1265]: This part is just an unfortunate API redundancy in libdecor - if resizability was inferred from min/max we could just reuse the same code path, but from what it sounds like we're instead expected to let libdecor do this work for us. It's not great, but if that's a responsibility libdecor wants, so be it... this can be resolved.

File: src/video/wayland/SDL_waylandwindow.h [hunk 32]
```diff
@@ -106,6 +116,7 @@ extern void Wayland_SetWindowSize(_THIS, SDL_Window * window);
 extern void Wayland_SetWindowMinimumSize(_THIS, SDL_Window * window);
 extern void Wayland_SetWindowMaximumSize(_THIS, SDL_Window * window);
 extern int Wayland_SetWindowModalFor(_THIS, SDL_Window * modal_window, SDL_Window * parent_window);
+extern int Wayland_GetWindowBordersSize(_THIS, SDL_Window * window, int *top, int *left, int *bottom, int *right);
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandwindow.h:119]: This ended up being a flop, so it can be removed entirely until it gets added some other time.

File: configure.ac [hunk 33]
```diff
@@ -2766,6 +2766,44 @@ CheckFcitx()
...
+        if test x$video_libdecor = xyes; then
+            EXTRA_CFLAGS="$EXTRA_CFLAGS `$PKG_CONFIG --cflags libdecor-0`"
+            AC_DEFINE(HAVE_LIBDECOR_H, 1, [ ])
+
+            AC_ARG_ENABLE(libdecor-shared,
+[AS_HELP_STRING([--enable-libdecor-shared], [dynamically load libdecor [default=yes]])],
+                          , enable_libdecor_shared=yes)
+
+            dnl FIXME: ABI FREEZE! decor_lib=[`find_lib "libdecor-0.so.*" "" | sed 's/.*\/\(.*\)/\1/; q'`]
+            decor_lib=libdecor-0.so
```
Comment (flibitijibibo) [inline configure.ac:2790]: ABI's frozen, this can now be reverted.

Comment (christianrauch) [reply configure.ac]: Ok, changed that to ``decor_lib=[`find_lib "libdecor-0.so.*" "" | sed 's/.*\/\(.*\)/\1/; q'`]``.

**Comment by Conan-Kudo** [comment]
@flibitijibibo @icculus @christianrauch @jadahl: `libdecor-0.1.0` will be available in Fedora 34 with this evening's (midnight UTC) updates push: https://bodhi.fedoraproject.org/updates/FEDORA-2021-d19281207d

File: src/video/wayland/SDL_waylandwindow.c [hunk 34]
```diff
@@ -483,8 +528,100 @@ static const struct xdg_toplevel_listener toplevel_listener_xdg = {
...
+
+   /* Always send maximized/restored/focus events; if the event is redundant it will
+     * automatically be discarded (see src/events/SDL_windowevents.c).
+     *
+     * No, we do not get minimize events from libdecor.
+     */
+    if (window_state & LIBDECOR_WINDOW_STATE_FULLSCREEN) {
+        window->flags |= SDL_WINDOW_FULLSCREEN;
+    } else {
+        window->flags &= ~SDL_WINDOW_FULLSCREEN;
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandwindow.c:573]: This line should be deleted, otherwise the first if block will never execute.

**Review by flibitijibibo — CHANGES_REQUESTED** [review]
As far as I'm concerned this one line is the only blocker left - once it's cut this is good enough for upstream.

File: src/video/wayland/SDL_waylandwindow.c (hunk 34 above)
Comment (christianrauch) [reply src/video/wayland/SDL_waylandwindow.c]: I undid the change that caused this line to be placed there, it is now at the end of this else block. As far as I understand, the else block still has to unset the `SDL_WINDOW_FULLSCREEN` flag, since the libdecor window state does not contain `LIBDECOR_WINDOW_STATE_FULLSCREEN` (i.e. the decorations are not in fullscreen mode) and this has to be propagated to SDL.

File: src/video/wayland/SDL_waylandwindow.c (hunk 23 above)
Comment (christianrauch) [reply src/video/wayland/SDL_waylandwindow.c:570]: This is fixed now.

File: src/video/wayland/SDL_waylandwindow.c (hunk 34 above)
Comment (flibitijibibo) [reply src/video/wayland/SDL_waylandwindow.c]: Makes sense to me!

**Review by flibitijibibo — APPROVED** [review]
Okay, that covers everything I saw on SDL's end - if anything pops up I suspect it will be a libdecor issue. @icculus, @slouken, this is ready for final review.

**Comment by sezero** [comment]
In configure.ac, `CheckLibDecor` should be called from within `CheckWayland` 
if wayland is found and enabled - unless I'm missing something.  Is the following
patch OK? (I didn't move CheckLibDecor before CheckWayland for a simple view
in here - will do so if this is OK.)
```diff
diff --git a/configure.ac b/configure.ac
index 615048e..c4839be 100644
--- a/configure.ac
+++ b/configure.ac
@@ -1595,6 +1595,8 @@ CheckWayland()
                 SUMMARY_video="${SUMMARY_video} wayland"
             fi
             have_video=yes
+
+            CheckLibDecor
         fi
     fi
 }
@@ -3609,7 +3611,6 @@ case "$host" in
         CheckInotify
         CheckIBus
         CheckFcitx
-        CheckLibDecor
         case $ARCH in
           linux)
               CheckInputKD
```

**Comment by flibitijibibo** [comment]
I put CheckLibDecor in there only because it was with the other Linux-y checks, this change makes sense to me!

**Comment by sezero** [comment]
OK, pushed https://github.com/libsdl-org/SDL/commit/9bcb5e7b94663c09525de9d615b6fd530e2d6f47 for it.
