### PR TITLE
GPU: Prefer D3D12 over Vulkan when available

### LINKED ISSUE #14564: GPU: Prefer D3D12 on Windows
The D3D12 backend is stable and it's probably time to prefer it on Windows. Driver quality is much higher and vendors have a bad habit of introducing horrible driver regressions on Windows with Vulkan. We can probably get this in for 3.4.0.

### PR DESCRIPTION
**Pull request by thatcosmonaut**
Defines the order of GPU backend preference by platform. 

On Windows, we prefer D3D12, on Apple we prefer Metal, on Android we prefer Vulkan (really it's the only possible option), and on Unix/BSD we prefer Vulkan. On all other platforms we use the default preference order of Private -> Metal -> Vulkan -> D3D12. 

Resolves #14564

### CODE REVIEW

**Comment by flibitijibibo** [comment]
Should we just take the current array and move D3D12 to the top?

**Comment by thatcosmonaut** [comment]
I'm concerned about the situation where D3D12 is enabled on Linux, say via vkd3d.

**Comment by flibitijibibo** [comment]
We don't have that set up at the moment - the WSI would have to be redone for that to be an option, and even then we can add a quick override like we have for D3D11 in FNA3D.

**Comment by slouken** [comment]
Yeah, this seems like overkill. Let's just reorder the backends for now.

**Comment by thatcosmonaut** [comment]
OK, works for me.

File: src/gpu/SDL_gpu.c [hunk 1]
```diff
@@ -626,8 +626,9 @@ static const SDL_GPUBootstrap * SDL_GPUSelectBackend(SDL_PropertiesID props)
         return NULL;
     }
 
+    // Iterate preferred backends and pick the first available one
```
Comment (flibitijibibo) [inline src/gpu/SDL_gpu.c]:
```suggestion
```

File: src/gpu/SDL_gpu.c [hunk 2]
```diff
@@ -626,8 +626,9 @@ static const SDL_GPUBootstrap * SDL_GPUSelectBackend(SDL_PropertiesID props)
...
     for (i = 0; backends[i]; i += 1) {
-        if (backends[i]->PrepareDriver(_this, props)) {
+        if (backends[i] != NULL && backends[i]->PrepareDriver(_this, props)) {
```
Comment (flibitijibibo) [inline src/gpu/SDL_gpu.c]:
```suggestion
        if (backends[i]->PrepareDriver(_this, props)) {
```
