### PR TITLE
x11: Don't poll the map state when the window was unmapped and border…

### LINKED ISSUE #14655: `SDL_WINDOW_FULLSCREEN_DESKTOP | SDL_WINDOW_BORDERLESS` hangs on Openbox
## Environment

Fresh install of Arch Linux on a Framework i7-1165G7 mainboard with LightDM configured to autologin to Openbox.

Using the Arch package of SDL3 3.2.28-1.

## Steps to Reproduce

Call `SDL_CreateWindow()` with flags `SDL_WINDOW_FULLSCREEN_DESKTOP | SDL_WINDOW_BORDERLESS`, then call `SDL_CreateRenderer()`.

This can be seen in Flex Launcher here: https://github.com/complexlogic/flex-launcher/blob/master/src/launcher.c#L224

## Actual Behaviour

SDL gets stuck in an infinite loop in `X11_SetWindowBordered()` in these four lines:

https://github.com/libsdl-org/SDL/blob/de642c8890fbbd34080feddfdb6e358056a4f6f6/src/video/x11/SDL_x11window.c#L1474-L1477

`attr.map_state` remains `IsUnmapped` and never becomes `IsViewable`. The app and X server max out a CPU core each.

Here's the relevant stack trace from gdb:

```
#8  0x00007fffed0fdaa1 in poll_for_response (dpy=dpy@entry=0x5555555a2990) at /usr/src/debug/libx11/libX11-1.8.12/src/xcb_io.c:310
#9  0x00007fffed1038e5 in _XReply (dpy=dpy@entry=0x5555555a2990, rep=rep@entry=0x7fffffffdf50, extra=extra@entry=0, discard=discard@entry=1) at /usr/src/debug/libx11/libX11-1.8.12/src/xcb_io.c:721
#10 0x00007fffed103c57 in XSync (dpy=0x5555555a2990, discard=0) at /usr/src/debug/libx11/libX11-1.8.12/src/Sync.c:44
#11 0x00007fffed3781bb in X11_SetWindowBordered (_this=<optimized out>, window=0x5555555cc7f0, bordered=<optimized out>) at /usr/src/debug/sdl3/SDL3-3.2.28/src/video/x11/SDL_x11window.c:1460
#12 0x00007fffed373d84 in X11_DispatchEvent (_this=_this@entry=0x5555555a4620, xevent=xevent@entry=0x7fffffffe360) at /usr/src/debug/sdl3/SDL3-3.2.28/src/video/x11/SDL_x11events.c:1888
#13 0x00007fffed374507 in X11_PumpEvents (_this=0x5555555a4620) at /usr/src/debug/sdl3/SDL3-3.2.28/src/video/x11/SDL_x11events.c:2176
#14 0x00007fffed378ed2 in X11_HideWindow (_this=0x5555555a4620, window=0x5555555cc7f0) at /usr/src/debug/sdl3/SDL3-3.2.28/src/video/x11/SDL_x11window.c:1653
#15 0x00007fffed339581 in SDL_HideWindow_REAL (window=0x5555555cc7f0) at /usr/src/debug/sdl3/SDL3-3.2.28/src/video/SDL_video.c:3322
#16 SDL_HideWindow_REAL (window=0x5555555cc7f0) at /usr/src/debug/sdl3/SDL3-3.2.28/src/video/SDL_video.c:3297
#17 0x00007fffed33c6f2 in SDL_RecreateWindow (window=0x5555555cc7f0, flags=1555) at /usr/src/debug/sdl3/SDL3-3.2.28/src/video/SDL_video.c:2639
#18 0x00007fffed294180 in GL_CreateRenderer (renderer=0x55555560e690, window=0x5555555cc7f0, create_props=9) at /usr/src/debug/sdl3/SDL3-3.2.28/src/render/opengl/SDL_render_gl.c:1656
#19 0x00007fffed27ddde in SDL_CreateRendererWithProperties_REAL (props=props@entry=9) at /usr/src/debug/sdl3/SDL3-3.2.28/src/render/SDL_render.c:1037
#20 0x00007fffed27dfc7 in SDL_CreateRenderer_REAL (window=0x5555555cc7f0, name=0x0) at /usr/src/debug/sdl3/SDL3-3.2.28/src/render/SDL_render.c:1166
#21 0x00007ffff7e15bd9 in SDL_CreateRenderer_REAL (window=0x5555555cc7f0, idx=<optimized out>, flags=6) at /usr/src/debug/sdl2-compat/sdl2-compat-2.32.60/src/sdl2_compat.c:5933
#22 0x0000555555557d07 in create_window () at /home/nick/flex-launcher/src/launcher.c:260
#23 0x000055555555a8da in main (argc=1, argv=0x7fffffffe9e8) at /home/nick/flex-launcher/src/launcher.c:1277
```

## Expected Behaviour

SDL should not go into an infinite loop no matter what the program does. It should either handle the combination of flags safely or reject it with an error.

## Workarounds

Removing `SDL_WINDOW_BORDERLESS` fixes the problem.

## Notes

It seems to me that the `SDL_WINDOW_BORDERLESS` flag is redundant here; `SDL_WINDOW_FULLSCREEN_DESKTOP` already means windowed (borderless) fullscreen, as opposed to `SDL_WINDOW_FULLSCREEN` which means exclusive fullscreen. So I've also put up a pull request to remove the flag from Flex Launcher.

Nevertheless, an infinite loop is clearly not how SDL should handle this. It would seem reasonable to me to just ignore `SDL_WINDOW_BORDERLESS` if `SDL_WINDOW_FULLSCREEN_DESKTOP` is specified, unless I'm misunderstanding what these flags are supposed to do. If these flags are incompatible, this should at least be documented, and SDL should print a warning or something.

Flex Launcher hasn't changed in a while and Openbox is the recommended installation so I wonder if this is a recent regression in SDL. I didn't bother to test older SDL versions but I can if you want. If this is the case, probably the old behaviour should be restored to maintain backward compatibility.

### PR DESCRIPTION
**Pull request by Kontrabant**
…s are toggled

An event flush while a window is being hidden may try to toggle the window borders. Don't poll the mapping state when toggling borders if the window is in the process of being hidden, or the window may already be unmapped, and the wait loop will hang forever.

Fixes #14655

### CODE REVIEW

File: src/video/x11/SDL_x11window.c [hunk 1]
```diff
@@ -1453,8 +1453,8 @@ bool X11_SetWindowModal(SDL_VideoDevice *_this, SDL_Window *window, bool modal)
 
 void X11_SetWindowBordered(SDL_VideoDevice *_this, SDL_Window *window, bool bordered)
 {
-    const bool focused = (window->flags & SDL_WINDOW_INPUT_FOCUS) ? true : false;
-    const bool visible = (!(window->flags & SDL_WINDOW_HIDDEN)) ? true : false;
+    const bool focused = !!(window->flags & SDL_WINDOW_INPUT_FOCUS);
```
Comment (slouken) [inline src/video/x11/SDL_x11window.c]:
```suggestion
    const bool focused = ((window->flags & SDL_WINDOW_INPUT_FOCUS) != 0);
```

Comment (slouken) [reply src/video/x11/SDL_x11window.c]: I know the `!!` bool conversion is handy, but we typically use the more verbose if test in SDL.

Comment (Kontrabant) [reply src/video/x11/SDL_x11window.c]: Fixed.

**Comment by Kontrabant** [comment]
Cherry-picking to 3.2.x as well.
