### PR TITLE
streamline cursor clipping logic on windows

### LINKED ISSUE #7890: Cursor not constrained to window when using `SDL_SetRelativeMouseMode` and another game is running
https://github.com/libsdl-org/SDL/blob/fb0c3197e0e4696551822815bdce0e187a0b06fc/include/SDL3/SDL_mouse.h#L200-L217

> the mouse position is constrained to the window

When using relative mode, I would expect the cursor to be constrained to the window. But it appears this is not the case on windows.

## Repro steps

1. Run `testwm.exe`, I'm using `testwm.exe  --resizable --geometry 1150x900 --title testwm.exe` to have a bigger window for convenience
2. Press <kbd>Ctrl</kbd>+<kbd>R</kbd> to enable relative mode
3. Move the mouse around, and notice that it can exit out of the window
   - note that `MOUSE_FOCUS` window flag will remain set, even if the mouse is outside the window (unlike when not using relative mode)

https://github.com/libsdl-org/SDL/assets/16479013/138af15f-e31b-44cc-89c1-a6a03b689675

I'm using [PowerToys Mouse pointer Crosshairs](https://learn.microsoft.com/en-us/windows/powertoys/mouse-utilities#mouse-pointer-crosshairs) to show where the actual OS mouse position is. Maybe this can aid debugging of this issue.

## Environment
- latest SDL3 `main`: 4d23eaf81e6918deb7521e4b81bb83545c92097f
- Windows 11 22H2 (OS Build 22621.1848)
- World of Tanks running in the background

Edit: the bug seems to only happen if [World of Tanks](https://worldoftanks.eu/) is open in the background. Could this invalidate the issue?

### PR DESCRIPTION
**Pull request by expikr**
This commit does the following:
- add logic in the `WM_MOUSEMOVE` case of the Window to conditionally call `WIN_UpdateClipCursor` upon receiving cursor motion if SDL is expecting the mouse to be clipped in some way (Fixes #7890)
- remove Windows-specific periodic refresh of cursor clipping and its `SDL_HINT_MOUSE_RELATIVE_CLIP_INTERVAL` hint (superceded by the above bullet point)
- streamline the processing logic within `WIN_UpdateClipCursor` for better readability of each branch, and avoid calling the Platform API until it is absolutely necessary.
- move `relative_mouse_center` field from Windows-specific per-window `SDL_WindowData` to the global `SDL_Mouse` struct, and the corresponding hint callbacks to `SDL_mouse.c` instead of `SDL_windowswindow.c`

relevant commits:

https://github.com/libsdl-org/SDL/commit/e56f05bac15cbab5198a0921f084460aa21b5bae (apr 2024)
https://github.com/libsdl-org/SDL/commit/6c962177272c6a2ce684e4298b40c25ebdd1ac74 (mar 2024)
https://github.com/libsdl-org/SDL/commit/ab5351f5d6578206db5ee8784a9cfa18a19728ae (mar 2024)
https://github.com/libsdl-org/SDL/commit/50203d58b3a87defd5cfebc26232a3da50e1a32a (dec 2020)
https://github.com/libsdl-org/SDL/commit/44f50c647ed4a9fe376ec6423a198367702407fd (jun 2020)
https://github.com/libsdl-org/SDL/commit/55b24b93b406d8213e7eaa7c0b319f138225c9c9 (sep 2018)

### CODE REVIEW

File: src/video/windows/SDL_windowsevents.c [hunk 1]
```diff
@@ -1140,11 +1140,24 @@ LRESULT CALLBACK WIN_WindowProc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lPara
...
-        if (!data->videodata->raw_mouse_enabled) {
+        int lparam_x_client = GET_X_LPARAM(lParam);
+        int lparam_y_client = GET_Y_LPARAM(lParam);
+        if (data->videodata->raw_mouse_enabled && SDL_GetMouse()->relative_mode_clip_interval > 0) {         
+            RECT rect = data->cursor_clipped_rect;
+            if (!WIN_IsRectEmpty(&rect)) {
+                POINT cur = {
+                    .x = lparam_x_client;
+                    .y = lparam_y_client;
+                };
```
Comment (sezero) [inline src/video/windows/SDL_windowsevents.c:1151]: MSVC doesn't seem to like C99 initializers. Suggest changing to:

```c
                POINT cur;
                cur.x = lparam_x_client;
                cur.y = lparam_y_client;
```

File: src/video/windows/SDL_windowsevents.c [hunk 2]
```diff
@@ -1137,7 +1137,8 @@ LRESULT CALLBACK WIN_WindowProc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lPara
                 cur.x = lparam_x_client;
                 cur.y = lparam_y_client;
                 if (ClientToScreen(hwnd, &cur) && (cur.x < rect.left || cur.y < rect.top || cur.x > rect.right || cur.y > rect.bottom)) {
-                     WIN_UpdateClipCursor(data->window);
+                    if (data->skip_update_clipcursor) data->skip_update_clipcursor = false;
```
Comment (sezero) [inline src/video/windows/SDL_windowsevents.c:1140]: What is the point of checking for true before assigning to false?

File: src/video/windows/SDL_windowsevents.c [hunk 3]
```diff
@@ -1126,7 +1126,25 @@ LRESULT CALLBACK WIN_WindowProc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lPara
 
     case WM_MOUSEMOVE:
     {
-        /* SDL_Mouse *mouse = SDL_GetMouse(); */
+        SDL_Mouse *mouse = SDL_GetMouse();
+        int lparam_x_client = GET_X_LPARAM(lParam);
+        int lparam_y_client = GET_Y_LPARAM(lParam);
+
+        if (mouse->relative_mode) {
```
Comment (slouken) [inline src/video/windows/SDL_windowsevents.c:1133]: You probably want to check all of these states, since these are the conditions under which the cursor might be clipped:
```
    if ((mouse->relative_mode || (window->flags & SDL_WINDOW_MOUSE_GRABBED) ||
         (window->mouse_rect.w > 0 && window->mouse_rect.h > 0)) &&
        (window->flags & SDL_WINDOW_INPUT_FOCUS)) {
```
