### PR TITLE
cmake+autotools: add option to enable --Werror

### LINKED ISSUE #6332: SDL should be possible to be built without any Werror
The CMake script currently adds `-Werror=declaration-after-statement`.
It should be possible to not add this arg to avoid unexpected build errors:
e.g. #6330 which was not caught by our GitHub workflows

I propose adding a `SDL_WERROR` CMake option (off by default).
All our CI jobs would then be configured with `-DSDL_WERROR=ON`:

### PR DESCRIPTION
**Pull request by madebr**
- Disable x11 by default on macos/ios
- Add `SDL_WERROR` cmake option to enable/disable `-Werror` (or `/WX` for MSVC).
- Add `--enable-werror` autotools option to enable/disable `-Werror`
- Get rid of all warnings on CI (please review them!!)
- Enable -Werror on CI for relevant platforms

Fixes #6332

### CODE REVIEW

**Comment by slouken** [comment]
I am a little confused. I would expect this to actually turn on `-Werror`, but instead it seems like it just makes it possible to turn off `-Werror=declaration-after-statement`

Isn't there a way to just set the compiler flags used to build SDL when building it as part of a larger project? I would expect us to use that functionality to isolate all of SDL's build options so `-Werror=declaration-after-statement` doesn't affect other modules.

As an aside, I'm totally fine with turning on `-Werror` in CI, if we resolve all the current warnings.

**Comment by madebr** [comment]
> I am a little confused. I would expect this to actually turn on `-Werror`, but instead it seems like it just makes it possible to turn off `-Werror=declaration-after-statement`

Yes that's true.

> Isn't there a way to just set the compiler flags used to build SDL when building it as part of a larger project? I would expect us to use that functionality to isolate all of SDL's build options so `-Werror=declaration-after-statement` doesn't affect other modules.

That is already the case today. Our compile flags don't leak into users' projects.
The reason to add a `SDL_WERROR` option is to be future proof. 

See #6330. Although our CI said everything was okay, OP of that issue was unable to use SDL2.
With the extra option, he would just have to configure with `-DSDL_WERROR=OFF` without requiring a patch.

> As an aside, I'm totally fine with turning on `-Werror` in CI, if we resolve all the current warnings.

Let's make an effort to do this.
Would you add `-Werror` only on CI or everywhere (but "disable-able" through `SDL_WERROR`)?
Or really only on CI?

**Comment by slouken** [comment]
I think we should default it off and enable it only for CI. We don't want developers unable to build because of some warning that their compiler emits that ours doesn't.

File: test/testautomation_stdlib.c [hunk 1]
```diff
@@ -36,6 +35,16 @@ stdlib_strlcpy(void *arg)
   return TEST_COMPLETED;
 }
 
+#if defined(HAVE_WFORMAT) || defined(HAVE_WFORMAT_EXTRA_ARGS)
```
Comment (madebr) [inline test/testautomation_stdlib.c:38]: I chose to "surgically" ignore these format warnings so format warnings in other locations are still reported.

File: configure.ac [hunk 2]
```diff
@@ -1606,6 +1606,49 @@ CheckStackBoundary()
...
+        if test x$have_gcc_werror = xyes; then
+            EXTRA_CFLAGS="$EXTRA_CFLAGS -Werror"
+        fi
+    fi
+}
+
+dnl See if GCC's -Wno-error=deprecated-declarations is supported.
+CheckNoErrorDeprecatedDeclarationsWerror()
+{
+    AC_MSG_CHECKING(for GCC -Werror option)
```
Comment (sezero) [inline configure.ac:1636]: Wrong informational message

File: test/testgeometry.c [hunk 3]
```diff
@@ -27,7 +27,7 @@ static SDLTest_CommonState *state;
 static SDL_bool use_texture = SDL_FALSE;
 static SDL_Texture **sprites;
 static SDL_BlendMode blendMode = SDL_BLENDMODE_NONE;
-static double angle = 0.0;
+static float angle = 0.0;
```
Comment (sezero) [inline test/testgeometry.c:30]: While you are there, change value to `0.0f` ?

**Comment by sezero** [comment]
Here is something for watcom makefiles:
```diff
diff --git a/Makefile.os2 b/Makefile.os2
index b9096c9..76b2b39 100644
--- a/Makefile.os2
+++ b/Makefile.os2
@@ -11,2 +11,4 @@
 # wmake -f Makefile.os2 HIDAPI=1
+#
+# To error out upon warnings: wmake -f Makefile.os2 ENABLE_WERROR=1
 
@@ -42,2 +44,5 @@ CFLAGS = -bt=os2 -d0 -q -bm -5s -fp5 -fpi87 -sg -oeatxhn -ei
 CFLAGS+= -wx
+!ifeq ENABLE_WERROR 1
+CFLAGS+= -we
+!endif
 # newer OpenWatcom versions enable W303 by default
diff --git a/Makefile.w32 b/Makefile.w32
index 22ec0cd..68c3a37 100644
--- a/Makefile.w32
+++ b/Makefile.w32
@@ -2,2 +2,4 @@
 # wmake -f Makefile.w32
+#
+# To error out upon warnings: wmake -f Makefile.w32 ENABLE_WERROR=1
 
@@ -28,2 +30,5 @@ CFLAGS = -bt=nt -d0 -q -bm -5s -fp5 -fpi87 -sg -oeatxhn -ei
 CFLAGS+= -wx
+!ifeq ENABLE_WERROR 1
+CFLAGS+= -we
+!endif
 # newer OpenWatcom versions enable W303 by default
diff --git a/test/Makefile.os2 b/test/Makefile.os2
index 75aaeed..ee66409 100644
--- a/test/Makefile.os2
+++ b/test/Makefile.os2
@@ -2,2 +2,4 @@
 # wmake -f Makefile.os2
+#
+# To error out upon warnings: wmake -f Makefile.os2 ENABLE_WERROR=1
 
@@ -9,2 +11,5 @@ CFLAGS = -bt=os2 -d0 -q -bm -5s -fp5 -fpi87 -sg -oteanbmier -ei
 CFLAGS+= -wx -wcd=303
+!ifeq ENABLE_WERROR 1
+CFLAGS+= -we
+!endif
 
diff --git a/test/Makefile.w32 b/test/Makefile.w32
index 51ca7ea..02e68e8 100644
--- a/test/Makefile.w32
+++ b/test/Makefile.w32
@@ -2,2 +2,4 @@
 # wmake -f Makefile.w32
+#
+# To error out upon warnings: wmake -f Makefile.w32 ENABLE_WERROR=1
 
@@ -9,2 +11,5 @@ CFLAGS = -bt=nt -d0 -q -bm -5s -fp5 -fpi87 -sg -oteanbmier -ei
 CFLAGS+= -wx -wcd=303
+!ifeq ENABLE_WERROR 1
+CFLAGS+= -we
+!endif
 CFLAGS+= -DSDL_MAIN_HANDLED
```

File: test/testgeometry.c (hunk 3 above)
Comment (madebr) [reply test/testgeometry.c]: I just did.

**Comment by madebr** [comment]
@sezero 

Thanks for the watcom patch. Applied in https://github.com/libsdl-org/SDL/pull/6336/commits/72820cf0d800a22061080d0fbb25bf451c7af6fa

File: configure [hunk 4]
```diff
@@ -23458,9 +23458,18 @@ if test ${enable_video_x11+y}
 then :
   enableval=$enable_video_x11;
 else $as_nop
-  enable_video_x11=yes
+  enable_video_x11=maybe
```
Comment (sezero) [inline configure:23543]: This is forcefully disabling x11 for mac: the previous version was better IMO.
We should fix the egl+x11 mess, instead of force-disabling it for mac.

Comment (madebr) [reply configure]: I changed the logic.
You're right. Once #6348 is fixed, this commit can be dropped.

Comment (sezero) [reply configure]: It need not be dropped, but can be reverted to your previous logic which isn't actually bad.

Comment (madebr) [reply configure]: I kind of like the current approach: use the 4th argument of [`AC_ARG_ENABLE`](https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Package-Options.html) to determine the default.

**Comment by slouken** [comment]
These seem fine to me, feel free to merge when ready.

File: configure.ac [hunk 5]
```diff
@@ -1860,8 +1903,15 @@ dnl Find the X11 include and library directories
...
-                  , enable_video_x11=yes)
+[AS_HELP_STRING([--enable-video-x11], [use X11 video driver [default=maybe]])],
+                  ,[
+    enable_video_x11=yes
+    case "$host" in
+        *-*-darwin*|*-ios-*)
+            enable_video_x11=no
+            ;;
+    esac])
+
```
Comment (madebr) [inline configure.ac:1914]: I've got a question left about this.
This disables x by default on Macos, and keeps it enabled on other platforms.

Perhaps you prefer to keep it always enabled, and only disable it on CI?

Comment (slouken) [reply configure.ac:1914]: No, it should default to always disabled on macOS.

Comment (madebr) [reply configure.ac:1903]: Then I'll merge it asap.
I just rebased it to make sure no new warnings were introduced in the last few days.
