### PR TITLE
Reimplement wayland message box function with execvp. 

### LINKED ISSUE #4308: Message box data need to be sanitized on Wayland
On Wayland, the message box window is drawn by running a Zenity command with `popen`. All meta-characters will be interpreted by the shell opened by `popen`.

If window message contains a `"`, it will throw an error: `sh: 1: Syntax error: Unterminated quoted string`.
```c
SDL_ShowSimpleMessageBox(SDL_MESSAGEBOX_ERROR, "Error", "test \" test", NULL);
```

Environment variable will be expanded and command run.
```c
SDL_ShowSimpleMessageBox(SDL_MESSAGEBOX_ERROR, "Error", "test `ls $HOME` test", NULL);
```
will expand `$HOME` environment variable, run `ls` and display result in message box window.

### PR DESCRIPTION
**Pull request by meyraud705**
Previous version used `popen` which required to sanitize user-provided text. Not sanitizing text could cause failure if it included a `"` or command injection with \`cmd\`.

This new version launches zenity with `execvp` so we don't need to sanitize. It then reads pressed button from a pipe.

Fix #4308

### CODE REVIEW

File: src/video/wayland/SDL_waylandmessagebox.c [hunk 1]
```diff
@@ -24,142 +24,167 @@
...
+            _exit(EXIT_FAILURE);
+        }
 
-    /* Read the result from stdout */
-    tmp = fgets(output, output_len, process);
-    pclose(process);
-    if ((tmp == NULL) || (*tmp == '\0') || (*tmp == '\n')) {
-        goto end; /* User simply closed the dialog */
-    }
+        argv[argc++] = "--icon-name";
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandmessagebox.c:62]: Should this be `--icon-name=dialog-${type}`?

File: src/video/wayland/SDL_waylandmessagebox.c [hunk 2]
```diff
@@ -24,142 +24,167 @@
 #if SDL_VIDEO_DRIVER_WAYLAND
 
 #include "SDL.h"
-#include <stdlib.h> /* popen/pclose/fgets */
+#include <stdlib.h> /* fgets */
+#include <stdio.h>
+#include <unistd.h>
+#include <sys/wait.h>
+#include <errno.h>
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandmessagebox.c:31]:
```suggestion
#include <stdlib.h> /* fgets */
#include <stdio.h> /* FILE, STDOUT_FILENO, fdopen, fclose */
#include <unistd.h> /* pid_t, pipe, fork, close, dup2, execvp, _exit, EXIT_FAILURE */
#include <sys/wait.h> /* waitpid, WIFEXITED, WEXITSTATUS */
#include <string.h> /* strerr */
#include <errno.h>
```

File: src/video/wayland/SDL_waylandmessagebox.c [hunk 3]
```diff
@@ -24,142 +24,167 @@
...
+        switch (messageboxdata->flags) {
+        case SDL_MESSAGEBOX_ERROR:
+            argv[argc++] = "error";
+            break;
+        case SDL_MESSAGEBOX_WARNING:
+            argv[argc++] = "warning";
+            break;
+        case SDL_MESSAGEBOX_INFORMATION:
+        default:
+            argv[argc++] = "information";
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandmessagebox.c:72]:
```suggestion
            argv[argc++] = "dialog-error";
            break;
        case SDL_MESSAGEBOX_WARNING:
            argv[argc++] = "dialog-warning";
            break;
        case SDL_MESSAGEBOX_INFORMATION:
        default:
            argv[argc++] = "dialog-information";
```

File: src/video/wayland/SDL_waylandmessagebox.c [hunk 4]
```diff
@@ -24,142 +24,167 @@
...
+            } else {
+                argv[argc++] = "--extra-button=\"\"";
             }
         }
+        argv[argc] = NULL;
+
+        /* const casting argv is fine:
+         * https://pubs.opengroup.org/onlinepubs/9699919799/functions/fexecve.html -> rational
+         */
+        execvp("zenity", argv);
```
Comment (flibitijibibo) [inline src/video/wayland/SDL_waylandmessagebox.c:103]:
```suggestion
        execvp("zenity", (char **)argv);
```

**Review by flibitijibibo — CHANGES_REQUESTED** [review]
With these changes I was able to replicate the old messagebox implementation without getting any compiler warnings. Once this stuff is applied it should be good to go!

**Review by flibitijibibo — APPROVED** [review]
This is now good to go. Sam, Ryan, this one is urgent because the current version allows ACE using the system shell.
