### PR TITLE
[SDL2] Fixed PS2 joystick analog sticks not enabled

### LINKED ISSUE #14813: [PS2] Analog Stick Not Working
We recently started porting [Chocolate Quake](https://github.com/Henrique194/chocolate-quake) to the PS2 platform and noticed that the analog sticks are not working. It appears that SDL never emits axis events when the analog sticks are moved. After discussing this with the PCSX2 developers, it seems this may be related to the absence of a `padSetMainMode` call, meaning the analog sticks are never properly enabled.

### PR DESCRIPTION
**Pull request by Henrique194**
## Description

SDL was not configuring the joystick in DualShock mode, which caused the analog sticks to never be enabled.

## Existing Issue(s)

Closes #14813

### CODE REVIEW

File: src/joystick/ps2/SDL_sysjoystick.c [hunk 1]
```diff
@@ -191,6 +191,66 @@ static SDL_JoystickID PS2_JoystickGetDeviceInstanceID(int device_index)
...
+    do {
+        state = padGetState(port, slot);
+    } while ((state != PAD_STATE_STABLE) && (state != PAD_STATE_FINDCTP1));
+}
+
+static void PS2_InitializePad(int port, int slot)
+{
+    int modes;
+    int i;
+    int actuators;
```
Comment (sezero) [inline src/joystick/ps2/SDL_sysjoystick.c]: `actuators` isn't used and is resulting in the CI build failure.

Comment (Henrique194) [reply src/joystick/ps2/SDL_sysjoystick.c]: Fixed.

File: src/joystick/ps2/SDL_sysjoystick.c [hunk 2]
```diff
@@ -191,6 +191,65 @@ static SDL_JoystickID PS2_JoystickGetDeviceInstanceID(int device_index)
...
+        return;
+    }
+
+    // When using MMODE_LOCK, user cant change mode with Select button
+    padSetMainMode(port, slot, PAD_MMODE_DUALSHOCK, PAD_MMODE_LOCK);
+
+    PS2_WaitPadReady(port, slot);
+    padEnterPressMode(port, slot);
+
+    PS2_WaitPadReady(port, slot);
```
Comment (fjtrujy) [inline src/joystick/ps2/SDL_sysjoystick.c:239]: Why do we have `PS2_WaitPadReady` that many times?

Comment (slouken) [reply src/joystick/ps2/SDL_sysjoystick.c:239]: @Henrique194, can you respond here?

Comment (Henrique194) [reply src/joystick/ps2/SDL_sysjoystick.c:239]: @fjtrujy @slouken
I followed the [sample code](https://github.com/ps2dev/ps2sdk/blob/19c09ec1a3a50a12ac615a27bb66fbc9570ac7cd/ee/rpc/pad/samples/pad/pad.c#L147) available in libpad. The first wait is necessary because otherwise we would try to set the mode before the controller is ready to be accessed. I will see whether removing the other waits has any impact.

**Comment by slouken** [comment]
Merged, thanks!
