### PR TITLE
asyncio: Added async i/o APIs.

### LINKED ISSUE #1374: Asynchronous file I/O
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2014-02-24 01:55:02 +0000, Nathaniel Fries wrote:

> Currently, file RWops are blocking and synchronous (just like what's provided by the C FILE* and C++ fstream). This is all fine in good for non-interactive programs and initialization-time loading. But most applications of SDL are interactive, and many are games and media players, which need to read from the harddisk while remaining interactive.
> 
> Because file RWops are blocking (take control away from the main thread), reading too much data from the hard disk on the main thread makes programs non-interactive. This leads to messy solutions like creating another thread just to load data ( "Main thread renders loading animation while background thread uploads whole level along with textures. In fact I did notice that this takes slightly longer than doing everything in main but user experience is much better with main thread still operational, showing anims and gameplay tips.
> ": http://forums.libsdl.org/viewtopic.php?t=9897 ).
> 
> So, I request the addition of asynchronous I/O features to SDL.
> 
> POSIX non-blocking I/O is simple: pass the flag O_NONBLOCK to open(), and all calls to read/write will return without waiting for the disk (the return value will be the number of bytes written).
> Asynchronous file I/O was added to POSIX in 2001. Most versions of the interface do not work on sockets. See: http://pubs.opengroup.org/onlinepubs/009604599/basedefs/aio.h.html
> Non-blocking I/O can be multiplexed using select() in order to reduce the number of read()/write() syscalls: http://pubs.opengroup.org/onlinepubs/7908799/xsh/select.html
> With non-blocking I/O, SDL will have to maintain the total number of bytes written in order to determine when an I/O operation has completed.
> 
> Windows does not support synchronous (in order) non-blocking I/O. Instead it only supports asynchronous (out-of-order, or in Windows terms, overlapped) I/O. This is implemented by passing FILE_FLAG_OVERLAPPED to CreateFile and maintaining an OVERLAPPED structure for each I/O operation. See: http://msdn.microsoft.com/en-us/library/windows/desktop/aa365683%28v=vs.85%29.aspx
> There are several ways to get indications of I/O completions using asynchronous I/O. One is to associate a kernel event with the OVERLAPPED structure passed to ReadFile/WriteFile. Another is to call GetOverlappedResult.
> But because an application that has real use of asynchronous I/O is probably performing operations on multiple files, it would be better to reduce the number of syscalls. This means using Read/WriteFileEx and entering an alertable wait state in the main loop (a new API function, SDL_PumpIO, for other threads; and probably inside SDL_PumpEvents) to execute I/O completion handlers. See: http://msdn.microsoft.com/en-us/library/windows/desktop/aa363772%28v=vs.85%29.aspx
> 
> It is entirely possible to implement this using the existing SDL_RWops interface. But an asynchronous SDL_RWop would break old code using SDL_RWops by its nature.
> 
> Instead, I recommend an additional API just for asynchronous file ops. While this could certainly be done as a third party library, I feel that it would be a better fit for the main library, using the SDL event queue to report completed/failed async ops with a new event.

On 2017-08-14 20:42:19 +0000, Sam Lantinga wrote:

> This is a good idea for SDL 2.1. Do you have a proposed first pass implementation?

### PR DESCRIPTION
**Pull request by icculus**
This is still in-progress, but I've been heads-down on this for awhile, so I'm putting it in a draft PR.

This implements an async i/o API, and a "generic" backend that implements it with a pool of SDL threads that can block on synchronous SDL_IOStreams. This is likely "good enough" for most things, and it's usable on everything but single-threaded Emscripten builds.

The downsides to the generic backend:

- While i/o happens in a background thread, you can't do two accesses in the same open file in parallel, because the SDL_IOStream needs to seek for each, so file position state would race. There's a mutex protecting it per-opened-file. Separate files (even two opens of the same file) can work in parallel, though.
- It can't cancel in-flight i/o; if a read/write is happening, it can't be stopped before it completes. In practice, this isn't likely a big deal.
- There are limited threads for i/o (currently `(SDL_GetCPUCount * 2) +1` at most), ~~and it uses the same thread pool that is used for notifying apps that i/o is complete, which is to say if the app uses that callback for heavy processing, until the callback returns, it won't be available for doing more i/o. In practice, you'd have to have lots of read/writes that also have very heavy callbacks before you'd see bottlenecks, I think, but system-specific APIs can just get all the i/o cooking separately regardless of callback weight.~~  **(EDIT: this isn't true now. The generic backend uses up to 8 threads for i/o, but they are only limited by disk bandwidth, and no longer have to worry about the app hogging them in a callback.)**
- ~~It can't ever work for single-threaded Emscripten, because it needs threads.~~ **(EDIT: it works in single-threaded in Emscripten now...it's just synchronous, because Emscripten's filesystem API is synchronous and almost always just a memcpy from MEMFS anyhow).**

This would benefit from a Windows backend, that uses win32 IO Completion Ports, to solve these limitations. Linux can use io_uring if that's generally available at this point. Emscripten ~~could use actual async file APIs and run stuff between mainloop iterations if single-threaded~~ **(EDIT: see above)**, or hand off from there to the usual thread pool if not. I'm sure Mac/iOS/Android have a thing, too, but the ABI wouldn't change, so we can deal with those later.

Fixes #1374.

### CODE REVIEW

**Comment by icculus** [comment]
This is one of those "you can't please everyone" things. I started with a poll interface and was asked to change it to callbacks.

You could just have an array of bools and have the callback set each one to true as pieces finish loading, and each frame check for true instead of DONE...or something like that.

**Comment by slouken** [comment]
This generally looks good. Is there going to be WriteFileAsync()? What's the interaction with storage?

**Comment by nfries88** [comment]
Looks pretty good. Do have some input

> * There are limited threads for i/o (currently `(SDL_GetCPUCount * 2) +1` at most)

While this is probably fine heuristically, I would probably add a hard maximum of 64. There's a lot of people gaming on old workstations that would exceed that cap and be unlikely to benefit from the typical case of I/O on a single drive.

>and it uses the same thread pool that is used for notifying apps that i/o is complete... in practice, you'd have to have lots of read/writes that also have very heavy callbacks before you'd see bottlenecks, I think

this is fine. a note in the documentation that callbacks should try to be brief and forward heavy processing to other threads may be warranted, because many assets do need reasonably heavy processing.

> This would benefit from ... IO Completion Ports ... io_uring ... Emscripten could use actual async file APIs

don't disagree but it might be more straightforward to start with an implementation that can portably share logic. A relatively thin shim over pread/pwrite on the Unix likes and ReadFile/WriteFile on Win32 can enable a single implementation with better characteristics than the generic implementation.

Emscripten would benefit most from its own implementation, IIRC all the libc synchronous I/O actually gets proxied to the main runtime thread in order to simplify handling the promises from the underlying JS interfaces.

>I'm sure Mac/iOS/Android have a thing, too, but the ABI wouldn't change, so we can deal with those later.

Android doesn't have a thing for this.

Mac and iOS have dispatch_io which just doesn't mesh well with this interface (in particular there is no way to supply a read buffer) and is better for sockets than regular files anyway.

**Comment by slouken** [comment]
Crazy thought... do you actually want that many I/O threads? Maybe we should start with one and add a hint that lets applications tune that?

**Comment by nfries88** [comment]
> Crazy thought... do you actually want that many I/O threads? Maybe we should start with one and add a hint that lets applications tune that?

having a fixed number of not enough threads makes the system unusable for many real projects and having a few too many idle threads is always cheaper than creating them on-demand. This is what posix aio implementations generally got wrong and why nobody really uses them for heavy I/O (except for FreeBSD's implementation I guess).

tunability as a range with a heuristic selection within that range might be appropriate. All of the factors that would determine the optimal number of threads for an I/O-busy program are not really statically knowable, but a user could profile their particular I/O pattern across a good variety of machines and come up with a range that might be better than just relying on the heuristic alone.

**Comment by icculus** [comment]
> This generally looks good. Is there going to be WriteFileAsync()? What's the interaction with storage?

LoadFileAsync is useful because it has open the file, figure out how large the file is, allocate memory for it, and read into it. WriteFileAsync would only need to open and write an existing buffer, so it's only saving one step. But we could definitely add it!

Storage just needs an equivalent of LoadFileAsync. On the built-in implementation, it literally will just call SDL_LoadFileAsync. Current thinking was not to implement positional reads/writes at the storage level, but I'm still trying to understand what data in a SDL_Storage interface does when you have a file like Spider-Man 2's New York map, which is presumably dozens of gigabytes.

>  Crazy thought... do you actually want that many I/O threads? Maybe we should start with one and add a hint that lets applications tune that?

Right now it spins threads on-demand if there aren't any idle ones, up to a maximum count, and ones that are idle for more than 30 seconds will start terminating until only one is left (we always keep one around so there isn't a failure case when _no_ threads can start). Until you use async i/o, it won't initialize _anything_ so it doesn't have a resource cost at all until you touch it. The idea being that you likely have a flood of startup loading and then there's not a lot of value in keeping idle threads around.

There's a FIXME to add a hint, and we definitely should tune the defaults in any case.

**Comment by icculus** [comment]
Okay, single-threaded Emscripten support is in, so this is Good Enough to ship and do improvements with system-specific APIs later...but do we really want this callback API?

It forces people deal with locking and worries that they'll clog the thread pool if they don't move quickly enough.

Maybe it would be better if we give them something like:

```c
SDL_GetAsyncResults(&details)
```

Internally we keep a queue of completed tasks, and each call to this returns the next completed one with all the details. You don't poll specific tasks, you just get the next one in the completed list. Call doesn't block, returns false if nothing is ready.

This dramatically simplifies SDL's code and the mental load an app needs to manage. The app can still toss work to a background thread to process the loaded data if they want...but if they just didn't want to block on i/o, they can otherwise still benefit in a single-threaded app.

**Comment by slouken** [comment]
Sure, I buy it, let’s do that instead.

**Comment by slouken** [comment]
The one thing that would be nice is a way to wait for multiple I/O operations to complete. WaitForCompletion(array of operations)

**Comment by slouken** [comment]
You probably want a separate handle for each request. For example if a library does async loading it wants to get its own data separate from the app.

**Comment by nfries88** [comment]
> Internally we keep a queue of completed tasks, and each call to this returns the next completed one with all the details. You don't poll specific tasks, you just get the next one in the completed list. Call doesn't block, returns false if nothing is ready.

As I think Sam was suggesting, allowing for separate completion queues (probably specified when creating an async file object, with NULL refering to some default completion queue) would probably be the most useful form of this approach, since different threads would have different interests. That also conveniently translates very simply to how IOCP and io_uring deal with completions.

**Comment by icculus** [comment]
Okay, this now has queryable tasks and "task groups" and the background thread callbacks are gone.

I'm _super happy_ with how this came out. Here's the category documentation from the new version, which gives the basic idea:

# CategoryIOAsync

SDL offers a way to perform i/o _asynchronously_. This allows an app to read or write files without waiting for data to actually transfer; the functions that request i/o never block while the request is fulfilled.

Instead, the data moves in the background and the app can check for results at their leisure.

This is more complicated that just reading and writing files in a synchronous way, but it can allow for more efficiency, and never having framerate drops as the hard drive catches up, etc.

The general usage pattern for async i/o is:

- Open a file with SDL_IOAsyncFromFile.
- Start i/o tasks to that file with SDL_ReadIOAsync or SDL_WriteIOAsync.
- Later on, use SDL_GetIOAsyncTaskResult to see if the task is finished.
- When your tasks are done, close the file with SDL_CloseIOAsync.

If you want to track several tasks at once, regardless of the order in which they complete:

- Create a task group with SDL_CreateIOAsyncGroup.
- Specify this group when calling SDL_ReadIOAsync or SDL_WriteIOAsync.
- Use SDL_GetIOAsyncGroupResult to see if anything has finished yet.

This all works, without blocking, in a single thread, but one can also use a task group in a background thread and sleep until new results have arrived:

- Call SDL_WaitIOAsyncGroup from one or more threads to efficiently block until new tasks complete.
- When shutting down, call SDL_SignalIOAsyncGroup to unblock sleeping threads despite there being no new tasks completed.

And, of course, to match the synchronous SDL_LoadFile, we offer SDL_LoadFileAsync as a convenience function. This will handle allocating a buffer, slurping in the file data, and null-terminating it; you still get a task handle to check later or add to a task group.

**Comment by slouken** [comment]
> I'm _super happy_ with how this came out. Here's the category documentation from the new version, which gives the basic idea:
 
Nice!

**Comment by jaedan** [comment]
Hi - I was sent this direction because I've been peripherally involved in SDL_Gpu (doing reviews focused on performance and answering questions about PCI and DMA). I happen to build storage APIs professionally though, so looking at this pull request is far more up my alley. I had a really long review I was working on, but the recent changes you've made addressed about 80% of what I was going to say so this will now be much shorter (but still probably long).

I think for now I'll stick to just public API feedback, and maybe I'll post in a few separate posts.

First, I do not think it is possible to implement the API calls that do not require a task group efficiently on Linux. On Linux, your asynchronous I/O choices are either Linux AIO (not to be confused with POSIX AIO) or io_uring. Both of these APIs require you to first create some per-thread context (e.g. a task group) in order to submit I/O. Creating these on demand per-file is expensive and may run into OS-imposed limits on the number of io_urings or aio_contexts available. I strongly suggest that you only expose the APIs that require a task group - it's the only way to get true asynchronous I/O. I've personally made a similar mistake with APIs released 10+ years ago and it was really painful to find my way out of the corner I painted myself into.

Second, opening and closing the file should be asynchronous operations too (and they should be submitted to the task group). These can actually secretly block a long time in some cases. Of course, on many operating systems there isn't an asynchronous open/close option at all, and the implementations there will be blocking. But at least on Linux with io_uring you can asynchronously open and close files, so the API should allow for the best behavior rather than forcing the worst.

More review to follow.

**Comment by icculus** [comment]
(Sorry, I just squashed this down to a single commit right before you posted that; it's all the same stuff, just in one commit.)

I'm skeptical that async opens are worth the API complexity, but I can totally see a close operation blocking while cached writes make their way to disk. I'm nervous about adding the complexity, but let me think on this a little tonight.

As for tasks vs task groups: presumably with io_uring (and Win32 i/o completion ports), we'll have a single internal thread that lives just to deal with moving data from the OS in a single context/completion port to our own task groups that mostly sleeps. If that's not a _terrible_ idea, then it doesn't matter if the app wants to query a single task or a task group, it's just a question of whether they look at a struct directly or shift the head of a linked list of structs before looking at it.

**Comment by icculus** [comment]
(Also, more review is totally welcome at any length you're willing to write, because I'm 100% winging it over here like I know what I'm doing.)

**Comment by jaedan** [comment]
The shift to support "task groups" is an excellent and necessary change. However, I do still have a few pieces of feedback on the group task group design.

1) One major source of overhead in storage APIs is the system calls themselves. The only way to work around this is to batch operations and submit them in a single system call. Some operating systems now have facilities for this (e.g. io_uring, and I think there's something on Windows called ioRing now). But in your API it isn't really clear whether this sort of batching would be allowed. I guess you could make an SDL_ReadIOAsync call simply queue onto the group and then only really submit the operation to the OS in SDL_GetIOAsyncGroupResult, but I think as the functions are named now that isn't clear enough to the user that they need to call SDL_GetIOAsyncGroupResult once to even start the operations. I think you need a separate SDL_QueueReadIOAsync and then an SDL_SubmitIO type of set up.

2) Task groups should *NOT* be thread safe. The whole purpose of io_uring, or Linux aio, or Windows ioRing (and to some extent iocp), or even NVMe multiple submission/completion queues or Linux blk-mq is that you don't need locks. Instead, instruct users to create one task group per thread and use it for every operation on that thread for it's entire duration. This needs to work essentially the same way as SDL_Gpu's command  buffers because the underlying storage hardware happens to work exactly the same way as the underlying GPU hardware in terms of command submission and completion.

3) The name task group indicates to me something lighter weight than what I think this really needs to represent. A task group needs to represent a Linux io_uring, or a Windows iocp, etc. These are not cheap things to create and destroy. In fact, we only want to do it once per thread and at thread start up time, then re-use it. Most of the modern OS APIs call it a "ring" (because it's literally a circular submission ring of commands) or a "queue". I've historically called it an "io_channel".

(More coming)

**Comment by jaedan** [comment]
> As for tasks vs task groups: presumably with io_uring (and Win32 i/o completion ports), we'll have a single internal thread that lives just to deal with moving data from the OS in a single context/completion port to our own task groups that mostly sleeps. If that's not a terrible idea, then it doesn't matter if the app wants to query a single task or a task group, it's just a question of whether they look at a struct directly or shift the head of a linked list of structs before looking at it.

Using a thread is, unequivocally, a terrible idea (sorry, that sounds really harsh and I promise I don't mean it to be, but I've been at this a long time and everyone wants to use a thread). The hardware (and I've helped design NVMe from the very beginning) wants you to create a separate "queue" per thread. The hardware accepts command submissions in parallel (and they're all asynchronous too!). And the operating systems have spent the last decade re-designing themselves to do parallel, asynchronous I/O internally to match the hardware.

You are supposed to create a per-thread "context" (io_uring, aio_context, ioRing, iocp, whatever) at thread start up time, and use that exclusively for the I/O operations you perform on that thread. This will allow for parallel, lockless I/O submission and provide the lowest latency.

**Comment by nfries88** [comment]
> I'm skeptical that async opens are worth the API complexity

I have noticed file open latency before. I've never seen it be significant for a single file, and the many-file usecase is probably covered adequately enough by SDL_LoadFileAsync and perhaps similar composite operations. I'd agree its probably not worth the complexity.

>but I can totally see a close operation blocking while cached writes make their way to disk. I'm nervous about adding the complexity, but let me think on this a little tonight.

An async sync-and-close would be useful for savefiles.

> As for tasks vs task groups: presumably with io_uring (and Win32 i/o completion ports), we'll have a single internal thread that lives just to deal with moving data from the OS in a single context/completion port to our own task groups that mostly sleeps. If that's not a _terrible_ idea, then it doesn't matter if the app wants to query a single task or a task group, it's just a question of whether they look at a struct directly or shift the head of a linked list of structs before looking at it.

Windows will [block inside an Overlapped ReadFile](https://learn.microsoft.com/en-us/previous-versions/troubleshoot/windows/win32/asynchronous-disk-io-synchronous) when the underlying disk driver's queue is full. It's not that hard to hit this with random reads because Windows disk drivers have shallow queues compared to eg Linux. This is unfortunate because other pending reads to the same device might still succeed without blocking by hitting the filesystem cache, and obviously when combined with other uses of Overlapped I/O (eg sockets) that should never block this is even worse. It will also block on Overlapped WriteFile for writes that extend a file, which is a pretty normal thing to happen. Because of this behavior the typical procedure is to still use a threadpool to issue overlapped I/O.

As far as io_uring goes, I definitely agree with jaeden that this would be a suboptimal use of it, but also think that the typical use of a per-thread ring is both needlessly resource-expensive (they are not lightweight objects) and a poor fit for games' logic. A ring wrapped in a mutex for each task group is probably the least bad approach here.

**Comment by slouken** [comment]
We could create a heavy weight async I/O context when a thread first uses the async API. This could be stored in TLS and be automatically cleaned up, so the users get the benefit of that without having to explicitly track things themselves.

It might be worth adding a io_uring and I/O ring implementation to validate that this API works efficiently with those interfaces.

The only thing that affects the ABI is the question of how asynchronous I/O interacts with the storage API, and it's becoming clear that it doesn't. This seems like it's intended as a low level high performance interface to disk files. If that's true, then let's bump this out of the ABI milestone.

**Comment by jaedan** [comment]
> Because of this behavior the typical procedure is to still use a threadpool to issue overlapped I/O.

On Linux for many many years (via Linux aio) and on Windows  [for the last 3](https://learn.microsoft.com/en-us/windows/win32/api/ioringapi/), this is no longer the standard procedure. We shouldn't make the API inefficient on modern operating systems by design, but rather accept the inefficiency only for operating systems with poor asynchronous IO support.

Let's imagine we have a system with a background thread that does the IO processing. This thread may spin while there's IO outstanding for efficiency, but it certainly can't just spin all the time. IO in games is sporadic, so most commonly this thread will be asleep when we next start a burst of IO. So we queue up the operation into the shared queue or ring and then signal the background thread to wake. On most operating systems, thread scheduling latency is only at about 1ms granularity, and even if it reacts instantly just the mechanics of restoring thread state to wake it takes a significant chunk of time. So all of this added time is added to our IO request. But then the underlying SSD will complete the request in 20-100 microseconds most likely. Why would we 10x our latency because of software design? It makes no sense.

> but also think that the typical use of a per-thread ring is both needlessly resource-expensive (they are not lightweight objects) and a poor fit for games' logic

I really can't disagree more on both points. These objects are not cheap to create because they usually do memory allocations and system calls, but actual resource use is very minimal. Usually it's 64 bytes * number of queues entries. And you make one of these per thread that wants to perform IO. If you have true asynchronous IO, then you only need a very limited number of threads in your game that are doing asset loading. We're talking kilobytes of total resources use here.

And regarding a poor fit for game logic, a ring buffer for command submission is a perfect fit for game logic. On each tick you enqueue all your IO operations. At end of tick you submit and check for completions. It cannot be more ideal. It also happens to be exactly how the GPU API works too, and it would be how an optimal networking API would function as well.

**Comment by jaedan** [comment]
> We could create a heavy weight async I/O context when a thread first uses the async API. This could be stored in TLS and be automatically cleaned up, so the users get the benefit of that without having to explicitly track things themselves.

The issue with this approach is the user needs to have some kind of handle to poll once per game tick. If you have a secret async context per thread and many task groups mapped to it, you don't have enough information about whether you've already polled that tick to make the most efficient use of the backing OS APIs. You end up polling too often or not often enough. The only solution I've ever found that really works is to make the async context a visible object in the API.

**Comment by jaedan** [comment]
> The only thing that affects the ABI is the question of how asynchronous I/O interacts with the storage API, and it's becoming clear that it doesn't. 

My primary motivation is having an API that can efficiently load data into the new SDL_GpuTransferBuffers directly, to be shipped over to the GPU. Ideally, this process will perform no CPU-copies of the data at all, and be entirely asynchronous. 

But I'd use it for save files and stuff too.

**Comment by nfries88** [comment]
> > Because of this behavior the typical procedure is to still use a threadpool to issue overlapped I/O.
> 
> On Linux for many many years (via Linux aio) and on Windows [for the last 3](https://learn.microsoft.com/en-us/windows/win32/api/ioringapi/), this is no longer the standard procedure. 

I agree, but SDL supports versions of Windows without IoRing and I was describing the behavior of the specific pre-existing API. 

> On most operating systems, thread scheduling latency is only at about 1ms granularity, and even if it reacts instantly just the mechanics of restoring thread state to wake it takes a significant chunk of time. 

This is sometimes true of scheduler interrupts themselves but not typical of latency following a wake event, [which is usually in the order of microseconds](https://stackoverflow.com/a/71789116/2658887) as long as a CPU is available to run on. 

> Why would we 10x our latency because of software design? It makes no sense.

because the threads that know when we need to start I/O tend to be latency sensitive (trying to hit those framerates) we generally do not want to do processing on them that could be done on another thread, especially when that processing is often more expensive than the I/O itself.

> > but also think that the typical use of a per-thread ring is both needlessly resource-expensive (they are not lightweight objects) and a poor fit for games' logic
> 
> I really can't disagree more on both points. These objects are not cheap to create because they usually do memory allocations and system calls, but actual resource use is very minimal. Usually it's 64 bytes * number of queues entries.

maybe I did overestimate the resource use then.

> And regarding a poor fit for game logic, a ring buffer for command submission is a perfect fit for game logic. On each tick you enqueue all your IO operations. At end of tick you submit and check for completions. It cannot be more ideal. It also happens to be exactly how the GPU API works too, and it would be how an optimal networking API would function as well.

ringbuffers are great for inter-thread communication in games, it's the pattern of a single thread both issuing I/O and dealing with completions that I think is a bad fit and what you seem to be advocating for (see above)

**Comment by icculus** [comment]
Okay, I'm going to think on this a bit and make some decisions.

To be clear, the goal here was to make something that doesn't have to block on i/o, and is _easy to use_, not to make something that moves data through DMA right from the disk to the GPU. If we have to give up some amount of efficiency to make the API pleasant, I'm willing to do that.

Also, I'm deeply worried by the Microsoft document that says overlapped i/o might turn out to be synchronous _if the file is using NTFS compression_, because that more or less makes overlapped i/o no better than just using synchronous i/o from a background thread for my purposes...if that's the state of things, we can just call this thing ready to merge.

**Comment by nfries88** [comment]
> overlapped i/o might turn out to be synchronous _if the file is using NTFS compression_, because that more or less makes overlapped i/o no better than just using synchronous i/o from a background thread for my purposes...

yeah, afaik the Overlapped I/O system just won't use the internal threadpool for anything other than waiting on the I/O itself, and so it blocks and completes synchronously when it needs to do anything else. So there's really no point with files using the transparent encryption or compression functionality. Though it's still probably useful to use Overlapped I/O for concurrent position-independent reads because without the overlapped flag when opening the file, ReadFile and WriteFile will serialize on concurrent accesses because they update the file pointer even with an offset supplied (more unfortunate behavior)

**Comment by jaedan** [comment]
> To be clear, the goal here was to make something that doesn't have to block on i/o, and is easy to use, not to make something that moves data through DMA right from the disk to the GPU. If we have to give up some amount of efficiency to make the API pleasant, I'm willing to do that.

The difference is one additional function call to create the asynchronous I/O context at start up time. Without this, you simply cannot do efficient, lockless, parallel I/O and you'll force all the implementations to spawn background threads and take locks. Is one extra function call such a burden on the user that they'd rather sacrifice performance and efficiency? I would certainly be happy to add the extra 3 lines of code or whatever it'll be to my application.

> Also, I'm deeply worried by the Microsoft document that says overlapped i/o might turn out to be synchronous if the file is using NTFS compression, because that more or less makes overlapped i/o no better than just using synchronous i/o from a background thread for my purposes...if that's the state of things, we can just call this thing ready to merge.

I'm in the camp that overlapped I/O on Windows is, in practice, mostly useless. If you're running on a Windows system without ioRing, I think it should just use the default thread pool implementation. But this doesn't let us off the hook on good API design, because ioRing and io_uring and Linux aio do exist and are effective.

> because the threads that know when we need to start I/O tend to be latency sensitive (trying to hit those framerates) we generally do not want to do processing on them that could be done on another thread, especially when that processing is often more expensive than the I/O itself. Decompression on the CPU is typically about 10x slower than a read from a SSD, I know that the cutting edge is GPU decompression which is also done asynchronously but not everyone is using that.

I'm not advocating that everyone must do their I/O from the game thread. I'm advocating that the API design should not force the back-end implementation to use a thread. Any application remains free to submit I/O and process completions on whatever thread they want. So let's not design an API that forces the inefficient case and instead create one that allows for the efficient case where it is available (Linux, Windows with ioRing support).

**Comment by nfries88** [comment]
> I'm not advocating that everyone must do their I/O from the game thread. I'm advocating that the API design should not force the back-end implementation to use a thread. Any application remains free to submit I/O and process completions on whatever thread they want. So let's not design an API that forces the inefficient case and instead create one that allows for the efficient case where it is available (Linux, Windows with ioRing support).

Providing a thread-safe API across all implementations should be a priority IMO.

with a mutex-guarded ring per task queue there should be no need for background threads in the implementation.

and if you were to only use this task queue on a single thread the overhead should only be a few ns on both ends because Linux's pthread mutexes and Windows' SRWLocks both have an atomic fast-path. It is certainly cheap relative to the generally necessary io_uring_enter syscall. So, at least in my head, an implementation can be made thread-safe without a significant sacrifice to the performance of the single-threaded usecase.

IIRC the submission side of the ring and the completion side of the ring could also be protected by separate mutexes.

**Comment by icculus** [comment]
Okay, I read up on Windows IoRing and io_uring, and @jaedan is probably right that we can make this work without the API getting totally obnoxious.

Here's what I think we should do.

First:

- Most of what we have can stay.
- The "generic" (thread pool for synchronous i/o) backend will always be available, as most platforms will use it either as their primary version, or as a fallback if you're not yet on Windows 11, etc.
- I'm (probably) not writing IoRing or io_uring backends before SDL3 ships; it can be added later, we just need the API in place.

The plan:

- Apps always create a task group for async i/o. This will correspond to an IoRing/io_uring. No querying of single tasks, they'll all go in a group now. While there might be ideal designs (one ring per thread or whatever), this should be safe to do other things, like different parts of an app having its own group, or multiple threads sharing a single ring.
- Apps can pop (shift, really) the latest results without blocking, or block for results from a background thread, like it works now.
- There _will_ be a mutex, so multiple threads can wait on a single group and pick up loaded data to process as available. This doesn't _have_ to be an SDL_Mutex, if the system-level ring can let multiple threads wait on completion and feed an event to only one of the waiters. If an app designs to have different rings in different threads, they'll just never have a contested lock, which is pretty fast in modern times.
- Closing a file needs to become async. Opening I'll probably pass on.

Later:

- We can add APIs to submit multiple tasks at once in a batch, but I'm avoiding that for now.

Questions:

- One of the motivations for task groups is so different pieces of a program (a third-party library, etc) can have their personal set of tasks they care about, and they won't consume other pieces' tasks by accident. I'm assuming it's safe to have two sets of rings in one thread that just coexist, but is this massively wasteful? And if so, what is the proper way to handle this? We could have one ring total, and any call to get/wait will move the completion queue to our higher level abstraction, but if multiple rings make more sense, we can move the appropriate parts of that abstraction into the backends instead.


Anyhow, the tl;dr is that most of what's there is probably good, and some minor changes will future-proof it to work well with IoRing/io_uring later.

**Comment by slouken** [comment]
If we are supporting multiple threads getting back an arbitrary I/O request from a group, we'll need some user data to identify the request. e.g. it came from my data archive, but it was _this_ file and offset, and has _this_ parameters for processing.

**Comment by icculus** [comment]
Yeah, we already have that: file handle, offset, size, userdata.

**Comment by jaedan** [comment]
> I'm (probably) not writing IoRing or io_uring backends before SDL3 ships; it can be added later, we just need the API in place.

Ideally, I will find the time. But my use of SDL is purely for hobbies so I can't make strong commitments. I feel very confident that I could sit down and type this out relatively quickly though. 

> There will be a mutex, so multiple threads can wait on a single group and pick up loaded data to process as available. This doesn't have to be an SDL_Mutex, if the system-level ring can let multiple threads wait on completion and feed an event to only one of the waiters. If an app designs to have different rings in different threads, they'll just never have a contested lock, which is pretty fast in modern times.

I only vote against the lock because if you need the lock you probably designed your application wrong. But an uncontested lock isn't a big enough problem that I'll protest any further. 

> One of the motivations for task groups is so different pieces of a program (a third-party library, etc) can have their personal set of tasks they care about, and they won't consume other pieces' tasks by accident. I'm assuming it's safe to have two sets of rings in one thread that just coexist, but is this massively wasteful?

Making multiple rings on the same thread is perfectly fine. They aren't heavy on resource use.

**Comment by icculus** [comment]
> I only vote against the lock because if you need the lock you probably designed your application wrong. 

Surely there will be apps that want to fire off a bunch of file reads at once then have multiple worker threads wait on a single ring, each picking up a new file to process as the read completes? Even if this reduces throughput, I could totally see an app using that pattern.

**Comment by jaedan** [comment]
> Surely there will be apps that want to fire off a bunch of file reads at once then have multiple worker threads wait on a single ring, each picking up a new file to process as the read completes? Even if this reduces throughput, I could totally see an app using that pattern.

This is one of the few valid things you could do with multiple waiters, and if you need to do a serious CPU unpack/decode step on your assets then it makes sense to shift that off of your game thread and onto a pool. But you could also accomplish this by issuing the IO from the game thread, polling for completions on the game thread, and then farming the decode jobs out to a thread pool. That completely separates the IO code from the decode code, and doesn't require a lock on the ring.

But again, having the lock and a thread safe wait isn't a big deal for me and I'll defer to your judgement on what people want in the API.

**Comment by icculus** [comment]
Okay, what is (hopefully!) the final API is ready to go. I think you'll be pretty happy with it.

The generic threadpool always exists (so even when we have IoRing support, if SDL detects we're not on Windows 11, it can fall back to that). Writing a new backend basically means filling in this:

```c
typedef struct SDL_IOAsyncGroupInterface
{
    bool (*queue_task)(void *userdata, SDL_IOAsyncTask *task);
    void (*cancel_task)(void *userdata, SDL_IOAsyncTask *task);
    SDL_IOAsyncTask * (*get_results)(void *userdata);
    SDL_IOAsyncTask * (*wait_results)(void *userdata, Sint64 timeoutMS);
    void (*signal)(void *userdata);
    void (*destroy)(void *userdata);
} SDL_IOAsyncGroupInterface;
```

That would be an IoRing/io_uring behind that. And then the other interface for files:

```c
typedef struct SDL_IOAsyncInterface
{
    Sint64 (*size)(void *userdata);
    bool (*read)(void *userdata, SDL_IOAsyncTask *task);
    bool (*write)(void *userdata, SDL_IOAsyncTask *task);
    bool (*close)(void *userdata, SDL_IOAsyncTask *task);
    void (*destroy)(void *userdata);
} SDL_IOAsyncInterface;
```

Basically just queues tasks to the ring, but is abstract so it can deal with win32 HANDLEs or Unix file descriptors, etc.

There are some locks at the higher level, but afaict, the new code gets out of the way of any actual I/O Ring as fast as possible.

This PR can merge if we're all happy with it.

File: include/SDL3/SDL_ioasync.h [hunk 1]
```diff
@@ -0,0 +1,500 @@
...
+     misrepresented as being the original software.
+  3. This notice may not be removed or altered from any source distribution.
+*/
+
+/* WIKI CATEGORY: IOAsync */
+
+/**
+ * # CategoryIOAsync
+ *
+ * SDL offers a way to perform i/o _asynchronously_. This allows an app to
```
Comment (slouken) [inline include/SDL3/SDL_ioasync.h:27]: Don't need underscores here

File: include/SDL3/SDL_ioasync.h [hunk 2]
```diff
@@ -0,0 +1,500 @@
...
+ * Instead, the data moves in the background and the app can check for
+ * results at their leisure.
+ *
+ * This is more complicated that just reading and writing files in a
+ * synchronous way, but it can allow for more efficiency, and never having
+ * framerate drops as the hard drive catches up, etc.
+ *
+ * The general usage pattern for async i/o is:
+ *
+ * - Create one or more SDL_IOAsyncGroup.
```
Comment (slouken) [inline include/SDL3/SDL_ioasync.h:40]: I still think we should have some sort of interface for this into SDL_Storage, even if it returns SDL_Unsupported() for now.

File: include/SDL3/SDL_ioasync.h (hunk 1 above)
Comment (slouken) [inline include/SDL3/SDL_ioasync.h:27]:
```suggestion
 * SDL offers a way to perform I/O asynchronously. This allows an app to
```
Also switch i/o to I/O through the rest of this file.

File: include/SDL3/SDL_ioasync.h [hunk 3]
```diff
@@ -0,0 +1,500 @@
...
+ * \returns a pointer to the SDL_IOAsync structure that is created or NULL on
+ *          failure; call SDL_GetError() for more information.
+ *
+ * \since This function is available since SDL 3.0.0.
+ *
+ * \sa SDL_CloseIOAsync
+ * \sa SDL_ReadIOAsync
+ * \sa SDL_WriteIOAsync
+ */
+extern SDL_DECLSPEC SDL_IOAsync * SDLCALL SDL_IOAsyncFromFile(const char *file, const char *mode);
```
Comment (slouken) [inline include/SDL3/SDL_ioasync.h:200]: Do you need to pass the task group in as a parameter? I haven't looked at the IORing API, but it seems like async I/O tasks might not be transferrable between task groups? Or are they?

File: include/SDL3/SDL_ioasync.h [hunk 4]
```diff
@@ -0,0 +1,500 @@
...
+ * \threadsafety It is safe to call this function from any thread.
+ *
+ * \since This function is available since SDL 3.0.0.
+ *
+ * \sa SDL_ReadIOAsync
+ * \sa SDL_CreateIOAsyncGroup
+ * \sa SDL_GetIOAsyncTaskResult
+
+ */
+extern SDL_DECLSPEC SDL_IOAsyncTask * SDLCALL SDL_WriteIOAsync(SDL_IOAsync *ioasync, void *ptr, Uint64 offset, Uint64 size, SDL_IOAsyncGroup *group, void *userdata);
```
Comment (slouken) [inline include/SDL3/SDL_ioasync.h:293]: It seems really odd that each operation could be part of a different group. Do async I/O APIs really work this way?

File: include/SDL3/SDL_ioasync.h [hunk 5]
```diff
@@ -0,0 +1,500 @@
...
+} SDL_IOAsyncResult;
+
+/**
+ * Information about a completed asynchronous i/o request.
+ *
+ * \since This struct is available since SDL 3.0.0.
+ */
+typedef struct SDL_IOAsyncOutcome
+{
+    SDL_IOAsync *ioasync;   /**< what generated this task. This pointer will be invalid if it was closed! */
```
Comment (slouken) [inline include/SDL3/SDL_ioasync.h:119]:
```suggestion
    SDL_IOAsync *ioasync;   /**< what generated this task. This pointer will be NULL if it was closed! */
```

Comment (icculus) [reply include/SDL3/SDL_ioasync.h:119]: It won't be NULL, it'll be the pointer that was valid before closing the file invalidated it...but in case the app is keying off it, we give them the pointer.

File: include/SDL3/SDL_ioasync.h (hunk 4 above)
Comment (icculus) [reply include/SDL3/SDL_ioasync.h:293]: It's not impossible you'd want to have a single packfile with game data, and put all your images in one group and audio in another, and have different code process each, knowing the group only has one type of data or another when it goes to pull from it.

(But I'll defer to @jaedan to say if that's something no one should ever actually do.)

File: include/SDL3/SDL_ioasync.h (hunk 3 above)
Comment (icculus) [reply include/SDL3/SDL_ioasync.h:200]: Individual tasks go in one group and then come out completed, but different tasks from the same file can go in different groups.

File: include/SDL3/SDL_ioasync.h (hunk 1 above)
Comment (icculus) [reply include/SDL3/SDL_ioasync.h]: Fixed in 6e5e55d01c1f9e12626d00881fd8d9661abda8d8.

File: include/SDL3/SDL_ioasync.h (hunk 2 above)
Comment (icculus) [reply include/SDL3/SDL_ioasync.h:40]: What I've learned from this is that these sort of APIs are not going to be implemented by anything in a serious way, so beyond the built-in filesystem Storage being backed by this PR's code, I don't see anyone else implementing this.

Maybe that's enough, though.

File: include/SDL3/SDL_ioasync.h (hunk 4 above)
Comment (slouken) [reply include/SDL3/SDL_ioasync.h:293]: I was more thinking about native async I/O APIs, which I haven't looked at, and I should before questioning your design. :)

**Comment by slouken** [comment]
It might be useful to have an API to query the number of outstanding tasks in a group.

I'm fine with merging this as-is, but we should definitely implement IORing or uring or both before we close this out of the ABI milestone.

File: include/SDL3/SDL_ioasync.h (hunk 4 above)
Comment (icculus) [reply include/SDL3/SDL_ioasync.h:293]: Basically Windows IoRing and Linux io_uring work like more complex versions of this: "take this file handle, do this thing to it, tell me when you're done." On Linux, the operations are literally just a list of syscalls: read, write, etc...but it also works with things like socket connect(), etc. It's kinda wild.

Older APIs _don't_ work like this, but we're just using the generic threadpool for those and I don't expect that to change.

File: src/file/SDL_ioasync.c [hunk 6]
```diff
@@ -0,0 +1,317 @@
...
+    task->ioasync = ioasync;
+    task->type = SDL_IOASYNC_TASK_CLOSE;
+    task->app_userdata = userdata;
+    task->group = group;
+
+    ioasync->closing = task;
+
+    SDL_UnlockMutex(ioasync->lock);
+
+    if (LINKED_LIST_START(ioasync->tasks, ioasync) == NULL) { // no tasks? Queue the close task now.
```
Comment (slouken) [inline src/file/SDL_ioasync.c:176]: Doesn't the lock need to be held while examining and modifying ioasync->tasks?

**Comment by icculus** [comment]
Yeah, I've been extremely handwavey about how to shut the thing down if you still have tasks in flight. I was thinking of adding a reference count to the groups so they don't explode if you destroy them while a task is still in-flight.

Closing files while i/o is still in-flight is okay already though: it'll forbid starting new i/o on a closed file, but it won't attempt to actually close it until all its tasks are done, and then the final destruction doesn't happen until the async close task completes. This was totally worth the effort because an app can just open a file, read a bunch of stuff from it, and then close it immediately, and only deal with the results without keeping the file handle around.

File: src/file/SDL_ioasync.c (hunk 6 above)
Comment (icculus) [reply src/file/SDL_ioasync.c:176]: Whoops, yes, that's a bug.

File: include/SDL3/SDL_ioasync.h (hunk 2 above)
Comment (slouken) [reply include/SDL3/SDL_ioasync.h:40]: Yeah, getting an async interface for title storage is probably important.

File: test/testasyncio.c [hunk 7]
```diff
@@ -0,0 +1,176 @@
...
+#include <SDL3/SDL_main.h>
+#include <SDL3/SDL_test.h>
+#include <SDL3/SDL_test_common.h>
+
+static SDL_Renderer *renderer = NULL;
+static SDL_Texture *texture = NULL;
+static SDL_IOAsyncGroup *group = NULL;
+static SDLTest_CommonState *state = NULL;
+
+SDL_AppResult SDL_AppInit(void **appstate, int argc, char *argv[])
```
Comment (slouken) [inline test/testasyncio.c:23]: Does it make sense to add some testautomation tests to validate parameter checking and invalid operations?

**Comment by slouken** [comment]
> Yeah, I've been extremely handwavey about how to shut the thing down if you still have tasks in flight. I was thinking of adding a reference count to the groups so they don't explode if you destroy them while a task is still in-flight.
> 
> Closing files while i/o is still in-flight is okay already though: it'll forbid starting new i/o on a closed file, but it won't attempt to actually close it until all its tasks are done, and then the final destruction doesn't happen until the async close task completes. This was totally worth the effort because an app can just open a file, read a bunch of stuff from it, and then close it immediately, and only deal with the results without keeping the file handle around.

Destroying a group with tasks in flight should probably block until they complete. Otherwise you might have I/O writing into buffers that could be freed immediately afterwards. This might get tricky with threads involved...

File: src/file/SDL_ioasync.c (hunk 6 above)
Comment (icculus) [reply src/file/SDL_ioasync.c]: Fixed in 91d1484b59f04008712250ea5b142ae87e1fdff8.

**Comment by nfries88** [comment]
a couple of thoughts/questions on the new interface:

1) It doesn't seem like outside code can do anything with SDL_IOAsyncTask anymore, and there's potential room for improvements in some backends by completely removing the public API contract of a stable pointer to SDL_IOAsyncTask. Maybe change the return type of SDL_ReadIOAsync and friends?

2) Is there any reason the iface member of SDL_IOAsync isn't a pointer?

File: include/SDL3/SDL_ioasync.h [hunk 8]
```diff
@@ -0,0 +1,500 @@
...
+ * \sa SDL_ReadIOAsync
+ * \sa SDL_WriteIOAsync
+ */
+typedef struct SDL_IOAsyncTask SDL_IOAsyncTask;
+
+/**
+ * A logical grouping of SDL_IOAsyncTask handles.
+ *
+ * When starting an asynchronous operation, you specify a group for the new
+ * task. A group can be later be asked if any individual task in it has
```
Comment (jaedan) [inline include/SDL3/SDL_ioasync.h:150]: "can be later be asked"

**Comment by icculus** [comment]
> Maybe change the return type of SDL_ReadIOAsync and friends?

To bool (true if it queued a task, false on failure)? My thought is they could use it as a reference key to know which talk is which, but I guess they could do that just as well with their userdata pointer.

File: include/SDL3/SDL_ioasync.h [hunk 9]
```diff
@@ -0,0 +1,500 @@
...
+ *
+ * \since This struct is available since SDL 3.0.0.
+ *
+ * \sa SDL_ReadIOAsync
+ * \sa SDL_WriteIOAsync
+ */
+typedef struct SDL_IOAsyncTask SDL_IOAsyncTask;
+
+/**
+ * A logical grouping of SDL_IOAsyncTask handles.
```
Comment (jaedan) [inline include/SDL3/SDL_ioasync.h:147]: The description here doesn't make it immediately obvious to me that the set of tasks in the group can constantly change. I think part of the problem is the name "group" which makes me think I'm statically taking a set of tasks and grouping them together, rather than using this object as a mechanism to submit tasks.

What if you named it SDL_IOWorkQueue?

**Comment by icculus** [comment]
> Is there any reason the iface member of SDL_IOAsync isn't a pointer?

Because this started from SDL_IOStream, which might have an arbitrary implementation that doesn't stick around, so a copy is necessary...but these are all internal for the async stuff, so I can change that.

File: include/SDL3/SDL_ioasync.h [hunk 10]
```diff
@@ -0,0 +1,500 @@
...
+extern SDL_DECLSPEC SDL_IOAsyncTask * SDLCALL SDL_WriteIOAsync(SDL_IOAsync *ioasync, void *ptr, Uint64 offset, Uint64 size, SDL_IOAsyncGroup *group, void *userdata);
+
+/**
+ * Close and free any allocated resources for an async I/O object.
+ *
+ * Closing a file is _also_ an asynchronous task! If a write failure
+ * were to happen during the closing process, for example, the
+ * task results will report it as usual.
+ *
+ * This function guarantees that the close will happen after any other
```
Comment (jaedan) [inline include/SDL3/SDL_ioasync.h:302]: Does closing guarantee a flush, or could data be left in the page cache? Maybe for games it doesn't matter, but flushing is required to build a save strategy that doesn't corrupt on power failure or OS crash.

File: include/SDL3/SDL_ioasync.h [hunk 11]
```diff
@@ -0,0 +1,500 @@
...
+ *               two threads should not attempt to close the same object.
+ *
+ * \since This function is available since SDL 3.0.0.
+ */
+extern SDL_DECLSPEC SDL_IOAsyncTask * SDLCALL SDL_CloseIOAsync(SDL_IOAsync *ioasync, SDL_IOAsyncGroup *group, void *userdata);
+
+/**
+ * Create a task group for tracking multiple I/O operations.
+ *
+ * An async I/O operation can be assigned to a group when started. The
```
Comment (jaedan) [inline include/SDL3/SDL_ioasync.h:333]: can be assigned -> must be assigned

File: include/SDL3/SDL_ioasync.h (hunk 9 above)
Comment (nfries88) [reply include/SDL3/SDL_ioasync.h:147]: Calling it a queue is more appropriate IMO too. Though the purpose for the queue is really more about the completions than the work itself. Maybe SDL_IOCompletionQueue or just SDL_IOQueue?

Comment (slouken) [reply include/SDL3/SDL_ioasync.h:147]: SDL_AsyncIOTask, SDL_AsyncIOQueue? That makes a certain sense to me.

File: include/SDL3/SDL_ioasync.h (hunk 11 above)
Comment (icculus) [reply include/SDL3/SDL_ioasync.h]: Fixed in 5829b1ff4fb0b9859c0f46e3eb0dc7f4ce5f5b7a.

File: src/dynapi/SDL_dynapi.sym [hunk 12]
```diff
@@ -94,7 +94,7 @@ SDL3_0.0.0 {
     SDL_CreateGPUTexture;
     SDL_CreateGPUTransferBuffer;
     SDL_CreateHapticEffect;
-    SDL_CreateIOAsyncGroup;
+    SDL_CreateIOAsyncQueue;
```
Comment (slouken) [inline src/dynapi/SDL_dynapi.sym:97]: Can we change IOAsync to AsyncIO?

File: include/SDL3/SDL_ioasync.h (hunk 10 above)
Comment (icculus) [reply include/SDL3/SDL_ioasync.h:302]: I'm assuming it implies the same flush that close/fclose/CloseHandle would (which is literally what the generic backend does, but I assume this would be true for IoRing/io_uring, too).

File: include/SDL3/SDL_ioasync.h (hunk 9 above)
Comment (icculus) [reply include/SDL3/SDL_ioasync.h]: In 5829b1ff4fb0b9859c0f46e3eb0dc7f4ce5f5b7a, I just went with SDL_IOAsyncQueue.

File: src/dynapi/SDL_dynapi.sym (hunk 12 above)
Comment (icculus) [reply src/dynapi/SDL_dynapi.sym:97]: Yes, I was just thinking the same thing. This started out as a compliment to SDL_IOStream, but this is it's own thing now, for sure.

File: include/SDL3/SDL_ioasync.h (hunk 8 above)
Comment (icculus) [reply include/SDL3/SDL_ioasync.h]: Fixed in 72991b43b9bda960825f0acd10bd2c4ce88bcbeb.

File: test/testasyncio.c (hunk 7 above)
Comment (icculus) [reply test/testasyncio.c:23]: Probably, but testautomation intimidates the crap out of me.  :)

**Comment by nfries88** [comment]
> > Maybe change the return type of SDL_ReadIOAsync and friends?
> 
> To bool (true if it queued a task, false on failure)? My thought is they could use it as a reference key to know which task is which, but I guess they could do that just as well with their userdata pointer.

bool return makes sense.

idk maybe task identity separate from userdata is very important to some potential users. But if that's the case, could return an integer "ticket" instead.

File: include/SDL3/SDL_ioasync.h (hunk 10 above)
Comment (jaedan) [reply include/SDL3/SDL_ioasync.h:302]: From `man close` on POSIX:

>   A successful close does not guarantee that the data has been successfully saved to disk, as the kernel uses the buffer cache  to defer writes. Typically, filesystems do not flush buffers when a file is closed.  If you need to be sure that the data is physically stored on the underlying disk, use [fsync(2)](https://man7.org/linux/man-pages/man2/fsync.2.html).

You need an asynchronous fsync baked into this close operation for this to really be correct. I think the comment here should say that this operation guarantees all data has been flushed from the operating system caches before it completes - we'll save a lot of developers a lot of headaches around corrupt files during OS crash or power loss.

Comment (nfries88) [reply include/SDL3/SDL_ioasync.h:302]: the flush that fclose/fflush does just flushes the libc stream buffers by calling write/WriteFile, it doesn't ensure that writes buffered by the OS are committed to disk - the C standard really has no concept of OS write buffering.

close and CloseHandle won't ensure that either, you need to explicitly use fsync/FlushFileBuffers if you want this.

Comment (slouken) [reply include/SDL3/SDL_ioasync.h:302]: We should not add fsync to this API. If we want that, it should be something separate that we add for iostream and asyncio

File: include/SDL3/SDL_ioasync.h (hunk 2 above)
Comment (nfries88) [reply include/SDL3/SDL_ioasync.h]: Most cloud storage APIs seem to provide their own async operations out of the box.

File: include/SDL3/SDL_ioasync.h (hunk 10 above)
Comment (nfries88) [reply include/SDL3/SDL_ioasync.h:302]: I just want as good as possible sync-on-close semantics and I believe that's all jaedan wants too.

File: include/SDL3/SDL_ioasync.h (hunk 4 above)
Comment (nfries88) [reply include/SDL3/SDL_ioasync.h]: [Linux aio also has big caveats and limitations that io_uring doesn't.](https://stackoverflow.com/questions/34572559/asynchronous-io-io-submit-latency-in-ubuntu-linux). It works extremely well for specific I/O patterns but it would require some significant shimming to be generally useful, and after that I'm not convinced it would actually outperform a threadpool using normal buffered pread/pwrite.

Comment (nfries88) [reply include/SDL3/SDL_ioasync.h]: > I was more thinking about native async I/O APIs, which I haven't looked at, and I should before questioning your design. :)

the only significant native async API for regular files that requires associating a file with a single context is Windows' IOCP, but it's fairly typical to use a single completion port for all I/O in a process anyway.

File: include/SDL3/SDL_ioasync.h (hunk 10 above)
Comment (jaedan) [reply include/SDL3/SDL_ioasync.h:302]: Yeah for SDL purposes the common use cases are writing config/settings/profiles, and writing out save state. For both of those operations, you need to do the following pattern:

1) asynchronously write out the file data to a temp file
2) asynchronously flush the OS page cache for that file. You don't want to block here, it can take a long time.
3) delete the old file
4) rename the new file to the correct name

Step 2 can be baked into closing the file for simplicity. And step 3 and 4 are usually fast and do not need to be asynchronous (although I won't argue against making it all async).

This whole process doesn't have to necessarily be captured in this API but correct, cross-platform, asynchronous sync-on-close would be extremely valuable. Very few game devs end up getting this right on their own.

**Comment by slouken** [comment]
@icculus, don't merge this yet.

Questions:
* How does this work with the storage system?
* What happens if you try to mix async operations from different providers (cloud storage + local file I/O)
* Do we want a sync close operation?
* How does this map to existing async cloud operations?

There are enough unknowns that I think I want to bump this to 3.x so we have more time to explore and iterate on the API. Having a real world big game test case would be great too. :)

**Comment by icculus** [comment]
> icculus, don't merge this yet.

Yeah, I have all last night's feedback to incorporate first, at the bare minimum.

**Comment by icculus** [comment]
> How does this work with the storage system?

The easiest would be to expose something that puts a task in a specified ~~group~~queue, but the problem is...

> What happens if you try to mix async operations from different providers (cloud storage + local file I/O)

...sooner or later, everything is going to have to land in _whatever_ we're using behind the scenes: a threadpool, or a modern i/o ring, and this is going to be out of the hands of the storage implementation.

So there are some options for Storage:

- call the new public async API behind the scenes; if they're just feeding files on the native filesystem anyhow, so why reinvent the wheel? This would totally work if the only Storage implementations are the ones we provide in SDL itself, but it's a public interface that external code can implement too.
- spin their own threads to offer async data if it's not coming from raw files on a native filesystem. Like, let's say you have a .zip file that we expose as a Storage object. It _could_ just set up loading a single entry from the .zip as an standard async task, but it still needs to uncompress that data before the app can have it, and you're probably going to need a thread for that.
- just return SDL_Unsupported(). This is not necessarily unreasonable. The built-in ones, which just talk to the native filesystem, will just use the new async API behind the scenes, and we don't ever burden other Storage implementations with having to deal with this. They don't have access to the internal interfaces anyhow.
- The Storage async API doesn't _have_ to use the same interfaces, we could have something simpler that doesn't deal with queues, etc. There's an argument for this in that the current storage API doesn't have file handles, or loads that are less than the whole file.

This was why I made a comment the other day about how this doesn't fit into the Storage API anymore and we should maybe go forward without it. I'm totally welcome to opinions and solutions on this, though.

**Comment by icculus** [comment]
> Do we want a sync close operation?

I'm less concerned about the sync concerns on writes[^1], and more concerned about someone wanting to grab a bunch of data from a file, close it, and then end up blocking anyhow because it's waiting for the reads to complete. I like that they can dump the file handle and be done with it and just catch the incoming data whenever it arrives.

[^1]: I'm fine with adding an fsync operation, to this and to SDL_IOStream. But people have been writing save games to disk with fclose() for decades and not had many notable problems. Power can go out whenever, but it usually doesn't, and stuff cached in RAM still writes to disk sooner than later.

File: src/dynapi/SDL_dynapi.sym (hunk 12 above)
Comment (icculus) [reply src/dynapi/SDL_dynapi.sym:97]: Fixed in 9f038d1cedf3ea9a68e962ec572a49f79b7c2bd2.

File: include/SDL3/SDL_ioasync.h (hunk 10 above)
Comment (icculus) [reply include/SDL3/SDL_ioasync.h]: To be pedantic, step 3 shouldn't be done, since the rename is atomic by itself; you end up with either the old data at that name or the new data but never halfway or both.

Which also makes me wonder in this pattern how important fsync actually is, since you'll either have the old data undamaged or the new data correctly in its place, flushing the file cache maybe isn't that important for data integrity here.

**Comment by icculus** [comment]
> Destroying a group with tasks in flight should probably block until they complete. Otherwise you might have I/O writing into buffers that could be freed immediately afterwards. This might get tricky with threads involved...

This is fixed in fe3e170ee72812abfc695115c28f5c9544560946. It now blocks until tasks complete and cleans up everything. The docs already tell you how to deal with background threads that are blocked in SDL_WaitAsyncIOResults, and also make explicit that nothing can safely touch this queue again once the Destroy call begins, even if that call is going to block for awhile.

**Comment by icculus** [comment]
> Because this started from SDL_IOStream, which might have an arbitrary implementation that doesn't stick around, so a copy is necessary...but these are all internal for the async stuff, so I can change that.

This is going to stay like this, we'll likely have to expose these interfaces for external code that wants to implement its own async stuff for SDL_Storage.

File: include/SDL3/SDL_ioasync.h (hunk 10 above)
Comment (jaedan) [reply include/SDL3/SDL_ioasync.h]: But you do need the flush between the writes and the rename because if you don't, you could crash after the rename and be left with a corrupt file.

**Comment by icculus** [comment]
Okay, Sam and I decided this is probably getting bumped from the milestone, so I'll add some notes here about what's still pending, to finish this up later. If I missed something in the comments above, let me know and I'll edit this list.

Hopefully I'll still get this into 3.2.0, but if it slips, we'll add it later.

- Force a sync during close: maybe. Since it's not synchronous, it's not unreasonable, but we'd have to add an fsync method to SDL_IOStream so the generic backend can use it.
- I'm positively allergic to testautomation, but we should attempt to hook this up to it.
- We need a good test case for this in general, some existing game we can slot this into.
- We need to figure out how to make this work with SDL_Storage, which probably means exposing both SDL_AsyncIOInterface and SDL_AsyncIOQueueInterface, telling storage people to implement both if they aren't working with raw files, and adding code to make sure you can only add a task on a compatible queue. I'm not sure what that would look like yet. I assume most implementers won't bother.
- Remove the SDL_AsyncIOTask struct from the public interface and just return bool when creating a new task.
- Add a way to query how many tasks are still in-flight for a queue/file. We now track this number internally for queues anyhow.

**Comment by nfries88** [comment]
> * We need to figure out how to make this work with SDL_Storage, which probably means exposing both SDL_AsyncIOInterface and SDL_AsyncIOQueueInterface, telling storage people to implement both if they aren't working with raw files, and adding code to make sure you can only add a task on a compatible queue. I'm not sure what that would look like yet. I assume most implementers won't bother.

probably simpler to just expose a function to add an arbitrary completion to a queue and not worry about handling incompatible queue types.

File: include/SDL3/SDL_ioasync.h (hunk 10 above)
Comment (nfries88) [reply include/SDL3/SDL_ioasync.h]: yes, rename is atomic WRT the inodes but not WRT file contents. fsync before rename is essential.

**Comment by icculus** [comment]
Linux io_uring support is in. This is something I was planning to knock out real fast this morning, so of course it took all day, but it shows the existing API maps pretty well to it.

(@nfries88 and @jaedan, feel free to take a look if you're interested.)

**Comment by icculus** [comment]
Also:

> Force a sync during close: maybe. Since it's not synchronous, it's not unreasonable, but we'd have to add an fsync method to SDL_IOStream so the generic backend can use it.

SDL_IOStream syncs files to disk in SDL_FlushIO() now (with no implicit flush if you just SDL_CloseIO() it), so this is now doable.

I'm still inclined to just sync all files during the async close work, since it's doesn't have to block, and otherwise the app is going to have to make sure the write completes before a flush is queued, so they don't run in the wrong order.

**Comment by nfries88** [comment]
io_uring's completion side is not thread-safe either, and racier than the submission side because the CQE isn't "removed" until you call io_uring_cqe_seen(), eg multiple threads may wind up getting the same cqe from io_uring_wait_cqe.

So everything from io_uring_wait_cqe/io_uring_peek_cqe until io_uring_cqe_seen needs to be inside a mutex if we want to support getting completions from the same queue from multiple threads.

**Comment by icculus** [comment]
> So everything from io_uring_wait_cqe/io_uring_peek_cqe until io_uring_cqe_seen needs to be inside a mutex if we want to support getting completions from the same queue from multiple threads.

Ugh, I assumed `seen` tells the kernel that it can reuse that slot to fill in a new completed request, not that it will keep giving out the same cqe to everyone waiting until it's marked as seen, but you're right, that's totally how it works. I'll fix that up.

> ps: now that you have an implementation that can clearly benefit from it, maybe operation batching is the next thing to look at?

If there's a reasonable way to do this in the API without it getting super-ugly, sure. But at that point we're mostly talking about reducing the number of syscalls, right? Doing so is good, but we're not trying to solve the C10k problem, so it's not high-priority for me.

**Comment by icculus** [comment]
Bumping this to 3.2.0, since the ABI lock is about to happen (we can add new stuff after ABI lock).

**Comment by nfries88** [comment]
> Ugh, I assumed `seen` tells the kernel that it can reuse that slot to fill in a new completed request, not that it will keep giving out the same cqe to everyone waiting until it's marked as seen, but you're right, that's totally how it works. I'll fix that up.

yeah, basically the entire liburing API is thread-unsafe except for the actual io_uring_enter syscalls. I'm not even 100% sure that it's safe to submit from one thread and reap from another, but it seems to work fine in practice.

> But at that point we're mostly talking about reducing the number of syscalls, right? Doing so is good, but we're not trying to solve the C10k problem, so it's not high-priority for me.

that's the main advantage. But yeah it probably the syscall overhead probably isn't significant enough that it would turn up when profiling.

**Comment by icculus** [comment]
I think the io_uring thread issues are settled in 7d4fdabf01418c0ae1ad759a62504dc763c530e8. I put a separate mutex on the submission and completion queues, and the completion side copies the data out and unlocks as fast as possible...so any serious contention probably won't be an issue in any reasonable case, and the wait() call just uses io_uring's API to block until there's new results, but then it grabs a mutex and uses the peek codepath to make sure that only one thread gets a valid event.

If the kernel wakes up multiple waiters, the existing API allows for this, so I think this part is solid now.

**Comment by icculus** [comment]
I'm wondering if we should just change...

```c
extern SDL_DECLSPEC SDL_AsyncIOTask * SDLCALL SDL_CloseAsyncIO(SDL_AsyncIO *asyncio, SDL_AsyncIOQueue *queue, void *userdata);
```

...to have a `bool flush` option, since it's trivial for the backend to flush after the close, but an app would have to make sure all writes complete before issuing a flush command, lest the flush happen _before_ the write.

We could also (or instead) add this to SDL_WriteAsyncIO.

Other options are always implicitly flush on close (easy for everyone, but less efficient for use-cases that could skip it), or add an explicit flush operation that the app is responsible for queueing correctly, or add a way to specify some operations need to serialize behind the scenes (this would be `IOSQE_IO_LINK` in io_uring, but this is sort of a pain and relies on future backends supporting it).

**Comment by slouken** [comment]
> I'm wondering if we should just change...
> 
> ```c
> extern SDL_DECLSPEC SDL_AsyncIOTask * SDLCALL SDL_CloseAsyncIO(SDL_AsyncIO *asyncio, SDL_AsyncIOQueue *queue, void *userdata);
> ```
> 
> ...to have a `bool flush` option, since it's trivial for the backend to flush before the close, but an app would have to make sure all writes complete before issuing a flush command, lest the flush happen _before_ the write.

This seems like a good idea.

**Comment by nfries88** [comment]
> I'm wondering if we should just change...
> 
> ```c
> extern SDL_DECLSPEC SDL_AsyncIOTask * SDLCALL SDL_CloseAsyncIO(SDL_AsyncIO *asyncio, SDL_AsyncIOQueue *queue, void *userdata);
> ```
> 
> ...to have a `bool flush` option, since it's trivial for the backend to flush before the close, but an app would have to make sure all writes complete before issuing a flush command, lest the flush happen _before_ the write.

that is perfectly adequate.

> We could also (or instead) add this to SDL_WriteAsyncIO.

this would be a little more questionable. I suppose it's possible some user may want to sync a rarely written file to disk but also keep it open for the purposes of reading, but this is not a viable strategy for keeping the disk coherent if doing parallel writes to different portions of the file because fsync() will sync incomplete writes and also because later write may complete before an earlier write. Getting this right basically requires the implementation to serialize writes whenever a synchronizing write is queued, which is why databases etc tend to basically implement their own disk cache in-process and do direct I/O (which is inherently synchronized with the disk) instead.

> Other options are always implicitly flush on close (easy for everyone, but less efficient for use-cases that could skip it)

probably harmless, but maybe someone would object.

> or add an explicit flush operation that the app is responsible for queueing correctly

hairy for the same reasons as synchronizing writes. 

> add a way to specify some operations need to serialize behind the scenes (this would be `IOSQE_IO_LINK` in io_uring, but this is sort of a pain and relies on future backends supporting it).

I've never seen an async framework provide chained operations without some sort of hairiness either.

**Comment by icculus** [comment]
Okay, optional flush/fsyncdata on close is in, 52c58b975eb121d1be8907eb21f5baa12d2de98b.

Unrelated, a pending TODO item is to remove SDL_AsyncIOTask from the public headers, and just return bool instead of a task handle, and this makes sense with the current API.

But code is already implemented in both backends to attempt to cancel in-flight tasks...it's not currently used because the public API doesn't offer it. If we _want_ to add it, we'll need the task handle in the public API. If we don't, we can lose the task handles and delete some code from the backends.

But if we don't offer it now, we can't add it later without adding replacement APIs that return a handle.

So which way do we want to go on this?

Canceling a task isn't guaranteed; if it hasn't started, both our threadpool and io_uring can cancel it, but otherwise they'll just have to wait for results once the work has gotten underway.

For files, this usually isn't a big deal, because presumably everything will finish in finite time. But if we ever open this up for something that can block indefinitely (like socket i/o), cancellation might become super-important. I'm 100% okay with this interface only ever being used on files, though.

**Comment by nfries88** [comment]
> For files, this usually isn't a big deal, because presumably everything will finish in finite time. But if we ever open this up for something that can block indefinitely (like socket i/o), cancellation might become super-important. I'm 100% okay with this interface only ever being used on files, though.

my super-opinionated and possibly unpopular take is that async I/O cancellability still doesn't really make sense for sockets *except for automatically at program shutdown*. If the connection is broken, the request in progress should error out.

It's also worth pointing out that while async I/O for sockets is the gold standard in scalability, if you're writing netcode for a FPS or something you definitely want kqueue/epoll/etc and non-blocking I/O over a threadpool. There's a few benchmarks that strongly suggest this is true for io_uring too, but I do know some work has gone into improving this over the past couple years.

(Note that while it seems to have been largely ignored, Windows 10 got a more epoll-like [socket readiness notification interface](https://learn.microsoft.com/en-us/windows/win32/winsock/winsock-socket-state-notifications) near the end of its cycle too.)

**Comment by slouken** [comment]
> Okay, optional flush/fsyncdata on close is in, [52c58b9](https://github.com/libsdl-org/SDL/commit/52c58b975eb121d1be8907eb21f5baa12d2de98b).
> 
> Unrelated, a pending TODO item is to remove SDL_AsyncIOTask from the public headers, and just return bool instead of a task handle, and this makes sense with the current API.
> 
> But code is already implemented in both backends to attempt to cancel in-flight tasks...it's not currently used because the public API doesn't offer it. If we _want_ to add it, we'll need the task handle in the public API. If we don't, we can lose the task handles and delete some code from the backends.
> 
> But if we don't offer it now, we can't add it later without adding replacement APIs that return a handle.
> 
> So which way do we want to go on this?
> 
> Canceling a task isn't guaranteed; if it hasn't started, both our threadpool and io_uring can cancel it, but otherwise they'll just have to wait for results once the work has gotten underway.
> 
> For files, this usually isn't a big deal, because presumably everything will finish in finite time. But if we ever open this up for something that can block indefinitely (like socket i/o), cancellation might become super-important. I'm 100% okay with this interface only ever being used on files, though.

I have mixed feelings on this. On the one hand it would be really nice to simplify the API. On the other hand I can totally see someone trying to cancel all pending I/O on shutdown or out of memory or something.

**Comment by slouken** [comment]
Also, is it time for an IORing implementation? :D

**Comment by icculus** [comment]
> Also, is it time for an IORing implementation? :D

Windows IoRing support is in, as of 26b4bf94b4daafb7010bbacf2909527de0a2387f.

If you aren't on Windows 11, it falls back to the threadpool, but it's noticeably faster on this Win11 VirtualBox VM than the threadpool version!

**Comment by slouken** [comment]
Removing SDL_AsyncIOTask cleans it up nicely, but does it make sense to add a function to cancel all the I/O on a queue?

File: src/dynapi/SDL_dynapi_procs.h [hunk 13]
```diff
@@ -1209,12 +1209,12 @@ SDL_DYNAPI_PROC(wchar_t*,SDL_wcsstr,(const wchar_t *a, const wchar_t *b),(a,b),r
 SDL_DYNAPI_PROC(long,SDL_wcstol,(const wchar_t *a, wchar_t **b, int c),(a,b,c),return)
 SDL_DYNAPI_PROC(SDL_AsyncIO*,SDL_AsyncIOFromFile,(const char *a, const char *b),(a,b),return)
 SDL_DYNAPI_PROC(Sint64,SDL_GetAsyncIOSize,(SDL_AsyncIO *a),(a),return)
-SDL_DYNAPI_PROC(SDL_AsyncIOTask*,SDL_ReadAsyncIO,(SDL_AsyncIO *a, void *b, Uint64 c, Uint64 d, SDL_AsyncIOQueue *e, void *f),(a,b,c,d,e,f),return)
-SDL_DYNAPI_PROC(SDL_AsyncIOTask*,SDL_WriteAsyncIO,(SDL_AsyncIO *a, void *b, Uint64 c, Uint64 d, SDL_AsyncIOQueue *e, void *f),(a,b,c,d,e,f),return)
-SDL_DYNAPI_PROC(SDL_AsyncIOTask*,SDL_CloseAsyncIO,(SDL_AsyncIO *a, bool b, SDL_AsyncIOQueue *c, void *d),(a,b,c,d),return)
+SDL_DYNAPI_PROC(bool,SDL_ReadAsyncIO,(SDL_AsyncIO *a, void *b, Uint64 c, Uint64 d, SDL_AsyncIOQueue *e, void *f),(a,b,c,d,e,f),return)
```
[the remark this answers is not in the document]
Comment (icculus) [reply src/dynapi/SDL_dynapi_procs.h:1212]: I cleaned that up right after ABI lock.  :)

**Comment by icculus** [comment]
> Removing SDL_AsyncIOTask cleans it up nicely, but does it make sense to add a function to cancel all the I/O on a queue?

I was thinking about that as an option. One still needs to wait for the completion, though, to free buffers that are in-flight, so all it gains you is _maybe_ some tasks will finish faster, or maybe a little less disk i/o gets started.

We could have it as a flag to SDL_DestroyAsyncIOQueue, to say "I'm going down and I don't care if this stuff finishes or not, get me out of here asap."

**Comment by icculus** [comment]
Hey, @madebr: I'm getting test failures like this:

```
22: Allocation 350: 64 bytes
22: 	0x7fbecacd5cd8: ???
22: 	0x7fbecacdb7f2: ???
22: 	0x55a9c282a089: ???
22: 	0x55a9c27f09d0: ???
22: 	0x7fbeca829d90: ???
22: 	0x7fbeca829e40: ???
22: 	0x55a9c27f0a85: ???
```

But running `ctest` or just `testautomation` on my machine doesn't trigger it. Is there something I have to do to turn on memory leak checking?

**Comment by icculus** [comment]
> We could have it as a flag to SDL_DestroyAsyncIOQueue, to say "I'm going down and I don't care if this stuff finishes or not, get me out of here asap."

Actually, this doesn't need a flag. Since you can't get the results without the queue, it's reasonable to cancel everything by default to make the queue destruction finish more quickly; the app has to assume all of it failed anyway, since any of it _could_ fail without warning.

**Comment by icculus** [comment]
...of course, we don't actually _have_ a list of pending tasks for the queue to cancel them, so screw it, I'm leaving it alone. I'll probably remove the cancel stuff from the implementation once this merges, so we can reasonable find it in revision control if we want to restore it later.

**Comment by icculus** [comment]
Still need to figure out the memory leaks in the test program, but otherwise, I think we should merge this. The only thing pending is what to do with the Storage interface, but it's becoming clear we'll want to rev that interface for other reasons, too, so it doesn't make sense to hold this up in the meantime.

**Comment by icculus** [comment]
> Hey, @madebr: I'm getting test failures like this:
>
> 22: Allocation 350: 64 bytes
> 22: 	0x7fbecacd5cd8: ???
> 22: 	0x7fbecacdb7f2: ???
> 22: 	0x55a9c282a089: ???
> 22: 	0x55a9c27f09d0: ???
> 22: 	0x7fbeca829d90: ???
> 22: 	0x7fbeca829e40: ???
> 22: 	0x55a9c27f0a85: ???
>
> But running ctest or just testautomation on my machine doesn't trigger it. Is there something I have to do to turn on memory leak checking?

(Ping @madebr)

**Comment by slouken** [comment]
Run with the command line option `--trackmem`

**Comment by madebr** [comment]
> > Hey, @madebr: I'm getting test failures like this:
> > 22: Allocation 350: 64 bytes
> > 22: 	0x7fbecacd5cd8: ???
> > 22: 	0x7fbecacdb7f2: ???
> > 22: 	0x55a9c282a089: ???
> > 22: 	0x55a9c27f09d0: ???
> > 22: 	0x7fbeca829d90: ???
> > 22: 	0x7fbeca829e40: ???
> > 22: 	0x55a9c27f0a85: ???
> > But running ctest or just testautomation on my machine doesn't trigger it. Is there something I have to do to turn on memory leak checking?
> 
> (Ping @madebr)

Configure your CMake project with `-DSDL_TRACKMEM=ON` (like ci does), and run ctest again.

I was hoping CI would show the stack traces when building with `RelWithDebInfo` cmake build type.
Does building in `Debug` build type also show nothing?

It's a far fetch, but maybe.
In 4c00433b69986f04832fa0356c0fc4ee8f220ca1, I moved the stack collection to report time so the tests run faster.
This late report generation might fail if the leaking library has been unloaded already.

**Comment by icculus** [comment]
Interestingly, `valgrind --leak-check=full ./test/testtimer --trackmem` does _not_ think this is leaking, but the --trackmem output does:

```c
Memory allocations:
Allocation 0: 64 bytes
	0x498e6cf: SDL_malloc_REAL+0x2f
	0x49968ce: SDL_CreateTimer+0xe0
	0x4996a97: SDL_AddTimerNS_REAL+0x31
	0x48c7509: SDL_AddTimerNS+0x34
	0x10dc95: main+0x345
	0x4ca01ca: __libc_init_first+0x8a
	0x4ca028b: __libc_start_main+0x8b
	0x10d665: _start+0x25
Allocation 1: 40 bytes
	0x498e744: SDL_calloc_REAL+0x49
	0x4b4f8c7: SDL_CreateMutex_REAL+0x2a
	0x4996560: SDL_InitTimers+0x39
	0x49967ec: SDL_CheckInitTimers+0xd
	0x4996850: SDL_CreateTimer+0x62
	0x4996a64: SDL_AddTimer_REAL+0x39
	0x48c74d3: SDL_AddTimer+0x31
	0x10dbf3: main+0x2a3
	0x4ca01ca: __libc_init_first+0x8a
	0x4ca028b: __libc_start_main+0x8b
	0x10d665: _start+0x25
Allocation 2: 64 bytes
	0x498e6cf: SDL_malloc_REAL+0x2f
	0x49968ce: SDL_CreateTimer+0xe0
	0x4996a64: SDL_AddTimer_REAL+0x39
	0x48c74d3: SDL_AddTimer+0x31
	0x10dfc9: main+0x679
	0x4ca01ca: __libc_init_first+0x8a
	0x4ca028b: __libc_start_main+0x8b
	0x10d665: _start+0x25
Allocation 3: 32 bytes
	0x498e6cf: SDL_malloc_REAL+0x2f
	0x4b5013f: SDL_CreateSemaphore_REAL+0x19
	0x4996583: SDL_InitTimers+0x5c
	0x49967ec: SDL_CheckInitTimers+0xd
	0x4996850: SDL_CreateTimer+0x62
	0x4996a64: SDL_AddTimer_REAL+0x39
	0x48c74d3: SDL_AddTimer+0x31
	0x10dbf3: main+0x2a3
	0x4ca01ca: __libc_init_first+0x8a
	0x4ca028b: __libc_start_main+0x8b
	0x10d665: _start+0x25
Allocation 4: 9 bytes
	0x498e6cf: SDL_malloc_REAL+0x2f
	0x4992b0d: SDL_strdup_REAL+0x30
	0x49952a6: SDL_CreateThreadWithPropertiesRuntime_REAL+0x138
	0x49953c2: SDL_CreateThreadRuntime_REAL+0x85
	0x49965e0: SDL_InitTimers+0xb9
	0x49967ec: SDL_CheckInitTimers+0xd
	0x4996850: SDL_CreateTimer+0x62
	0x4996a64: SDL_AddTimer_REAL+0x39
	0x48c74d3: SDL_AddTimer+0x31
	0x10dbf3: main+0x2a3
	0x4ca01ca: __libc_init_first+0x8a
	0x4ca028b: __libc_start_main+0x8b
	0x10d665: _start+0x25
Allocation 5: 112 bytes
	0x498e744: SDL_calloc_REAL+0x49
	0x499525e: SDL_CreateThreadWithPropertiesRuntime_REAL+0xf0
	0x49953c2: SDL_CreateThreadRuntime_REAL+0x85
	0x49965e0: SDL_InitTimers+0xb9
	0x49967ec: SDL_CheckInitTimers+0xd
	0x4996850: SDL_CreateTimer+0x62
	0x4996a64: SDL_AddTimer_REAL+0x39
	0x48c74d3: SDL_AddTimer+0x31
	0x10dbf3: main+0x2a3
	0x4ca01ca: __libc_init_first+0x8a
	0x4ca028b: __libc_start_main+0x8b
	0x10d665: _start+0x25
Allocation 6: 64 bytes
	0x498e6cf: SDL_malloc_REAL+0x2f
	0x49968ce: SDL_CreateTimer+0xe0
	0x4996a64: SDL_AddTimer_REAL+0x39
	0x48c74d3: SDL_AddTimer+0x31
	0x10dbf3: main+0x2a3
	0x4ca01ca: __libc_init_first+0x8a
	0x4ca028b: __libc_start_main+0x8b
	0x10d665: _start+0x25
Total: 0.38 Kb in 7 allocations
==305100== 
==305100== HEAP SUMMARY:
==305100==     in use at exit: 714,589 bytes in 168 blocks
==305100==   total heap usage: 3,294 allocs, 3,126 frees, 1,972,232 bytes allocated
==305100== 
==305100== 288 bytes in 1 blocks are possibly lost in loss record 23 of 52
==305100==    at 0x484D953: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==305100==    by 0x40145AB: calloc (rtld-malloc.h:44)
==305100==    by 0x40145AB: allocate_dtv (dl-tls.c:370)
==305100==    by 0x40145AB: _dl_allocate_tls (dl-tls.c:629)
==305100==    by 0x4D13606: allocate_stack (allocatestack.c:429)
==305100==    by 0x4D13606: pthread_create@@GLIBC_2.34 (pthread_create.c:655)
==305100==    by 0x4B4F4CF: SDL_SYS_CreateThread (SDL_systhread.c:115)
==305100==    by 0x499530B: SDL_CreateThreadWithPropertiesRuntime_REAL (SDL_thread.c:383)
==305100==    by 0x49953C1: SDL_CreateThreadRuntime_REAL (SDL_thread.c:403)
==305100==    by 0x49965DF: SDL_InitTimers (SDL_timer.c:230)
==305100==    by 0x49967EB: SDL_CheckInitTimers (SDL_timer.c:295)
==305100==    by 0x499684F: SDL_CreateTimer (SDL_timer.c:309)
==305100==    by 0x4996A63: SDL_AddTimer_REAL (SDL_timer.c:363)
==305100==    by 0x48C74D2: SDL_AddTimer (SDL_dynapi_procs.h:61)
==305100==    by 0x10DBF2: main (testtimer.c:143)
==305100== 
==305100== 2,617 bytes in 1 blocks are definitely lost in loss record 25 of 52
==305100==    at 0x484DB80: realloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==305100==    by 0x498E499: real_realloc (SDL_malloc.c:6323)
==305100==    by 0x11A419: SDLTest_LogAllocations (SDL_test_memory.c:443)
==305100==    by 0x1110E9: SDLTest_CommonDestroyState (SDL_test_common.c:745)
==305100==    by 0x10E29C: main (testtimer.c:285)
==305100== 
==305100== LEAK SUMMARY:
==305100==    definitely lost: 2,617 bytes in 1 blocks
==305100==    indirectly lost: 0 bytes in 0 blocks
==305100==      possibly lost: 288 bytes in 1 blocks
==305100==    still reachable: 711,684 bytes in 166 blocks
==305100==         suppressed: 0 bytes in 0 blocks
==305100== Reachable blocks (those to which a pointer was found) are not shown.
==305100== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==305100== 
==305100== For lists of detected and suppressed errors, rerun with: -s
==305100== ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 0 from 0)
icculus@lucha:~/projects/SDL-icculus/buildbot$ 
```

To be clear, SDL_Quit() legit cleans up the completed timer list, which we intentionally keep as an allocation pool until SDL_Quit is called, so even SDL_RemoveTimer() will "leak" in this regard, as it currently stands.

**Comment by madebr** [comment]
Does allocation and deallocation happen through SDL_malloc/SDL_free?
Does deallocation happen after `SDL_TrackAllocations`?

**Comment by icculus** [comment]
Okay, this is the moment, let's merge this...!

**Review by slouken — APPROVED** [review]

**Comment by sezero** [comment]
Is there a specific reason to use `__kernel_time64_t` and `long long` in SDL_asyncio_liburing.c? Can we not simply use `Sint64` instead? E.g.:
```diff
--- a/src/file/io_uring/SDL_asyncio_liburing.c
+++ b/src/file/io_uring/SDL_asyncio_liburing.c
@@ -284,3 +284,3 @@ static SDL_AsyncIOTask *liburing_asyncioqueue_wait_results(void *userdata, Sint3
     } else {
-        struct __kernel_timespec ts = { (__kernel_time64_t) timeoutMS / SDL_MS_PER_SECOND, (long long) SDL_MS_TO_NS(timeoutMS % SDL_MS_PER_SECOND) };
+        struct __kernel_timespec ts = { (Sint64) timeoutMS / SDL_MS_PER_SECOND, (Sint64) SDL_MS_TO_NS(timeoutMS % SDL_MS_PER_SECOND) };
         liburing.io_uring_wait_cqe_timeout(&queuedata->ring, &cqe, &ts);
```

**Comment by icculus** [comment]
I think it's just what the struct uses, at least on the headers I looked at, but the PR to change this should be fine.

**Comment by icculus** [comment]
Just adding a "best practices" section to the async i/o docs. @jaedan and @nfries88, does this cover it well?

## Best Practices

Simple non-blocking i/o--for an app that just wants to pick up data whenever it's ready without losing framerate waiting on disks to spin--can use whatever pattern works well for the program. In this case, simply call [SDL_ReadAsyncIO](SDL_ReadAsyncIO), or maybe [SDL_LoadFileAsync](SDL_LoadFileAsync), as needed. Once a frame, call [SDL_GetAsyncIOResult](SDL_GetAsyncIOResult) to  check for any completed tasks and deal with the data as it arrives.

If two separate pieces of the same program need their own i/o, it is legal for each to create their own queue. This will prevent either piece from accidentally consuming the other's completed tasks. Each queue does require some amount of resources, but it is not an overwhelming cost. Do not make a queue for each task, however. It is better to put many tasks into a single queue. They will be reported in order of completion, not in the order they were submitted, so it doesn't generally matter what order tasks are started.

One async i/o queue can be shared by multiple threads, or one thread can have more than one queue, but the most efficient way--if ruthless efficiency is the goal--is to have one queue per thread, with multiple threads working in parallel, and  attempt to keep each queue loaded with tasks that are both started by and consumed by the same thread. On modern platforms that can use newer interfaces, this can keep data flowing as efficiently as possible all the way from storage hardware to the app, with no contention between threads for access to the same queue.

Written data is not guaranteed to make it to physical media by the time a closing task is completed, unless [SDL_CloseAsyncIO](SDL_CloseAsyncIO) is called with its `flush` parameter set to `true`, which is to say that a successful result here can still result in lost data during an unfortunately-timed power outage if not flushed. However, flushing will take longer and may be unnecessary, depending on the app's needs.

**Comment by nfries88** [comment]
I would probably add a note that for very simple cases or where the data is needed immediately it is generally more efficient and much simpler logic to just use normal blocking I/O.

But aside for that, that advice looks pretty complete.
