### PR TITLE
Fix WINRT_IsScreenKeyboardShown on Xbox

### LINKED ISSUE #6433: WINRT_IsScreenKeyboardShown always returns false on Xbox
Two underlying issues here:

- OcculledRect is the recommended way for universal apps but not Xbox (see docs [here](https://learn.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.inputpane.visible?view=winrt-22621))
- The Xbox recommended way of checking Visible property does not work on latest UWP/Xbox

Workaround is to use the Showing/Hiding events to track state on Xbox.

I'll have a PR shortly.

### PR DESCRIPTION
**Pull request by tomcashman**
## Description
Fixes WINRT_IsScreenKeyboardShown on Xbox. I kept existing behavior the same on universal apps/windows mobile to avoid issues for developers on those platforms.

## Existing Issue(s)
Fixes #6433

### CODE REVIEW

File: src/video/winrt/SDL_winrtkeyboard.cpp [hunk 1]
```diff
@@ -386,6 +386,30 @@ WINRT_ProcessCharacterReceivedEvent(Windows::UI::Core::CharacterReceivedEventArg
 
 #if NTDDI_VERSION >= NTDDI_WIN10
 
+bool WINRT_InputPaneVisible = false;
```
Comment (flibitijibibo) [inline src/video/winrt/SDL_winrtkeyboard.cpp:389]:
```suggestion
static bool WINRT_InputPaneVisible = false;
```

**Review by flibitijibibo — COMMENTED** [review]
One minor thing, otherwise lgtm

File: src/video/winrt/SDL_winrtkeyboard.cpp (hunk 1 above)
Comment (tomcashman) [reply src/video/winrt/SDL_winrtkeyboard.cpp]: Updated now
