### PR TITLE
events: Fix spurious early returns from SDL_WaitEvent()/SDL_WaitEventTimeout()

### LINKED ISSUE #5780: SDL_WaitEvent timeouts when no joystick is connected
This seems to be connected with #4886, cc @cgutman

`SDL_WaitEvent` should not timeout, but it does seem to due to capping of timeout passed to backend by 3 seconds (`PERIODIC_POLL_INTERVAL_MS`) and not handling the timeout internally.

This can be observed with `SDL_WaitEvent` returning 0, indicating an error, but not setting any sdl error, so `SDL_GetError()` returns an empty string

Repro:

```c
#include <SDL2/SDL.h>
#include <stdio.h>
#include <stdlib.h>

int main()
{
	if (SDL_Init(SDL_INIT_EVERYTHING) != 0) {
		fprintf(stderr, "SDL_Init Error: %s\n", SDL_GetError());
		return EXIT_FAILURE;
	}

	SDL_Window* win = SDL_CreateWindow("Hello World!", 100, 100, 620, 387, SDL_WINDOW_SHOWN);
	if (win == NULL) {
		fprintf(stderr, "SDL_CreateWindow Error: %s\n", SDL_GetError());
		return EXIT_FAILURE;
	}

    for (;;) {
        SDL_Event e;
        if (!SDL_WaitEvent(&e)) {
            const char* error = SDL_GetError();
            if (!error || strcmp(error, "") == 0) {
                printf("Seems like SDL_WaitEvent signaled a timeout\n");
            } else {
                printf("Got a real failure: %s\n", error);
            }
        } else {
            if (e.type == SDL_QUIT) {
                printf("SDL_QUIT\n");
                break;
            }
        }
    }

	SDL_DestroyWindow(win);
	SDL_Quit();

	return EXIT_SUCCESS;
}
```

Compiled and ran with:
```
gcc -o main main.c $(pkg-config sdl2 --cflags --libs)
./main
```

If nothing happens, it would print "Seems like SDL_WaitEvent signaled a timeout" around every 3 seconds, indicating a timeout in `SDL_WaitEvent` which should not happen

It seems that it does not happen when a joystick is connected (there seems to be a different code path used there).

The bug also doesn't seem to trigger on Wayland

Was reproduced on KDE with X11

### PR DESCRIPTION
**Pull request by cgutman**
## Description
Fixes the spurious `SDL_WaitEvent()` timeout bug described in #5780

## Existing Issue(s)
Fixes #5780

### CODE REVIEW

**Comment by sezero** [comment]
Is the issue present in 2.0.22 and earlier or is it a new thing?

File: src/events/SDL_events.c [hunk 1]
```diff
@@ -973,7 +973,10 @@ SDL_WaitEventTimeout_Device(_THIS, SDL_Window *wakeup_window, SDL_Event * event,
             status = _this->WaitEventTimeout(_this, loop_timeout);
             /* Set wakeup_window to NULL without holding the lock. */
             _this->wakeup_window = NULL;
-            if (status <= 0) {
+            if (status == 0 && loop_timeout == PERIODIC_POLL_INTERVAL_MS) {
```
Comment (slouken) [inline src/events/SDL_events.c:976]: Shouldn't this be `if (need_periodic_poll)`? The timeout could happen to be `PERIODIC_POLL_INTERVAL_MS` if it lines up just right.

Comment (cgutman) [reply src/events/SDL_events.c:976]: Yeah, it doesn't hurt if we loop again if the callers passes `PERIODIC_POLL_INTERVAL_MS` since we'll exit in the `elapsed >= (Uint32)timeout` check above, but no sense in doing that if we're not using the periodic poll anyway.

**Comment by cgutman** [comment]
> Is the issue present in 2.0.22 and earlier or is it a new thing?

Looks like it was present in 2.0.18+. I'm surprised that it took this long someone to find/report it.

**Comment by DCNick3** [comment]
>Looks like it was present in 2.0.18+. I'm surprised that it took this long for someone to find/report it.

It is only reproducible when there are no events for whole 3 seconds, which is kind of rare.

Was found on yuzu nintendo switch emulator only when gdbstub was active (which, when hitting a breakpoint, stopped all the inside activity). Worked fine otherwise, raining with events
